### ISSUE TITLE
Non-required argument in `wp core install` when using shared user tables

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#1009]
I'm using [custom user tables](http://codex.wordpress.org/Editing_wp-config.php#Custom_User_and_Usermeta_Tables) which are shared across several installs.

When I set up subsequent sites (after the initial setup) with `wp core install` there are some arguments which are normally required that should be optional when using shared user tables.

 * Only one of `--admin_user` and `--admin_email` should be required. Either of these are sufficient to uniquely identify an existing user to use as the admin.
 * `--admin_password` should be optional.

Installation works fine currently, except the `--admin_password` argument is ignored. Maybe this should be a separate ticket.

Related core trac ticket: https://core.trac.wordpress.org/ticket/27093

**Comment by danielbachhuber** [comment]
Spent a little bit of time thinking about how we should go about this.

I'm not a huge fan of conditionally requiring arguments because (at least for now) we don't have a great way to go about this. Furthermore, custom user tables is a < 1% use case, so I don't think WP-CLI's support for it needs to be perfect.

Instead, we can just include some note that only `admin_user` is respected when installing on a site with custom user tables, and make sure to ignore `admin_email` and `admin_password`. Or, if `admin_user` doesn't exist, we can create it.
