### ISSUE TITLE
Support for creating POT files

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#1042]
Ze [gave me a pretty nice critique](http://zedejose.com/edit-flow-cant-nice-%D0%BF%D0%BE%D0%B6%D0%B8%D1%82%D0%BA%D0%B8/) of localization deficiencies in Edit Flow. Part of the problem as I'm aware of it is that I only periodically recreate the POT file because my workflow is to commit to trunk on WordPress.org, and download the POT file generated. I'd like for it to be much easier to do this on a regular basis.

It would be neat to have a suite of translation tools as a part of WP-CLI including, but not limited to, regenerating POT files. I'm not familiar-enough with all of the internal mechanics of the gettext implementation to offer recommendations beyond this.

@joehoyle mentioned he had started on this for another project and might have code to share.

**Comment by geminorum** [comment]
See also : [wemakecustom/wp-pot-generator](https://github.com/wemakecustom/wp-pot-generator)

**Comment by danielbachhuber** [comment]
#1775 added `grunt-wp-i18n`, which solves this nicely.

**Comment by voltronik** [comment]
I see generating .pot files was added in 0.19.0 but I don't understand how to generate them. 
Can you help by telling me what WP-CLI command to use?

**Comment by danielbachhuber** [comment]
> Can you help by telling me what WP-CLI command to use?

It's actually a Grunt command. After you've scaffolded a new plugin, you can do `npm install; grunt i18n` to generate files

**Comment by voltronik** [comment]
Ok, thanks. I'll take a look.

**Comment by sun** [comment]
Please consider to re-open this issue.

WP-CLI is the natural go-to solution for all WordPress plugin and theme developers.  All of the mentioned alternatives are not.

The suggestion wasn't to duplicate efforts and waste everyone's time.  The suggestion was to (re-)use and leverage the existing code of the existing i18n/l10n scripts in WP-CLI.

The seemingly official set of i18n/l10n scripts is barely documented.  And, Grunt is an insane workaround, because Grunt is not able to reliably interpret PHP code.

This topic does not only affect contributed plugins and themes, it also affects custom plugins and themes.  Developers constantly have to regenerate and manage translations for their custom extensions.  No one is aware of how painful this work is, as it happens behind the scenes.

The workflows of WordPress extension development have to become more accessible.  This is your unique chance to pave the way for major improvements in the WordPress eco-system.  Do not miss this chance.

This is what we're looking for:
```sh
$ wp translation template <plugin/theme-path> [<new-pot-file-pathname>]
$ wp translation create <plugin/theme-path> <locale>
$ wp translation ...
```
Focus is on the very first command (for now).

Thoughts?
