### ISSUE TITLE
Handle non-writable temp dir better

### ISSUE THREAD

**Issue by scribu** [wp-cli/wp-cli#1118]
> PHP Warning: copy(/tmp/wp-cli-cacert.pem): failed to open stream: Permission denied in phar:///usr/local/bin/wp/php/commands/core.php on line 142

We can steal a few ideas from WP's `get_temp_dir()` function:

* [x] show a warning if the temporary directory isn't writable
* [x] try to fall back on `ini_get('upload_tmp_dir');`

Follow-up from #1117

**Comment by halfgaar** [comment]
We also have problems writing to wp-cli-cacert.pem because we have multiple wordpress sites running, all as different user. The first one that creates the file, blocks the others. 

And, writing to a predictable name is a symlink attack vulnerability.

**Comment by shakaran** [comment]
This should be reopened. If the file is already created by other user is always reporting

`Warning: copy(/tmp/wp-cli-cacert.pem): failed to open stream: Permission denied in phar:///usr/local/bin/wp/php/utils.php on line 29`

The wp-cli should check if the file is present and try write another one instead if it cannot delete it because is written by other user (in a shared hosting).

For example write /tmp/wp-cli-cacert.pem.1 if it is already written or /tmp/wp-cli-cacert.pem.2, etc

Alternatively, the wp-cli, should always delete the temporal file created when it finish, because I have to execute always the following in terminal for avoid errors with other users or executions:

rm -rf /tmp/wp-cli-cacert.pem

**Comment by acki** [comment]
+1

**Comment by acki** [comment]
@danielbachhuber Plz reopen this ticket. It is not solved yet. (WP CLI 1.4.0)

**Comment by danielbachhuber** [comment]
@acki Please open a new issue with all relevant details, thanks.
