### ISSUE TITLE
Dashes or underscores

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#1122]
There seems to be a mixture of dashes and underscores used in parameter and flag names. For example, the options for `wp user create` are:

`
<user-login>
<user-email>
[--role=<role>]
[--user_pass=<password>]
[--user_registered=<yyyy-mm-dd>]
[--display_name=<name>]
[--send-email]
[--porcelain]`

Is there a pattern here that I'm not seeing? Or do these parameter and flag names need to be standardised to use one or the other?

**Comment by skoblenick** [comment]
I would agree with @johnbillion your CLI should have a defined and consistent pattern for options not following the poor design choices made by existing tools/APIs/frameworks. For example the PHP string library, the naming conventions follow two completely different patterns simply because they were written by different people; i.e. str_replace and strpos. This subject was nicely covered by Kevin Lacker at Parse Developer Day 2013 in a talk about [How to Design Great APIs](https://youtu.be/qCdpTji8nxo).

**Comment by danielbachhuber** [comment]
> I would agree with @johnbillion your CLI should have a defined and consistent pattern for options not following the poor design choices made by existing tools/APIs/frameworks.

I agree with this in theory. In practice though, both dashes and underscores are used throughout, and standardizing on one vs. the other would cause pretty substantial breaking changes at this point.
