### ISSUE TITLE
HHVM: wp core download fails due to /tmp/ directory missing

### ISSUE THREAD

**Issue by javorszky** [wp-cli/wp-cli#1135]
## Context

Using this vagrant box: https://github.com/vicb/hhvm-vagrant
## Problem
- `wp core download` fails. The temp `.tar.gz` file gets downloaded. If I specify `--path=/tmp/wp-core-test`, the files are there, however I get the following error after a while:

``` shell
vagrant@precise64:/vagrant/www/wp$ wp core download

Notice: Undefined variable: handle in phar://wp-cli.phar/php/WP_CLI/Loggers/Regular.php on line 17

Warning: Not a valid stream resource in phar://wp-cli.phar/php/WP_CLI/Loggers/Regular.php on line 12

Notice: Undefined variable: handle in phar://wp-cli.phar/php/WP_CLI/Loggers/Regular.php on line 12

Warning: Not a valid stream resource in phar://wp-cli.phar/php/WP_CLI/Loggers/Regular.php on line 12

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'DirectoryIterator::__construct(/tmp/wp_53528e87aecdd/): failed to open dir' in :
Stack trace:
#0 (): DirectoryIterator->__construct()
#1 (): FilesystemIterator->__construct()
#2 phar://wp-cli.phar/php/commands/core.php(109): RecursiveDirectoryIterator->__construct()
#3 phar://wp-cli.phar/php/commands/core.php(102): Core_Command::_copy_overwrite_files()
#4 phar://wp-cli.phar/php/commands/core.php(79): Core_Command::_extract()
#5 (): Core_Command->download()
#6 phar://wp-cli.phar/php/WP_CLI/Dispatcher/CommandFactory.php(35): call_user_func()
#7 (): {closure}()
#8 phar://wp-cli.phar/php/WP_CLI/Dispatcher/Subcommand.php(239): call_user_func()
#9 phar://wp-cli.phar/php/WP_CLI/Runner.php(245): WP_CLI\Dispatcher\Subcommand->invoke()
#10 phar://wp-cli.phar/php/WP_CLI/Runner.php(252): WP_CLI\Runner->run_command()
#11 phar://wp-cli.phar/php/WP_CLI/Runner.php(36): WP_CLI\Runner->_run_command()
#12 phar://wp-cli.phar/php/WP_CLI/Runner.php(514): WP_CLI\Runner->do_early_invoke()
#13 phar://wp-cli.phar/php/wp-cli.php(20): WP_CLI\Runner->before_wp_load()
#14 phar://wp-cli.phar/php/boot-phar.php(5): include()
#15 /usr/bin/wp(4): include()
#16 {main}
vagrant@precise64:/vagrant/www/wp$
```

This is the contents of the `/tmp` folder:

``` shell
vagrant@precise64:/tmp$ ls -la
total 10580
drwxrwxrwx  3 root    root       4096 Apr 19 14:56 .
drwxr-xr-x 24 root    root       4096 Apr 19 13:36 ..
-rwxrwxrwx  1 vagrant vagrant    2285 Apr 19 13:47 jTn4Rg
-rwxrwxrwx  1 root    root          0 Apr 19 13:46 perf-6857.map
-rwxrwxrwx  1 vagrant vagrant  500009 Apr 19 13:47 perf-7064.map
-rwxrwxrwx  1 vagrant vagrant  445909 Apr 19 13:47 perf-7069.map
-rwxrwxrwx  1 root    root     121966 Apr 19 13:51 perf-7097.map
-rwxrwxrwx  1 root    root     120745 Apr 19 13:51 perf-7100.map
-rwxrwxrwx  1 vagrant vagrant  357344 Apr 19 13:51 perf-7102.map
-rwxrwxrwx  1 vagrant vagrant  444124 Apr 19 13:52 perf-7104.map
-rw-rw-r--  1 vagrant vagrant  468442 Apr 19 14:00 perf-7113.map
-rw-rw-r--  1 vagrant vagrant  452030 Apr 19 14:05 perf-7116.map
-rw-rw-r--  1 vagrant vagrant  477588 Apr 19 14:07 perf-7120.map
-rw-rw-r--  1 vagrant vagrant  143413 Apr 19 14:26 perf-7183.map
-rw-rw-r--  1 vagrant vagrant  242824 Apr 19 14:26 perf-7185.map
-rw-r--r--  1 root    root     120745 Apr 19 14:33 perf-7217.map
-rw-r--r--  1 root    root     120745 Apr 19 14:55 perf-7223.map
-rw-r--r--  1 root    root     124453 Apr 19 14:55 perf-7226.map
-rw-r--r--  1 root    root     124453 Apr 19 14:55 perf-7228.map
-rw-rw-r--  1 vagrant vagrant  469267 Apr 19 14:56 perf-7230.map
-rwxrwxrwx  1 vagrant vagrant    1366 Apr 19 13:36 vagrant-shell
drwxrwxr-x  5 vagrant vagrant    4096 Apr 19 14:56 wordpress
-rw-rw-r--  1 vagrant vagrant 5810471 Apr 19 14:56 wp_53528e87aecdd.tar.gz
-rwxrwxrwx  1 vagrant vagrant  229054 Apr 19 14:56 wp-cli-cacert.pem
vagrant@precise64:/tmp$
```

The `.tar.gz` file is there. The directory isn't. I've made the directory 777.

**Comment by alexissusset** [comment]
It seems that this issue still exists, compiled wp-cli from github master code and still getting the following error:
Downloading WordPress 4.2.1 (en_US)...

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'DirectoryIterator::__construct(/tmp/wp_55474735c30a2/): failed to open dir' in :
Stack trace:
#0 (): DirectoryIterator->__construct()
#1 (): FilesystemIterator->__construct()
#2 /usr/local/php/commands/core.php(211): RecursiveDirectoryIterator->__construct()
#3 /usr/local/php/commands/core.php(204): Core_Command::_copy_overwrite_files()
#4 /usr/local/php/commands/core.php(181): Core_Command::_extract()
#5 (): Core_Command->download()
#6 /usr/local/php/WP_CLI/Dispatcher/CommandFactory.php(52): call_user_func()
#7 (): Closure$WP_CLI\Dispatcher\CommandFactory::create_subcommand()
#8 /usr/local/php/WP_CLI/Dispatcher/Subcommand.php(295): call_user_func()
#9 /usr/local/php/WP_CLI/Runner.php(304): WP_CLI\Dispatcher\Subcommand->invoke()
#10 /usr/local/php/WP_CLI/Runner.php(311): WP_CLI\Runner->run_command()
#11 /usr/local/php/WP_CLI/Runner.php(52): WP_CLI\Runner->_run_command()
#12 /usr/local/php/WP_CLI/Runner.php(608): WP_CLI\Runner->do_early_invoke()
#13 /usr/local/php/wp-cli.php(20): WP_CLI\Runner->before_wp_load()
#14 /usr/local/php/boot-fs.php(17): include()
#15 {main}

This issue happens when running Ubuntu 14.04.2 LTS with HHVM installed from http://dl.hhvm.com/ubuntu repository

**Comment by amadex** [comment]
Is there already any solution on this?... It seems the script tries to find a folder like "/tmp/wp_55474735c30a2/" when the folder that is uncompressed is "/tmp/wordpress/"...

**Comment by malfborger** [comment]
same issue on ubuntu with hhvm

**Comment by mosamlife** [comment]
same issue with hhvm

**Comment by chuckreynolds** [comment]
same

**Comment by Ore4444** [comment]
same
