### ISSUE TITLE
`wp network meta` commands bypass `site-options` cache

### ISSUE THREAD

**Issue by mgburns** [wp-cli/wp-cli#1628]
We were recently running WP-CLI against an install with a persistent object cache and noticed `wp network meta get` was returning stale results and `wp network meta update` was not clearing the `site-options` cache.

Looks like this is caused by usage of the `*_metadata` functions for managing site options (by way of https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/CommandWithMeta.php).

I noticed there's an open PR that implements a `site option` command (https://github.com/wp-cli/wp-cli/pull/1259). Looks like that would address this issue (and I'm assuming supersede `network meta`) if accepted.

**Comment by danielbachhuber** [comment]
Thanks for the report, seems reasonable.

**Comment by danielbachhuber** [comment]
> (and I'm assuming supersede network meta)

Took a look at this. I'm not 100% sure about deprecating `network meta` in favor of `site option`. Oddly, `get_site_option()` [bypasses `get_metadata()`](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/option.php#L1004), although it might be that it was never updated because the last touch on that line was a long time ago: https://core.trac.wordpress.org/changeset/14410

I think we might need both.
