### ISSUE TITLE
multisite-convert does not work for non-english install

### ISSUE THREAD

**Issue by Fab1en** [wp-cli/wp-cli#1703]
The `wp core multisite-convert` command adds the multisite constant at the wrong place in `wp-config.php` when this file is not in English.

Here is the end of the resulting file with a fr_FR WordPress install :
```
/** 
 * Pour les développeurs : le mode deboguage de WordPress.
 * 
 * En passant la valeur suivante à "true", vous activez l'affichage des
 * notifications d'erreurs pendant votre essais.
 * Il est fortemment recommandé que les développeurs d'extensions et
 * de thèmes se servent de WP_DEBUG dans leur environnement de 
 * développement.
 */ 
define('WP_DEBUG', false); 

/* C'est tout, ne touchez pas à ce qui suit ! Bon blogging ! */

/** Chemin absolu vers le dossier de WordPress. */
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

/** Réglage des variables de WordPress et de ses fichiers inclus. */
require_once(ABSPATH . 'wp-settings.php');
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', false);
$base = '/';
define('DOMAIN_CURRENT_SITE', 'mywebsite.localhost');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);

/* That's all, stop editing!
```

**Comment by danielbachhuber** [comment]
Thanks for the report. I'll need to give some thought as to the best way to fix this.

**Comment by Fab1en** [comment]
The following code in `Core_Command` class should be modified to take into account non-english installs : 
```
private static function modify_wp_config( $content ) {
	$wp_config_path = Utils\locate_wp_config();
	$token = "/* That's all, stop editing!";
	list( $before, $after ) = explode( $token, file_get_contents( $wp_config_path ) );
	file_put_contents( $wp_config_path, $before . $content . $token . $after );
}
```
For example, in french installs, the `$token` value should be `/* C'est tout, ne touchez pas à ce qui suit !`. This value could be extracted from the `wp-config-sample.php` file which contains the initial content for wp-config.php file and is not modified.

**Comment by danielbachhuber** [comment]
I've spent some time thinking about this, and haven't identified a better token to use that's guaranteed to be more reliable. Because the process of modifying the wp-config.php is quite ugly, I'm concerned about making a change which could cause a regression.

For now, I'm going to address this issue by warning the end user when the token can't be found, instead of erroneously inserting the constants into the end of the file.

**Comment by Fab1en** [comment]
Thanks for the time your spent on this. I know that this could cause regressions, but here is what I propose : when the english token is not found, why not trying to get the one used in wp-config-sample.php file ? The token can be easily extracted from this file (it's 5 lines before the end) and is more than likely to match.

**Comment by danielbachhuber** [comment]
> when the english token is not found, why not trying to get the one used in wp-config-sample.php file ? The token can be easily extracted from this file (it's 5 lines before the end) and is more than likely to match.

I don't want to try to pull something from wp-config-sample.php. Because we can't extract the token in a precise manner (e.g. WP-CLI can't know definitively that it's found the correct token at 5 lines before the end).

Given the lack of precision in the possible implementations, it's better just to put the decision on the end user.
