### ISSUE TITLE
if an import halts due to max_execuation_time, what happens if I re-run it?

### ISSUE THREAD

**Issue by VickG** [wp-cli/wp-cli#1708]
This might be a stupid question... but I ran an import and had 9k posts imported by the time it hit the server max_execution_time which made the import halt.

I have since then increased the max_execuation_time.

My question:
Should I erase my 9k posts that were imported until it halted, or is it safe to re-run the import without deleting everything that got imported until it halted?

thanks

**Comment by danielbachhuber** [comment]
> is it safe to re-run the import without deleting everything that got imported until it halted?

It's safe-ish. The WordPress Importer has a mechanism to prevent duplicate content from being created. However, because your script halted mid-execution, there's probably one item that's broken to some degree. Also, there are cleanup tasks that run at the end of the import that didn't run, so at least some of your content didn't get cleaned up.

If it's possible, you should empty the site and start over. `wp site empty` will delete all posts, comments, and terms without affecting your options or users. If you use it though, you'll need to manually delete the uploads directory.
