### ISSUE TITLE
Save cache to $XDG_CACHE_HOME instead of ~/.wp-cli/cache

### ISSUE THREAD

**Issue by marcinant** [wp-cli/wp-cli#1747]
As in topic. On linux systems it could be great to keep cache files in $XDG_CACHE_HOME and use $XDG_CONFIG_HOME for config files.

**Comment by danielbachhuber** [comment]
I'm not familiar with `$XDG_CACHE_HOME`. Can you share a bit more detail, with suggestions on how we can accommodate with backwards compat?

**Comment by marcinant** [comment]
Everything is described here:
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

All modern Linux distributions support XDG and by default applications keep their config in: 
~/.config/[appname]

and cache in:

~/.cache/[appname]

So, cache should go to ~/.cache/wp-cli/core instead of ~/.wp-cli/cache/core

On Ubuntu and Debian systems $XDG_CACHE_HOME, $XDG_DATA_HOME and $XDG_CONFIG_HOME environment variables are not set and these systems just use defaults as described in basedir-spec. For example:
"If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used."

WP-CLI should just test if $XDG_* variables are set and fallback to defaults suggested by xdg specification. That's all.

**Comment by marcinant** [comment]
You can also take a look how it's now solved in Composer:
https://github.com/composer/composer/pull/1407

**Comment by szepeviktor** [comment]
You may set `WP_CLI_CACHE_DIR`. Please consider the number of Windows and OSX users.
But yes, on linux we could change `$home/.wp-cli/cache` to `$home/.cache/wp-cli`. I use XGD in my shell scripts. XDG means X Desktop Group.

**Comment by danielbachhuber** [comment]
I'm open to making this change, but I'm concerned about backwards compatibility — or lack thereof. Unless there's a reasonable suggestion for backwards compat, I think we'll save this change for v1.0.0

**Comment by COLABORATI** [comment]
Composer has this feature now, it would be great if it wp-cli would follow. What is the status?

**Comment by danielbachhuber** [comment]
Given the backwards compatibility concerns and that we have a `WP_CLI_CACHE_DIR` environment variable you can set to customize the cache directory, I don't think it's worthwhile to make this change.

**Comment by TomaszGasior** [comment]
Each application should be compatible with standards of platform it's developed for. Linux support means required changed should be made to be compatible with XDG. 

Most of apps handle legacy config directories by first checking for existence of legacy config directory and reading it if exists instead XDG-compatible directory. I think it's completely possible in this app too.

This issue is not critical so maintainers of this software don't have to spend his own time to fix it. But the issue should not be closed as "not worthwhile" since this is still OS standards incompatibility, Instead, it should be kept open making the work possible for community of the affected OS.
