### ISSUE TITLE
plugin update from zip file

### ISSUE THREAD

**Issue by jthayne** [wp-cli/wp-cli#1762]
Would it be possible to extend the `plugin update` command to be able to update from a file or url similar to the `plugin install` command?  I will try and get to a patch for this when I can, but if someone can get to it before then, it would be helpful.

**Comment by danielbachhuber** [comment]
You can use `wp plugin install <path-to-file> --force`

**Comment by theMikeD** [comment]
I'm confused here @danielbachhuber . The OP asked about updating, you replied with a command that used install, and I updated the docs to reflect your command. What did I miss?

**Comment by danielbachhuber** [comment]
> The OP asked about updating, you replied with a command that used install

You should use the `wp plugin install <file>` command to update a plugin with a ZIP file. Although it's `wp plugin install`, it's the same thing behind the scenes.

> and I updated the docs to reflect your command

You updated the docs for `wp plugin update` to include arguments that aren't supported by `wp plugin update`. Furthermore, command docs are automagically generated from the PHPdoc, so that's not even the proper place to update.

**Comment by theMikeD** [comment]
Ah, I hit the wrong file, my bad. 

That said, if you'd like updates to the docs by those without intimate familiarity with the code, it would be helpful if the proper place/method to update them was listed in the wp-cli.github.com readme file or some other obvious place because, if it *is* described somewhere, it's not obvious.

**Comment by danielbachhuber** [comment]
> That said, if you'd like updates to the docs by those without intimate familiarity with the code, it would be helpful if the proper place/method to update them was listed in the wp-cli.github.com readme file or some other obvious place because, if it is described somewhere, it's not obvious.

Good suggestion. I've made it more obvious: https://github.com/wp-cli/wp-cli.github.com/commit/0678f9f7e3bb472273c378969426834b204a4652
