### ISSUE TITLE
Provide flags to display changelog and readme information with `plugin` command

### ISSUE THREAD

**Issue by tw2113** [wp-cli/wp-cli#1910]
In short, provide ways to see changelog and readme.txt data when requested to help make decisions when updating.

**Comment by danielbachhuber** [comment]
> Provide flags to display changelog and readme information with `plugin` command

Can you explain how this might work, with a bit more detail?

**Comment by tw2113** [comment]
my thoughts were something like `wp plugin changelog $plugin_name` or whatever best fits, and it displays the available changelog similar to how the modal popup does when you click the "View version #.#.# details." link on the updates page. Fetch and display the same content.

**Comment by danielbachhuber** [comment]
Great — seems reasonable.

**Comment by szepeviktor** [comment]
See the Wiki: https://github.com/wp-cli/wp-cli/wiki/Shell-Tips

**Comment by szepeviktor** [comment]
The one remaining obstacle is a readme2text converter class.

**Comment by mrwweb** [comment]
A big ol' +1 for this. A couple quick additions:

1. I like the `wp plugin changelog <plugin-name>` syntax proposed.
1. I could also see this built in to `wp plugin search` instead of—or in addition to—that first option via `wp plugin search <search> --field=changelog`
1. Being able to pick out a specific version's changes with `wp plugin changelog <slug> [--version=<version>]` would be super-extra awesome but, I suspect, unfeasible.

**Comment by danielbachhuber** [comment]
Closing this at wontfix — best implemented as a community package first.
