### ISSUE TITLE
Command to delete all inactive plugins and/or themes

### ISSUE THREAD

**Issue by drywall** [wp-cli/wp-cli#1954]
Is there anything in the works to make it easier to delete inactive stuff? Something like:

`wp plugin delete --inactive`

Right now the easiest way I've found to do this is with:

`wp plugin list --status=inactive --fields=name --format=csv | tail --lines=+2 | xargs wp plugin delete`

...which is not terribly convenient or self-explanatory. If nothing's in the works but people would like it, I'm happy to attempt to cobble something together...

**Comment by danielbachhuber** [comment]
You can use:

```
wp plugin delete $(wp plugin list --status=inactive --field=name)
```

I'll add it as an example to `wp plugin delete`

**Comment by drywall** [comment]
Thanks! What version of wp-cli supports this?

**Comment by danielbachhuber** [comment]
> Thanks! What version of wp-cli supports this?

v0.12.0 and higher

**Comment by tmuka** [comment]
I noticed this referenced on the blog, wanted to pop by with a warning to be careful since the one-liner will happily delete the required parent theme of a wp child theme.

On my servers I use something like this to whitelist a few themes I know are parent themes.
`sudo wp --allow-root theme list --status=inactive --enabled=no --field=name | egrep -v "(twentyfifteen|genesis|business|thematic|twentytwelve)" | xargs -0 -d"\n" wp --allow-root theme delete`

A better way would be to first list the active theme, then grep it's style.css file for "Template:"  which would indicate it's a child theme. i didn't have a one liner for this, but i might try to come up with one using something like this to return the active theme's parent.
`grep "Template:" $(find `pwd` -name $(wp --allow-root theme list --status=active --field=name))/style.css | cut -d: -f2 | xargs`

maybe it'd be cleaner to make the parent of an active theme return a status that isn't "inactive"...

**Comment by danielbachhuber** [comment]
> maybe it'd be cleaner to make the parent of an active theme return a status that isn't "inactive"...

Or we could have `parent` as the status for an "active" parent theme?

**Comment by tmuka** [comment]
yeah, i like that.

**Comment by danielbachhuber** [comment]
Cool, #2033
