### ISSUE TITLE
Issue updating wp-cli

### ISSUE THREAD

**Issue by b-long** [wp-cli/wp-cli#1962]
When attempting to run `wp cli update`, I receive the following error: 

```shell
[user@host /var/www/html]$ wp cli update
You have version 0.19.1. Would you like to update to 0.19.2? [y/n] y
Downloading from https://github.com/wp-cli/wp-cli/releases/download/v0.19.2/wp-cli-0.19.2.phar...
New version works. Proceeding to replace.
Error: Cannot move /tmp/wp_55c02efd45b5c.phar to /usr/local/bin/wp
```
Note, the current executable is owned by the same user: 
```shell
[user@host /var/www/html]$ ls -l /usr/local/bin/wp 
-rwxrwxr-x 1 user user 1368135 Jun  5 02:23 /usr/local/bin/wp
# Debug info
[user@host /var/www/html]$ php --version
PHP 5.3.29 (cli) (built: May 12 2015 22:42:19) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies

```

Am I missing something?

**Comment by danielbachhuber** [comment]
What are the permissions for `/tmp/wp_55c02efd45b5c.phar`?

**Comment by b-long** [comment]
Sorry about that; the permissions are 775: 

```shell
[user@host /tmp]$ ls -l /tmp/wp_55c02efd45b5c.phar
-rwxrwxr-x 1 user user 1365588 Aug  4 03:18 /tmp/wp_55c02efd45b5c.phar
```

**Comment by danielbachhuber** [comment]
I don't have any good ideas, unfortunately :/

**Comment by nyordanov** [comment]
@b-long - if you manually replace `/usr/local/bin/wp` with [this file](https://www.dropbox.com/s/jqfkllebkxa6so2/wp-cli.phar?dl=1), what happens if you then run `wp cli update --debug`? This is a "fake" 0.19.0 - it is the current master branch + https://github.com/nyordanov/wp-cli/commit/1a76044c2d3de6317b9467450f76a5a7f8224238 Feel free to build it yourself if you'd like to.

This should show us why `replace()` fails. The more interesting question is why `is_writable()` returns a false positive.

In any case `sudo wp cli update --allow-root` should work.

**Comment by b-long** [comment]
Perhaps it has something to do with permissions?

```shell
[user@host /tmp]$ rm /usr/local/bin/wp
rm: cannot remove ‘/usr/local/bin/wp’: Permission denied
[user@host /tmp]$ ls -l /usr/local/bin/wp
-rwxrwxr-x 1 user user 1368135 Jun  5 02:23 /usr/local/bin/wp
[user@host ~]$ getfacl /usr/local/bin/wp 
getfacl: Removing leading '/' from absolute path names
# file: usr/local/bin/wp
# owner: user
# group: user
user::rwx
group::rwx
other::r-x
```

I replaced /usr/local/bin/wp with the wp-cli.phar (renamed and ensured permissions were the same), however the output didn't include any extra deubug information.  I did opt to build it myself (from your `cli-update-errors` branch; I'm not sure why the `--debug` flag didn't seem to work: 

```shell
[user@host html]$ wp cli update --debug
Success: WP-CLI is at the latest version.
```

**Comment by nyordanov** [comment]
`--debug` didn't work because the update didn't fail this time.

Anyway, it appears the issue is this: http://superuser.com/a/331124

I'm not sure what we can do about this. Do you have the same problem when updating composer? `wp cli update` is similar to `composer self-update` and they also use `rename` to replace the currently installed file with the update: https://github.com/composer/composer/blob/69210d5bc130f8cc9f96f99582a041254d7b9833/src/Composer/Command/SelfUpdateCommand.php#L189

**Comment by szepeviktor** [comment]
Is `/usr/local/bin` files should be owned by root with permissions: 644 and 755.

**Comment by danielbachhuber** [comment]
@nyordanov worth making note of this somewhere?

**Comment by danielbachhuber** [comment]
Actually, with #2003, we'll throw an error when the parent directory isn't writable.

**Comment by b-long** [comment]
I'm not sure if this is **actually** solved (at least for RHEL / Amazon Linux users) @danielbachhuber @nyordanov  .  Consider this : 

```shell
[user@host ~]$ wp cli update
Error: /usr/local/bin is not writable by current user
[user@host ~]$ sudo !!
sudo wp cli update
sudo: wp: command not found
[user@host ~]$ cat /etc/*release
NAME="Amazon Linux AMI"
VERSION="2015.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2015.03"
PRETTY_NAME="Amazon Linux AMI 2015.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2015.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2015.03
```
Following the normal install process (per http://wp-cli.org/ ), it seems that the `root` user can't see `/usr/local/bin/wp`

**Comment by szepeviktor** [comment]
> sudo: wp: command not found

This shows that `/usr/local/bin` is not in root's PATH.

**Comment by b-long** [comment]
@szepeviktor I agree it's not on root's PATH :smile: I was trying to point out that either the install instructions should be modified (on http://wp-cli.org/ ), or when wp-cli is run as a normal user, it could try to escalate privileges.  Otherwise, it's inevitable that other user's will run into this who may not be familiar with modifying permissions / PATH.  If we fix the install procedures we won't have to address future user's who have this problem.

**Comment by szepeviktor** [comment]
`sudo` warns you:

> With great power comes great responsibility.

So if you install wp-cli to a system location then you should know how to upgrade it.

**Comment by rnmccandless** [comment]
Instead of moving the `wp-cli.phar` executable to `/usr/local/bin/wp` as suggested by http://wp-cli.org/#installing, it's best to put it in one of the following listed directories in `$ sudo su -c 'echo $PATH'`. You can move wp-cli by `$ sudo mv /usr/local/bin/wp /usr/bin/`. After, any user (including root now) can use it with or without sudo, and any user can update wp-cli via sudo. Remember to log out and log back in again after you've moved wp-cli - otherwise you will get an error like: `$ wp
-bash: /usr/local/bin/wp: No such file or directory`.

**Comment by danielbachhuber** [comment]
> Instead of moving the wp-cli.phar executable to /usr/local/bin/wp as suggested by http://wp-cli.org/#installing, it's best to put it in one of the following listed directories in $ sudo su -c 'echo $PATH'

Why?

> Remember to log out and log back in again after you've moved wp-cli - otherwise you will get an error like: $ wp -bash: /usr/local/bin/wp: No such file or directory.

This is incorrect. If the directory you've moved WP-CLI to is already on your PATH, you don't need to log out and log back in.

**Comment by szepeviktor** [comment]
It is useful to follow standards: http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/usr.html

**Comment by danielbachhuber** [comment]
> It is useful to follow standards:

Just to clarify, the standard for `/usr/local/bin` is:

> The original idea behind '/usr/local' was to have a separate ('local') '/usr' directory on every machine besides '/usr', which might be just mounted read-only from somewhere else. It copies the structure of '/usr'. These days, '/usr/local' is widely regarded as a good place in which to keep self-compiled or third-party programs. The /usr/local hierarchy is for use by the system administrator when installing software locally. It needs to be safe from being overwritten when the system software is updated. It may be used for programs and data that are shareable amongst a group of hosts, but not found in /usr. Locally installed software must be placed within /usr/local rather than /usr unless it is being installed to replace or upgrade software in /usr.

`/usr/local/bin` is the proper place to put WP-CLI, not `/usr/bin`.

**Comment by rnmccandless** [comment]
> Why?

Why not? The goal is to allow either have sudo access or root access to wp-cli so that wp-cli can be used and updated via root or sudo. When you move the wp-cli phar file to `/usr/local/bin/wp`, root does not have access to this path.

> This is incorrect. If the directory you've moved WP-CLI to is already on your PATH, you don't need to log out and log back in.

Have you tried this? You should know that `bash` can cache the full path to the commands. When you move the already installed `wp` and then try to `wp`, it can fail because it tries to access the original directory in `/usr/local/bin/wp`. Another way is to clear the `bash` cache via `$ hash -d wp` or `$ hash -r` instead of logging out / in.

**Comment by szepeviktor** [comment]
> When you move the wp-cli phar file to /usr/local/bin/wp, root does not have access to this path.

Please reconsider your answer.

**Comment by rnmccandless** [comment]
@szepeviktor revised.

**Comment by szepeviktor** [comment]
What OS are you running?

**Comment by szepeviktor** [comment]
In Debian `/etc/profile`
```bash
if [ "`id -u`" -eq 0 ]; then
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
else
  PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
fi
export PATH
```

**Comment by rnmccandless** [comment]
Thanks for the suggestion @szepeviktor.

We're using RedHat 6.6. The root `$PATH` only includes `/sbin:/bin:/usr/sbin:/usr/bin`.

I thought about just including the directory `/usr/local/bin/` to the root `$PATH`, but we don't want to include all commands listed in this directory all the time.

Perhaps instead of moving wp-cli to `/usr/bin`, one could execute: `sudo su - -c "wp"` which will include the current user's `$PATH` (including the `/usr/local/bin`) into the root `$PATH` for that session only. To update, `sudo su - -c "wp cli update"` to update wp-cli or do any other privileged activities with wp-cli with sudo. Additionally, one could also login with sudo: `sudo su -` which `-` helps to include the user's `$PATH`.

**Comment by danielbachhuber** [comment]
Just a heads up — WP-CLI discourages use of `wp` as root, and doesn't formally support it.

**Comment by szepeviktor** [comment]
It is quiet sad that Redhat does not follow standards. As /usr/bin is a *system* dir the best I can tell you is
`ln -s /usr/local/bin/wp /usr/bin/`
