### ISSUE TITLE
Make `wp core language update` updating all installed languages

### ISSUE THREAD

**Issue by duritong** [wp-cli/wp-cli#2021]
Currently `wp core language update` only updates the current active language.
However, installed but not active languages are still reported as having updates available in the Wordpress GUI.
It would be nice if there is a way from the cli to update the installed languages as well.

**Comment by duritong** [comment]
The cli ui looks like:

```
wp language list | grep -v uninstalled
language	english_name	native_name	status	update	updated
de_DE	German	Deutsch	installed	available	2015-09-04 18:46:16
en_US	English (United States)	English (United States)	active	none	
# wp core language update
Success: Translations updates are not needed for the 'English (US)' locale.
```

However, the wordpress looks like:

![wordpress_update](https://cloud.githubusercontent.com/assets/9511/9774734/a4296ac6-574a-11e5-9479-f82741d4d8c6.png)

**Comment by middlesister** [comment]
+1 for this.

I have a site that has two languages installed, but the active language is en_US

After updating anything - core, plugin or theme - i need to

`wp core language activate sv_SE
wp core language update
wp core language activate en_US`

I now do it every time after an update as a routine, since I don't want to bother with going to the admin UI to see if there are new translations. If there would be a way to automate this further I would be happy.

**Comment by fazen** [comment]
+1

Same problem than @middlesister one. But I can't update other language.
 

I have a site that has two languages installed, but the active language is en_US

I have a
After updating anything - core, plugin or theme - i need to

wp core language activate sv_SE wp core language update wp core language activate en_US

I now do it every time after an update as a routine, since I don't want to bother with going to the admin UI to see if there are new translations. If there would be a way to automate this further I would be happy.

**Comment by fazen** [comment]
@middlesister , same problem here, but I can't update!

`wp core language activate it_IT; wp core language update`

gives:

`Success: Language activated.`
`Success: Translations updates are not needed for the 'English (US)' locale.`

**Comment by apermo** [comment]
+1 I have the same issue.
