### ISSUE TITLE
Use tagged version of WordPress develop test suite

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2050]
Because the WordPress develop test suite [doesn't guarantee backwards compat between versions](https://core.trac.wordpress.org/ticket/33888), we should make sure `install-wp-tests.sh` uses the branched version corresponding with the tag.

**Comment by torounit** [comment]
+1

**Comment by keesiemeijer** [comment]
I think the WP_TESTS_DIR that phpunit is using is set in [bootstrap.php](https://github.com/wp-cli/wp-cli/blob/master/templates/bootstrap.mustache#L3). If the environment variable is set it will always use that version of the testsuite. What's the reason the environment variable is used?

**Comment by danielbachhuber** [comment]
> What's the reason the environment variable is used here?

To be able to set directory PHPUnit looks in for the WordPress testing framework.

**Comment by danielbachhuber** [comment]
Related #2119

**Comment by danielbachhuber** [comment]
Here's the current version endpoint: http://api.wordpress.org/core/version-check/1.7/

**Comment by danielbachhuber** [comment]
From WordPress Slack:

```
dd32 [7:17 AM] @danielbachhuber fyi we may return more offerings over either in the future (no idea what). But if you just want the latest version string, you could also try API version 1.0 or 1.1.
```

**Comment by keesiemeijer** [comment]
I've provisioned my vagrant (VVV) and use the new [install-wp-tests.sh](https://github.com/wp-cli/wp-cli/blob/master/templates/install-wp-tests.sh) file (from 0.21.0-alpha). I'm still getting the fatal errors regarding this issue locally. 
```
Fatal error: Class 'WP_REST_Server' not found
```
This is because the VVV [bash_profile](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/master/config/bash_profile#L31) points the WP_TESTS_DIR to the test framework from the development branch. I can fix this by removing that line from from the bash_profile, but I think it will confuse a lot of users using VVV.

Another point regarding the new `install-wp-tests.sh` code when installing WordPress for the tests:
```bash
if [ -d $WP_CORE_DIR ]; then
		return;
fi
```
Consider the following scenario:

Do tests for WordPress latest (**4.3.1**) with
```bash
bash bin/install-wp-tests.sh wordpress_test root '' localhost latest
phpunit
```

This will create the WP core directory and use the latest WordPress version for your test.
Now do tests for  WordPress **4.2**
```bash
bash bin/install-wp-tests.sh wordpress_test root '' localhost 4.2
phpunit
```
The directory exists (with WP 4.3.1 ) .  The unit tests use WP **4.3.1** instead of the version you wanted (**4.2**) .

There should be a test if the WP core directory contains the WordPress version you want to test against.

**Comment by danielbachhuber** [comment]
> This is because the VVV bash_profile points the WP_TESTS_DIR to the test framework from the development branch. I can fix this by removing that line from from the bash_profile, but I think it will confuse a lot of users using VVV.

Can you open an issue with VVV please?

**Comment by danielbachhuber** [comment]
> Another point regarding the new install-wp-tests.sh code when installing WordPress for the tests:

The conditional was added in 01dd52e5f7822245a5fa06e27b8ff5b99248f4ed (11 months ago). I'll consider the situation you're describing with #2119

**Comment by keesiemeijer** [comment]
I will open an issue with VVV. Thanks for all the work you do for this project.
