### ISSUE TITLE
"wp core update-db --network" not dismissing the notice in the network admin

### ISSUE THREAD

**Issue by borissamardzija** [wp-cli/wp-cli#2094]
Hello,

I am using nightly version (WP-CLI 0.21.0-alpha-a2f40ae) for testing `wp core update-db --network` and I noticed that after updating, the notice 

> Thank you for Updating! Please visit the Upgrade Network page to update all your sites.

is not dismissed in the network admin.

That's because [db version check](https://github.com/WordPress/WordPress/blob/39fb7992a98a4a3d79619ee155d86512fbc4feae/wp-admin/includes/ms.php#L749)  in WordPress so that must be updated too.

Please see https://github.com/wp-cli/wp-cli/issues/683#issuecomment-138950583

**Comment by danielbachhuber** [comment]
We [are updating the db version](https://github.com/wp-cli/wp-cli/blob/master/php/commands/core.php#L1004) stored in the database if all of the updates were successful.

Can you share the full output of `wp core update-db --network` ?

**Comment by borissamardzija** [comment]
Ah, somehow I overlooked that line of code :)

This is the output of `wp core update-db --network`
```
Database upgraded successfully on xxx1
Warning: Database failed to upgrade on xxx2
Database upgraded successfully on xxx3
Database upgraded successfully on xxx4
Warning: Database failed to upgrade on xxx5
Database upgraded successfully on xxx6
...
Success: WordPress database upgraded on 1677/1708 sites.
```

Now I see that these sites where db upgrade fail are all archived or deleted.

I have (sub)domain mapping set for them eg. `xxx1.mydomain.com` so when site is deleted or archived, subdomain is removed and from that moment, that site is not accessible.

Could that be the issue here? I also have that problem when doing "manual" network upgrade from network admin panel, so in order to upgrade these sites, I need to archive / delete them before.

I have also looked [westonruter/multisite-network-upgrade](https://gist.github.com/westonruter/beb6120e61e9691e88ac#file-multisite-network-upgrade-php-L38) command and what I see is that only sites that are not archived / deleted / spam are being upgraded.

**Comment by danielbachhuber** [comment]
> Could that be the issue here? I also have that problem when doing "manual" network upgrade from network admin panel, so in order to upgrade these sites, I need to archive / delete them before.

Seems like it could be the problem. Mind opening a core ticket on this subject, so we can see what core's opinion on the matter is?

**Comment by borissamardzija** [comment]
You mean [WordPress core] (https://make.wordpress.org/core/reports/)?

**Comment by danielbachhuber** [comment]
Yes. Core Trac: https://core.trac.wordpress.org/

**Comment by danielbachhuber** [comment]
Actually, easier. Ping @jeremyfelt

**Comment by jeremyfelt** [comment]
Yeah, there are a few improvements that are needed for the network db upgrade process in general.

For an update to be successful, the server needs to be able to access the individual site with `wp_remote_get()` so that all of the code is loaded in the context of that site when the upgrade occurs. If a domain is invalid, if a cert is bad, or if the server itself doesn't have the proper DNS for that to occur, then an update will fail.

In core, we loop through the sites 5 at a time. Once the last set of 5 is reached, the network option is updated so that the notice disappears. If any site fails, `wp_die()` fires and halts the entire thing, which is really ugly. There's no great way to continue.

I've done some ugly custom stuff in our configuration to help get past broken domains/certs and continue with the upgrade process. It'd be really nice to clean that process up and provide more helpful information.

That all said, WP-CLI is probably handling it correctly from a command line perspective. If not all sites were successfully upgraded, and they are going to be left as is, then the update of the network level version should be done manually.

**Comment by borissamardzija** [comment]
But in core, just active sites are upgraded (not archived, spam and deleted), right? I think WP-CLI should follow core behavior on this.

The problem is, when I run `wp core update-db --network` the notice won't dissappear, so I have to run manual network update from browser which will then remove it (because it won't try to upgrade archived / spam / deleted sites).

Current approach also has potential performance issue on networks with large number of such sites, network upgrade will take considerably more time than really needed.

**Comment by jeremyfelt** [comment]
> But in core, just active sites are upgraded (not archived, spam and deleted), right? I think WP-CLI should follow core behavior on this.

Ahh, I missed that part before. Yes, the query is explicitly for "active" sites.

**Comment by danielbachhuber** [comment]
> Ahh, I missed that part before. Yes, the query is explicitly for "active" sites.

Cool. I'll get that fixed.

**Comment by danielbachhuber** [comment]
@borissamardzija thanks for using WP-CLI nightly and reporting this bug!

**Comment by borissamardzija** [comment]
It works really nice now :+1: 

```
Database upgraded successfully on xxx1
Database upgraded successfully on xxx2
Database upgraded successfully on xxx3
Database upgraded successfully on xxx4
Database upgraded successfully on xxx5
Database upgraded successfully on xxx6
...
Success: WordPress database upgraded on 1099/1099 sites.
wp core update-db --network  203,37s user 36,34s system 43% cpu 9:08,13 total
```

Thank you for this great tool and support!

**Comment by srguglielmo** [comment]
I'm seeing this issue on WP-CLI 0.23.0.

I upgraded WP core using `wp core update`. Then I ran `wp core update-db --network` to update the database for all sites on my network. It cycles through all the sites and prints a success message:
"_Database upgraded successfully on ..._"
and finally ends with:
"_Success: WordPress database upgraded on 1952/1955 sites_"

However, in the admin dashboard on any of the sites on my network, it is still prompting me to update.

![Upgrade Notice](http://i.imgur.com/2P4qRil.png)

![Upgrade Page](http://i.imgur.com/242ZCNo.png)

Running `wp core update-db --network` a second time does not get rid of the notice.

Red Hat Enterprise Linux Server release 5.11
PHP 5.3.3 (we have plans to upgrade the entire server & PHP  in progress)
WordPress 4.5.2
WP-CLI version: 0.23.0
No packages in wp-cli

**Comment by danielbachhuber** [comment]
> "Success: WordPress database upgraded on 1952/1955 sites"
> 
> However, in the admin dashboard on any of the sites on my network, it is still prompting me to update.

The message is only disabled when the upgrade process is 100% successful. You'll need to track down which three sites aren't being updated, and why.

**Comment by srguglielmo** [comment]
Ah, didn't realize that. Thanks!

**Comment by TheLastCicada** [comment]
I'm having this same issue with wp-cli version 1.0.0.  Running `wp core update-db --network` returns that all sites are already at the latest db version.  Here is the output of that command, anonymized a bit to protect site names:

```wp --allow-root core update-db --network
WordPress database already at latest db version 38590 on example.com/
WordPress database already at latest db version 38590 on internal.example.com/
WordPress database already at latest db version 38590 on internal.example.com/projects/
WordPress database already at latest db version 38590 on jobs.example.com/
WordPress database already at latest db version 38590 on internal.example.com/sys/
WordPress database already at latest db version 38590 on internal.example.com/bot/
WordPress database already at latest db version 38590 on internal.example.com/luci/
WordPress database already at latest db version 38590 on internal.example.com/docs/
WordPress database already at latest db version 38590 on internal.example.com/fff/
WordPress database already at latest db version 38590 on internal.example.com/pm/
WordPress database already at latest db version 38590 on internal.example.com/proj/
WordPress database already at latest db version 38590 on internal.example.com/ux/
WordPress database already at latest db version 38590 on internal.example.com/design/
WordPress database already at latest db version 38590 on internal.example.com/accounts/
WordPress database already at latest db version 38590 on internal.example.com/plugins/
Success: WordPress database upgraded on 15/15 sites.
```

Yet in wp-admin, I still see this banner:
![screenshot 2016-12-09 11 09 51](https://cloud.githubusercontent.com/assets/3232332/21061176/146a385c-be00-11e6-8ebe-235a4dca0a8e.png)

I chatted with @jeremyfelt and determined that this was due to the mult-network setup on here and the db version not being updated in sitemeta for one of the networks.  I would say this is a bug in wp-cli, but the support for multi-network in core is also spotty, and so few people are using a multinetwork setup, I think it is hard to justify spending much time addressing this.  So I'm just going to leave this comment here to document that update-db does not work 100% as expected on a multi-network install.

**Comment by danielbachhuber** [comment]
@TheLastCicada Can you open a new issue for this? I think I'd actually like to fix it, but want to track it separately.

**Comment by TheLastCicada** [comment]
New issue https://github.com/wp-cli/wp-cli/issues/3657
