### ISSUE TITLE
Sign releases via GPG

### ISSUE THREAD

**Issue by ypid** [wp-cli/wp-cli#2121]
Or are they just well hidden?

**Comment by danielbachhuber** [comment]
Sorry, I'm not sure I follow your question. Releases aren't signed right now, in part because they're built on Travis.

Can you clarify?

**Comment by ypid** [comment]
You can sign releases also when they are build on Travis :wink: Please check it out.

https://www.gnupg.org/gph/en/manual/x135.html

**Comment by danielbachhuber** [comment]
Apologies if this is a newbie question, but why is it necessary to sign releases via GPG when we're already distributing a hash?

**Comment by ypid** [comment]
In short: To ensure integrity. Hashes are a start, but the question is where how does the user know the hashes? For the record: Can you point me to the hashes. That would be a start.

https://en.wikipedia.org/wiki/Web_of_trust
https://en.wikipedia.org/wiki/Code_signing

**Comment by szepeviktor** [comment]
There are two types of hashes: https://github.com/wp-cli/builds/tree/gh-pages/phar

**Comment by ypid** [comment]
All right. Hashes don’t help much in proving the integrity. For this to properly be done you could build locally and sign it (only for releases). In case wp-cli builds [deterministicly](https://en.wikipedia.org/wiki/Deterministic_system), you could just build it locally, compare the binary and then sign it (without touching the Travis build stuff).

**Comment by szepeviktor** [comment]
> All right. Hashes don’t help much in proving the integrity.

Do you mean hash collision?
What is the difference between GPG signing and SHA512 hashing?

**Comment by szepeviktor** [comment]
```bash
wget -qO- https://github.com/wp-cli/wp-cli/releases/download/v0.20.1/wp-cli-0.20.1.phar|sha512sum|cut -d' ' -f1
wget -qO- https://github.com/wp-cli/builds/raw/gh-pages/phar/wp-cli.phar.sha512
```
These should give the same output. How would you modify the phar's content?

**Comment by ypid** [comment]
> Oh! I see your point: if someone modifies the phar and also the hash then he wins!

**Comment by danielbachhuber** [comment]
> Oh! I see your point: if someone modifies the phar and also the hash then he wins!

If someone was able to modify the pharmacy and the hash, then wouldn't they possibly also be able to create a new signed version? 

I'm assuming your attack vector is to steal private keys in some way. If private keys are stolen, it doesn't matter which signing method we used as both could be compromised.

**Comment by ypid** [comment]
> If someone was able to modify the pharmacy and the hash, then wouldn't they possibly also be able to create a new signed version?

Ideally not but that depends as  you mentioned on your ability to keep your private key private.

**Comment by danielbachhuber** [comment]
Ok. I've added GPG signing to the release checklist https://github.com/wp-cli/wp-cli/wiki/Release-Checklist

**Comment by ypid** [comment]
@danielbachhuber Thanks. I’m looking forward to it :wink:

**Comment by tianon** [comment]
Was the public key for these artifacts ever published anywhere?  It appears to have short ID `2F6B6B7F`, but it's not on the keyservers and I can't seem to find any other mention of it.  Any chance it could be pushed somewhere for verifying these artifacts? :pray: (or I could be linked to where I missed it? :innocent:)

(http://security.stackexchange.com/a/412 has some good information about sharing your public key, including several good keyservers that participate in the global "gossip" pool that'll automatically share your public key -- something like `gpg --keyserver keyserver.ubuntu.com --send-keys 2F6B6B7F` should do the trick)

I think it's probably also worth pointing out that the `.gpg` artifacts included in the existing `wp-cli` releases are full signed copies, so the best way to verify/use them (once that key gets shared to the keyservers) would be something like this:
```console
$ wget -O wp-cli.phar.gpg 'https://github.com/wp-cli/wp-cli/releases/download/v1.0.0/wp-cli-1.0.0.phar.gpg'
# only need to download the single ".phar.gpg" artifact since it contains the original with a signature

$ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys XXX
# this last bit ("XXX") should be replaced with the full fingerprint of the 2F6B6B7F key, once it's published (from the output of "gpg --fingerprint", with the spaces removed)
# for example, my own personal key's short ID is BF357DD4, but the full fingerprint is B42F6819007F00F88E364FD4036A9C25BF357DD4

$ gpg --batch --decrypt --output wp-cli.phar wp-cli.phar.gpg
# this should take "wp-cli.phar.gpg" and extract from it the signed bits into "wp-cli.phar"

$ chmod +x wp-cli.phar
# ready for use! (move/rename to suit personal taste)
```

In the future, it might be worth considering switching to detached signatures instead, so that the workflow becomes instead:

1. download `wp-cli.phar` and the associated detached signature
2. grab the public key to verify from somewhere
3. verify the file's signature (`gpg --batch --verify wp-cli.phar.asc wp-cli.phar`, for example)
4. profit :moneybag: 

https://www.gnupg.org/gph/en/manual/x135.html#AEN160 has a bit about that, but generally it'd be changing from

`gpg --output wp-cli.phar.gpg --sign wp-cli.phar`

to something like

`gpg --output wp-cli.phar.sig --detach-sig wp-cli.phar`

or even

`gpg --output wp-cli.phar.asc --detach-sig --armor wp-cli.phar`

(`--armor` will create a plain-text version rather than a binary signature file)

**Comment by tianon** [comment]
Just found https://github.com/wp-cli/wp-cli/issues/2919#issuecomment-222678309 -- sorry for the noise! :+1:  (hopefully threading this needle forward helps some other future travellers find this info)
