### ISSUE TITLE
Bump minimum supported WP version

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2134]
We currently support WP 3.5.2: https://github.com/wp-cli/wp-cli/blob/fac9c4fe5f2f1efcbe27eff5dc075d2e5b9eda49/php/WP_CLI/Runner.php#L499

I think it's time to drop support for old versions of WordPress. What should we increase it to?

Related https://github.com/ankitpokhrel/Dynamic-Featured-Image/pull/49#issuecomment-146866772

**Comment by Ugoku** [comment]
I'd say it's safe to bump it to at least 3.7, since [this page](https://codex.wordpress.org/Supported_Versions) suggests lower versions do not get any updates at all, whereas 3.7 *might* get updates if any bugs found are serious enough.

Just my two cents as a recent wp-cli user who happened to stumble upon this issue :)

**Comment by szepeviktor** [comment]
3.8

**Comment by danielbachhuber** [comment]
@szepeviktor any rationale for 3.8?

**Comment by szepeviktor** [comment]
Mostly there's no rationale. I'm seeing that is widely supported.

**Comment by dfisek** [comment]
3.7 is the way to go. Since we still get security updates for 3.7 installations (latest 3.7.11).

I believe this could be a general rule, once Wordpress core drops support for a version, wp-cli can too.

**Comment by szepeviktor** [comment]
Core deprecation stats
```bash
grep -irh _deprecated_ * | grep -o "'[.0-9]\+'" | sort -n | uniq -c
      1 '0.0'
      3 '0.71'
      1 '0.72'
      1 '1.2'
      3 '1.3'
      3 '1.5'
      1 '1.5.1'
     14 '2.0'
     33 '2.1'
      3 '2.2'
      3 '2.3'
     22 '2.5'
      3 '2.6'
      7 '2.7'
     37 '2.8'
      2 '2.8.1'
      6 '2.9'
    114 '3.0'
     20 '3.1'
      3 '3.2'
     34 '3.3'
     18 '3.4'
      1 '3.4.1'
     27 '3.5'
      6 '3.6'
      6 '3.7'
      1 '3.8'
      6 '3.9'
      4 '4.0'
```

**Comment by szepeviktor** [comment]
Core versions usage stats
![version](http://i.snag.gy/fF2EO.jpg)

**Comment by Ipstenu** [comment]
I would not drop support, since by allowing it to run on 3.5.2, you can run 'wp core update' and get someone on the newest version quickly. If there's no technical reason (like supporting it prevents development, or causes a security hole) then it should be fine to leave alone.

If you DID want to remove support, it would be really nice to still have a way to run the core update. Maybe limit the feature set to JUST updates to encourage people to upgrade :)

If dropping support leaves users out in the cold without an easy upgrade path, then you will end up with less secure people. Any time you can avoid that, do it :)

**Comment by scribu** [comment]
You can upgrade from any older version using `wp core download --force`.

**Comment by danielbachhuber** [comment]
> If there's no technical reason (like supporting it prevents development, or causes a security hole) then it should be fine to leave alone.

Older versions are getting in the way of development now.

> If you DID want to remove support, it would be really nice to still have a way to run the core update. Maybe limit the feature set to JUST updates to encourage people to upgrade :)

I like this idea.

**Comment by Ipstenu** [comment]
@scribu - Not 2.9 you can't, that I'm aware of. Last time I tried it told me I had an out of date version and it wasn't supported. I'll test again. I may not have used --force, but why would that be needed? It's out of date so it should be updated.

@danielbachhuber - "getting in the way of development" is a technical reason. ;) If you can't write new code because of old code, that's totes valid. As long as it spits back "Dude, you're on an annncient version of WP. Upgrade by running 'wp core update --you-fool'!!!" with Mr T, I'm for it ;)

**Comment by johnbillion** [comment]
FYI 3.7 is now the minimum version that can be tested using the new `test-install.sh` introduced in #2050, because 3.7 was the first version which included the test suite.

**Comment by scribu** [comment]
> I may not have used --force, but why would that be needed?

Without `--force`, it refuses to download, because it detects that files are already present.

**Comment by Ipstenu** [comment]
Ah, you were talking 'download' and I was talking 'upgrade'

wp core upgrade should keep working is what I mean. Yes, download works, but that's illogical for most users (and sadly many tech support).
