### ISSUE TITLE
Install missing plugins with wp plugin command?

### ISSUE THREAD

**Issue by joemaller** [wp-cli/wp-cli#2217]
I didn't see this mentioned in past issues, but I've run into this situation a few times.

**Use case:**
Recovering a site from major failure, only the active theme files and database dumpfile still exist. The site requires a number of plugins but these weren't documented. 

It would be great if `wp plugin update --all` could gather the list of `active_plugins` from the `wp-options` table and then install them. Currently, missing plugins are just skipped. 

An alternate command might be `wp plugin install --missing`

I think I'll be able to cobble a workaround with `wp option get active_plugins`, but this would be helpful to have.

**Comment by danielbachhuber** [comment]
Unfortunately, there's no reliable way of knowing which of the plugins in `active_plugins` should be installed from WordPress.org, because custom plugins can have the same slug as a WordPress.org.

For your specific use case, I think it's worth reviewing each of the plugins present in `active_plugins`, and only install those which are actually used by the codebase.

**Comment by joemaller** [comment]
ok, thanks. It would nice if WordPress stored the entire blob of plugin metadata so more intelligent actions could be taken.

Assuming most third party plugins were installed from WordPress.org, a simple script wrapping `wp option get active_plugins` should fix most cases.
