### ISSUE TITLE
Call to a member function errors in plugins

### ISSUE THREAD

**Issue by ram-arrowebs** [wp-cli/wp-cli#2331]
Hi there,
Not sure if this is the right way to submit issues.

The following fatal errors prevent the update to get any further
plugins/addthis/addthis_addjs_new.php on line 57
plugins/contact-form-7/includes/shortcodes.php on line 174

The maintenance mode plugin when activated also prevents the cli to perform any updates
Thanks,

**Comment by danielbachhuber** [comment]
The root of the problem is that both Add This and Contact Form 7 are making calls to global variables which aren't explicitly globalized. In order to be properly fixed, both plugins need to explicitly globalize their variables.

You can use WP-CLI without fataling by employing the `--skip-plugins` flag: `wp --skip-plugins=addthis,contact-form-7 plugin update` or similar.

> The maintenance mode plugin when activated also prevents the cli to perform any updates

This is a problem of the plugin, not of WP-CLI. Again though, you can use `--skip-plugins=<maintenance-mode-plugin-slug>` to skip the loading of the plugin.
