### ISSUE TITLE
Cannot redeclare wp_get_server_protocol()

### ISSUE THREAD

**Issue by dennisjac** [wp-cli/wp-cli#2376]
Hi,
I just installed wp-cli to use with my wordpress 4.4.1 installation. When I run it in my home directory without arguments it outputs usage instructions but when I run it without arguments in my wordpress folder I get:

PHP Fatal error:  Cannot redeclare wp_get_server_protocol() (previously declared in /var/www/html/stage2.rolandtichy.de/wp-includes/load.php:18) in /var/www/html/stage2.rolandtichy.de/wp-includes/load.php on line 23

I tried the latests release version of wp-cli and the current master branch both with the same result. I can reproduce the same error when I create a test.php and require('wp-includes/load.php') twice so that's what seems to happen when running wp-cli.
Any idea what could cause this?

Output of wp --info:
```
PHP binary:	/usr/bin/php
PHP version:	5.4.16
php.ini used:	/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.22.0
```

**Comment by danielbachhuber** [comment]
> Any idea what could cause this?

Potentially a plugin or theme is calling `require('wp-includes/load.php')`

Can you try `wp --skip-themes --skip-plugins` in your WordPress directory to see if that bypasses the errors?

**Comment by dennisjac** [comment]
```wp --skip-themes``` makes it work but I can find no reference to ```wp-includes/load.php``` in ```wp-content/themes/*```.

**Comment by danielbachhuber** [comment]
Ok. Hard for me to say what it might be then, other than it's probably in your theme.

**Comment by danielbachhuber** [comment]
> What is wrong with including this file in a theme?

It loads WordPress. Your theme shouldn't need to load WordPress, given it's a WordPress theme.

> wp-cli does include it as well after all. Shouldn't wp-cli actually use require_once to prevent this kind of collision?

WP-CLI isn't a WordPress theme, it's a command line interface to WordPress. Here's some background on the why of how WP-CLI loads WordPress #1631

**Comment by dennisjac** [comment]
Indeed functions.php in the theme includes wp-config.php which seems rather pointless. Removing that line fixes things. Sorry for the noise and thanks for pointing me in the right direction.

**Comment by rosswintle** [comment]
I know this is closed, but I just wanted to add a weird behaviour that I've noticed that may be related.

This is with WP-CLI 0.23.0 running on PHP 5.5.27 on an up-to-date Mac.

If I run WP-CLI from inside the theme directory I get fatals for duplicate function definitions:

Fatal error: Cannot redeclare oikos_nav_menu_basic() (previously declared in /some/path/wordpress/wp-content/themes/my-theme/functions.php:76) in /some/path/wordpress/wp-content/themes/my-theme/functions.php on line 97

It looks like if I run WP-CLI in a theme's directory, it tries to load the functions.php file twice for some reason.

If I change to a different theme's directory (the non-active theme) and run WP-CLI there I also get odd errors.

Does WP-CLI try to load a functions.php file in the directory that you run it in?

**Comment by danielbachhuber** [comment]
> Does WP-CLI try to load a functions.php file in the directory that you run it in?

It doesn't, no.

**Comment by rosswintle** [comment]
Thanks Daniel. Would you believe it, I tracked it down to a dodgy plugin that does:

```
include(functions.php');
```

😖

Well...yes, you probably would.

**Comment by lehelmatyus** [comment]
Hi everyone,
I am using WP CLI on my local.
I am getting:
Fatal error: Cannot redeclare wp_get_server_protocol() (previously declared in C:\UniServerZ\vhosts\ ..stuff ..\wp-includes\load.php:16)
1. $ wp --skip-themes --skip-plugins  <- don't seem to help
2. didn't find require('wp-includes/load.php') in themes or plugins
BUT I do have a custom weird wp-config.php since I am hosting it on pantheon.
What do?

wp --info
PHP binary:     C:\UniServerZ\core\php56\php.exe
PHP version:    5.6.18
php.ini used:   C:\UniServerZ\core\php56\php-cli.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 1.0.0

**Comment by danielbachhuber** [comment]
@lehelmatyus Github issues aren't an appropriate venue for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. Please review http://wp-cli.org/#support

**Comment by lehelmatyus** [comment]
alright.

**Comment by jmfield2** [comment]
I was bit by this because I have slightly modified my wp-config.php to better control how wp-settings is loaded.  

The problem for me was the way the WP_CLI Runner tries to grab everything in wp-config EXCEPT the require_once for wp-settings (https://github.com/wp-cli/wp-cli/blob/d9d405a4ca01ba23e80277b8cb9000857e84e0cd/php/WP_CLI/Runner.php#L432) 

It seems like this could be done in a smarter way, but adding //require_once('wp-settings.php'); to the end of my custom require_once line was enough to fix it for now.

**Comment by pooledge** [comment]
I know it's closed, but it might by a problem solution for those using wp-config-local.php when it's available. Having same issue by getting `Fatal error:  Cannot redeclare wp_get_server_protocol() (previously declared in /siteroot/v1/wp-includes/load.php:16) in /siteroot/v1/wp-includes/load.php on line 21` I was able to overcome it by removing usual `/** Use local config file if exists */
if ( file_exists( dirname( __FILE__ ) . '/wp-config-local.php' ) ) {
	include( dirname( __FILE__ ) . '/wp-config-local.php' );
}` form wp-config.php file.

Might it make sense to add this check to wp-cli? Or is there a proper way to use wp-config-local.php so that wp-cli still works?

**Comment by MaximeCulea** [comment]
Can I ask if it's on the tube to make wp cli compatible with composer like installs ? @danielbachhuber 
Because doing @pooledge 's manipulation on server each time when using wp-cli is killing my envy of using it :(

**Comment by danielbachhuber** [comment]
@MaximeCulea WP-CLI is compatible with Composer installs.

Please see https://wp-cli/#support for available support options.
