### ISSUE TITLE
Feature request: random passwords for existing users

### ISSUE THREAD

**Issue by dsXLII** [wp-cli/wp-cli#2472]
When using wp-cli to generate new users, it can optionally generate random passwords. I'd like to be able to do this for existing users. Hypothetically:

`wp user reset-password admin`

This differs from the existing user update, in that you don't have to provide a new password on the command line.

It might even be useful to offer a quick "reset ALL users' passwords" feature, in the event of a security incident or similar. (wp user reset-all-passwords? Maybe with a --noreally required flag, to be sure you don't do it on accident.)

I'd suggest an added flag to decide whether to send the new passwords to the users' email address of record. (I wouldn't use it, but I certainly can see others wanting to do so.)

For background: I manage several sites where all authentication is external to WordPress, but the users still have to have WordPress accounts (and passwords). I'm presently using wp-cli in a complicated shell script to regularly reset all users' WP passwords, as an added security measure. This just seems like a nice-to-have feature, but since I already have a working process for this, it's certainly not crucial to me.

**Comment by danielbachhuber** [comment]
Thanks for the feature request, @dsXLII :)

I asked you to open an issue because I wrote a command for this the other week and thought it would be a good reason to publish it. I took the time this morning to put it up as a community command: https://github.com/danielbachhuber/wp-reset-password-command

If you update to the nightly build of WP-CLI `wp cli update --nightly`, you can install the command with `wp package install danielbachhuber/wp-reset-password-command`

Now that we have a distribution mechanism for community packages (#1564), I'm going to put more emphasis on building out new features as community packages as a way of dog-fooding and improving the user experience.
