### ISSUE TITLE
Command 'wp db tables' doesn't see all tables; command 'wp db repair' does! Can't use wp search-replace!

### ISSUE THREAD

**Issue by bhagerty** [wp-cli/wp-cli#2474]
I'm trying to use WP-CLI on a local development machine running XAMPP, and I'm having a weird problem. I'm trying to clone a deployed site. 

The local development server is running **MariaDB 10.0.17**. The version of wordpress is **3.9.1**, which I installed using `wp core download --version=3.9.1` (I know it's out of date, but I need to replicate an existing out-of-date site before I update it). I copied over themes and plugins from the deployed site that I'm trying to replicate. 

I imported the deployed site's database successfully in PHPMyAdmin on my local machine, and I successfully entered the database credentials in wp-config.php. The site's front page pulls up successfully. But before doing more, I need to update the site URLs throughout the database. I'd like to do this using `wp search-replace`, but I can't, because of what seems to me an inexplicable failure of WP-CLI to see the tables in my database. Here's the output of `wp --info`:
```
PHP binary:	H:\xampp2015\php\php.exe
PHP version:	5.6.14
php.ini used:	H:\xampp2015\php\php.ini
WP-CLI root dir:	C:\wp-cli
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.22.0
```
Let's say that the database is called `foo_wp`. Let's say the table prefix is `aribtraryprefix_`. The database includes a bunch of tables, as you can see from the output of `wp db repair`:
```
foo_wp.aribtraryprefix_blc_filters                    OK
foo_wp.aribtraryprefix_blc_instances                  OK
foo_wp.aribtraryprefix_blc_links                      OK
foo_wp.aribtraryprefix_blc_synch                      OK
foo_wp.aribtraryprefix_commentmeta                    OK
foo_wp.aribtraryprefix_comments                       OK
foo_wp.aribtraryprefix_cp_donations_pro               OK
foo_wp.aribtraryprefix_icl_content_status             OK
foo_wp.aribtraryprefix_icl_core_status                OK
foo_wp.aribtraryprefix_icl_flags                      OK
foo_wp.aribtraryprefix_icl_languages                  OK
foo_wp.aribtraryprefix_icl_languages_translations     OK
foo_wp.aribtraryprefix_icl_locale_map                 OK
foo_wp.aribtraryprefix_icl_message_status             OK
foo_wp.aribtraryprefix_icl_node                       OK
foo_wp.aribtraryprefix_icl_reminders                  OK
foo_wp.aribtraryprefix_icl_string_positions           OK
foo_wp.aribtraryprefix_icl_string_status              OK
foo_wp.aribtraryprefix_icl_string_translations        OK
foo_wp.aribtraryprefix_icl_strings                    OK
foo_wp.aribtraryprefix_icl_translate                  OK
foo_wp.aribtraryprefix_icl_translate_job              OK
foo_wp.aribtraryprefix_icl_translation_status         OK
foo_wp.aribtraryprefix_icl_translations               OK
foo_wp.aribtraryprefix_itsec_lockouts                 OK
foo_wp.aribtraryprefix_itsec_log                      OK
foo_wp.aribtraryprefix_itsec_temp                     OK
foo_wp.aribtraryprefix_links                          OK
foo_wp.aribtraryprefix_options                        OK
foo_wp.aribtraryprefix_postmeta                       OK
foo_wp.aribtraryprefix_posts                          OK
foo_wp.aribtraryprefix_rednao_smart_forms_entry       OK
foo_wp.aribtraryprefix_rednao_smart_forms_table_name  OK
foo_wp.aribtraryprefix_smart_donations_campaign_table OK
foo_wp.aribtraryprefix_smart_donations_donation_item  OK
foo_wp.aribtraryprefix_smart_donations_progress_table OK
foo_wp.aribtraryprefix_smart_donations_transaction_table OK
foo_wp.aribtraryprefix_term_relationships             OK
foo_wp.aribtraryprefix_term_taxonomy                  OK
foo_wp.aribtraryprefix_terms                          OK
foo_wp.aribtraryprefix_usermeta                       OK
foo_wp.aribtraryprefix_users                          OK
Success: Database repaired.
```
But I can't run wp search-replace on these tables, because wp db doesn't see them. This is the output of `wp db tables`:
```
aribtraryprefix_users
aribtraryprefix_usermeta
aribtraryprefix_posts
aribtraryprefix_comments
aribtraryprefix_links
aribtraryprefix_options
aribtraryprefix_postmeta
aribtraryprefix_terms
aribtraryprefix_term_taxonomy
aribtraryprefix_term_relationships
aribtraryprefix_commentmeta
```
As you can see, this is a truncated set of my tables. Even more problematically, wp db doesn't seem to be properly looking at their contents. I know from inspecting them in PHPMyAdmin that the actual database tables include my base URL (`www.hagertyforjudge.com`) hundreds of times. But here's what I get if I run `wp search-replace www.hagertyforjudge.com www.hagertyforjudge.dev --dry-run`:
```
+-------+--------+--------------+------+
| Table | Column | Replacements | Type |
+-------+--------+--------------+------+
+-------+--------+--------------+------+
```
I am stumped. I want to use `wp search-replace` over this database, but it's not working. The output of `wp db repair` shows that wp-cli can find my tables if it needs to, but the inconsistent output from `wp db`, and the failure of `wp search-replace`, show that something is wrong here. 

Let me know if you have suggestions, or if I can provide more info to help diagnose this possible bug.

*As a followup, I would note that [the PHP script from interconnect/It](https://interconnectit.com/products/search-and-replace-for-wordpress-databases/) worked flawlessly on this database. So this definitely seems to reflect a bug in wp-cli, not a problem with my databases.

**Comment by danielbachhuber** [comment]
You can use `wp search-replace <search> <replace> --all-tables` to search and replace against all tables in the connected database. WP-CLI uses the tables registered to `$wpdb` by default.

Is your table prefix registered in `wp-config.php`? Does the WordPress site load as expected through the browser?

**Comment by bhagerty** [comment]
Thanks for the quick response. Yes, the table prefix is registered in `wp-config.php`. If you're asking me how the site loaded before running the search and replace, my answer is that the front page loaded successfully. I didn't try to load any other pages because they weren't going to work until the URLs were replaced.

I'm a little confused by your answer. You say:
> You can use wp search-replace <search> <replace> --all-tables to search and replace against all tables in the connected database. WP-CLI uses the tables registered to $wpdb by default.

Maybe the `--all-tables` switch would have worked, but I'd call that a workaround, not really a solution. 

Doesn't it seem strange to you that `wp db tables` and `wp db repair` return a different set of tables? And doesn't it seem strange that `wp search-replace [string1] [string2] --dry-run` showed NO affected tables, even the small set of tables returned by `wp db tables`, when it's a fact that even this small set of tables included [string1]? 

If you're saying that somehow my tables didn't get registered to `$wpdb` in a way that WP-CLI understood, then how can I solve that problem? Everything in `wp-config.php` was set up properly, and as I said, the PHP script from interconnect/It worked flawlessly to search and replace the strings in this database. So it's hard for me to see how this could be a problem with my setup, as opposed to a bug in WP-CLI.

I love WP-CLI, but it seems like something related to the `search-replace` function needs to be fixed. I am happy to provide any information that I can to help you fix it. (I don't know enough to fix it myself.)

**Comment by danielbachhuber** [comment]
> Doesn't it seem strange to you that wp db tables and wp db repair return a different set of tables?

No. They are different commands.

`wp db tables` returns tables registered to `$wpdb` by default, [per the manual](http://wp-cli.org/commands/db/tables/). Similar to the flag `wp search-replace` also supports, you can use `wp db tables --all-tables` to list all tables in the database.

`wp db repair` doesn't care about which tables are registered to `$wpdb`.

> If you're saying that somehow my tables didn't get registered to $wpdb in a way that WP-CLI understood, then how can I solve that problem?

By doing more debugging, of course.

Or you can just use `--all-tables` and avoid the headache.

**Comment by lordspace** [comment]
I am seeing the same bug with the latest version of wp-cli.
I consider this as a bug because all tables have the same prefix.
In my case it was a WordPress site (5.7) and only WooCommerce (5.1.0) plugin installed.
I wanted to check if x_58c90ee3_woocommerce_downloadable_product_permissions table was created.

I suspect it has to do with the long table names. It seems the length of a mariadb table can be up to 64 chars.
In my case the longest table name length was 55 chars.
Maybe wp-cli (and wp db tables command) is skipping some tables based on the length even though they are valid and have the proper db table prefix.

```
OS:     Linux 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.11
php.ini used:   /etc/php/7.4/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/site/my-example.org/htdocs
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0
```

**Comment by designzwang** [comment]
Even though the issue is closed, I found no better place to add a comment.

I stumbled into the same issue as of now (2022-10), so it still is a  problem with wp-cli.
For me, it was a HUGE surprise that my db search and search-replace operations did not cover all tables having the prefix that is defined in wp-config.php:$table_prefix .
@lordspace suggested a problem with table name length, but this can be ruled out since in my case even short names like "wp_tm_taskmeta" and "wp_tm_tasks" ( from the WP-Optimize plugin ) were not listed by "wp db tables". So it must be an issue with how plugins set up their database configuration. 

So the only workaround to be safe is to use the --all-tables-with-prefix="XXX" flag using your $table_prefix ... 
Actually this should be noted in the wpcli docs at least ...

**Comment by wojsmol** [comment]
@designzwang Your table prefix is `wp_` or `wp_tm_`?

**Comment by designzwang** [comment]
Hello @wojsmol ,  my prefix in this installation is wp_  , and  tm_XXX are table names from the  WP-Optimize plugin.  These two tables are just examples, I had some more tables from other plugins that were not listed by "wp db tables".
Some more examples:
wp_nextend2_image_storage
wp_nextend2_section_storage
wp_nextend2_smartslider3_generators
wp_nextend2_smartslider3_sliders
wp_nextend2_smartslider3_sliders_xref
wp_nextend2_smartslider3_slides
wp_shortpixel_queue
wp_tec_series_relationships

Even though "wp_" being configured as $table_prefix, these tables are not listed by "wp db tables" and are not processed by "wp search-replace".    Like I said, that was unexpected.  When using --all-tables-with-prefix="wp_"  , all tables were shown.

**Comment by designzwang** [comment]
@wojsmol   yes, I saw the reference in Daniels old comment from 2016, and then I looked at the docs, however could not get a grip on what "registered to the database handler" means and how that could or should be done. Seems as if not all plugin authors do this "registration". If you have a pointer how to "register", I would notify the plugin developers of the issue. 

But - Yikes!   By accident, I copied my example string from my first comment ( --all-tables-with-prefix="XXX" ) into the console of my test container, and even though the string XXX is nowhere in my table names or config, the output of "db tables" changed. It looks like this:

# db list without any params lists 18 ( of 28 ) tables:
user@7d035a68e28b:/var/www/html# wp  db tables | wc -l
     18 
# wc_ is the correct prefix in this installation - now 28 tables are found:
user@7d035a68e28b:/var/www/html# wp  db tables --all-tables-with-prefix="wc_" | wc -l
     28
# but now using a Fantasy prefix    
user@7d035a68e28b:/var/www/html# wp db tables --all-tables-with-prefix="FOObaar" | wc -l 
     28
# still showing all tables ?!

Never mind, I just added my comment for others who end up here (like me)  after having the same problem. If you consider this to be not a bug or problem, thats OK since there is a workaround ...

Regards,  Ulrich
