### ISSUE TITLE
We are not GitHub friendly

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#2489]
```
$ wp plugin install https://github.com/norcross/airplane-mode/archive/master.zip --activate
Downloading install package from https://github.com/norcross/airplane-mode/archive/master.zip...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Success: Translations updates are not needed for the 'English (US)' locale.
Activating 'airplane-mode-master'...
Success: Plugin 'airplane-mode-master' activated.
```
Thus you get `-master` added to the plugin name.

What could be the solution? `--plugin-name=airplane-mode`?

**Comment by danielbachhuber** [comment]
> Thus you get -master added to the plugin name.

Right, because it's the master branch and `-master` is included in the ZIP file. You should be able to install `https://github.com/norcross/airplane-mode/archive/develop.zip` or `https://github.com/norcross/airplane-mode/archive/my-feature-branch.zip` alongside if you like.

> What could be the solution?

You can rename the directory if you'd like.

**Comment by szepeviktor** [comment]
OK.
