### ISSUE TITLE
Permit installing local packages

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2565]
If I run `wp scaffold package`, I'd want the scaffolded package to be immediately available.

Unintentionally, we currently require a package to be available in the package index in order to be able to run `wp package install`. Additionally, Composer will error if you try to `require` a package that isn't available in the remote repository. You need to add the local path as a repository in itself.

Related #2532

**Comment by schlessera** [comment]
I had a quick look at the `wp scaffold package` command.

First of all, I wonder why you did not reuse `composer create-project` functionality. As it stands now, the command itself has to know all the details about how a package is structured. It would be cleaner and more maintainable if you had one "boilerplate" package that gets pulled in through `composer create-project` and customized via a post-install script. I'll add this as a new issue to consider.

Then I was wondering about how to make a freshly created package available immediately. A possible solution might be to have a `composer.lock` file be generated upon scaffolding.

When you hit `composer install`, it first checks whether there is a `composer.lock` file. If it finds one, it does not scan the repositories at all, it just fetches the packages from the URL that is stored in the `composer.lock` file. So, theoretically, you could have a local URL stored in that `composer.lock` file, and then `composer install` would just work.

Generating a valid `composer.lock` without running `composer update` might be troublesome, though. But combined with the approach above (having a boilerplate package be pullled in), it might just be a simple regex-replace.

**Comment by danielbachhuber** [comment]
> First of all, I wonder why you did not reuse composer create-project functionality.

I didn't know about it (or rather, had forgotten about it). 

> A possible solution might be to have a composer.lock file be generated upon scaffolding.

If our modification to composer.lock gets blown away though, we'll lose the custom package, right?

Do you have much experience with [repositories](https://getcomposer.org/doc/05-repositories.md)? I was thinking it might be possible to specify a repository of a local path, but it didn't seem to work in my testing when the path was already in the vendor directory.

**Comment by wesm87** [comment]
One way that I know of would be to initialize a git repository for the new Composer package, then specify a custom repository URL pointing to the local Git repo. For example:

```
"repositories": [
  {
    "type": "vcs",
    "url": "/path/to/new/package"
  }
],
"require": {
   "author/package": "dev-master"
}
```

I've used this method before so I could test local changes without having to push everything up to a remote repository. It looks like you're requiring the author information in the form of `author/package` so that's not an issue, but I'm not sure how complicated it would be to manage the list of custom repositories, and if someone were to move the package to a different folder it would break the custom repository URL. Still, it might be worth exploring the idea.

**Comment by schlessera** [comment]
> Do you have much experience with repositories? I was thinking it might be possible to specify a repository of a local path, but it didn't seem to work in my testing when the path was already in the vendor directory.

I have been experimenting a lot with more complex Composer setups lately, and so far I found a solution for pretty much anything with enough of digging.

The `"path"` repository type does indeed let you specify a local path to include. However, the whole point is to symlink whatever path you pass into it into your `vendor` folder. So, if you choose a package already located within you `vendor` folder, it will fail because the symlink target also exists, and even if it would work would not do much.

If your package is already located within your `vendor` folder, you don't need to pull it in anymore with `composer install`, if there is a `composer.lock` that already has stored the same version. Composer will just assume that it already fetched the correct version, without scanning the repositories.

Alternatively, you could store the package somehwere other than the `vendor` folder (a temporary folder for wp-cli?), and then the `"path"` repository type will work, symlinking it into the `vendor` folder.

**Comment by danielbachhuber** [comment]
> Composer will just assume that it already fetched the correct version, without scanning the repositories.

It would be nice if we could enable this behavior when the `composer.lock` file is missing too.

**Comment by ernilambar** [comment]
@danielbachhuber is there any quick hack for this until full feature is merged?

**Comment by danielbachhuber** [comment]
> is there any quick hack for this until full feature is merged?

To installing? Not that I'm aware of. But, you can always use the command with `--require`

**Comment by haroldangenent** [comment]
To my knowledge, there would be three (simple) options to include a local repository:

- Add a repository with [`"type": "vcs"`](https://getcomposer.org/doc/05-repositories.md#vcs) (as mentioned above)
- [`autoload`](https://getcomposer.org/doc/04-schema.md#autoload) the local package
- Add a repository with [`"type": "path"`](https://getcomposer.org/doc/05-repositories.md#path) (as mentioned above)

The `path` option would probably be the most appropriate option in this case. There would be no downside of actually needing a VCS repository that only checks out committed files (`type: vcs`).

The only minor downside (that all options have) is that you'll have to re-add the local package when `composer.json` is changed, for example when changing the autoloaded file in the package (default when scaffolding: `command.php`).

**vendor/**
In all cases, packages cannot be loaded from `vendor/`. To my knowledge, this is not possible (and probably not recommended), because Composer either checks out the files to `vendor/` (`type: vcs`) or creates a symlink there (`type: path`). Even [franzliedke/studio](https://github.com/franzliedke/studio), created for local development with Composer, doesn't support this (it uses `type: path` as well).

**Comment by danielbachhuber** [comment]
@schlessera @wesm87 @haroldangenent Thanks folks, your guidance has been really helpful. I've gotten a reasonable implementation worked out in #3484

**Comment by wesm87** [comment]
👍
