### ISSUE TITLE
Unclear on the functionality of `--only-missing` for media regenerate

### ISSUE THREAD

**Issue by ethanclevenger91** [wp-cli/wp-cli#2608]
Issue: Missing image sizes not regenerated
Environments tested: Windows 10 w/ PHP 5.6.16, [Homestead vagrant box] (https://laravel.com/docs/master/homestead) w/ PHP 7.0.2

To reproduce:

1. Upload images through WordPress media uploader
2. Define a new image size in theme's `functions.php`
3. Run `wp media regenerate --only-missing`

Expected result: Image size added in step 2 is generated for all images
Actual result: `No thumbnail regeneration needed for "[image-name]" (ID [image-id]).` output for all images

Is this as intended or perhaps a bug?

**Comment by danielbachhuber** [comment]
Sorry for the late reply, @ethanclevenger91.

I was able to reproduce your situation, although I'm not 100% clear on the expected behavior. WP-CLI's current behavior is to look at the `sizes` stored in attachment metadata, and generate image files for the sizes where the file doesn't exist.

I suppose we could also check the registered intermediate sizes too, but I'm not confident this wouldn't introduce unexpected behavior.

Thoughts?

**Comment by ethanclevenger91** [comment]
Depends on what kind of unexpected behavior you're potentially foreseeing. In my experience, I'm almost _exclusively_ using intermediate sizes that I've declared rather than the built-in ones.
