### ISSUE TITLE
wp menu item add-custom - can't insert at beginning of list

### ISSUE THREAD

**Issue by discopatrick** [wp-cli/wp-cli#2641]
It seems it's not possible to insert a menu item at the beginning of a menu. If an existing menu item already holds the position you specify, your new menu item will be placed after it.
```
# wp menu list test-menu
+-------+--------+-------+-------------------------+----------+
| db_id | type   | title | link                    | position |
+-------+--------+-------+-------------------------+----------+
| 1952  | custom | one   | http://www.one.co.uk/   | 1        |
| 1953  | custom | two   | http://www.two.co.uk/   | 2        |
| 1954  | custom | three | http://www.three.co.uk/ | 3        |
+-------+--------+-------+-------------------------+----------+

# wp menu item add-custom test-menu "before-one" "http://www.before-one.co.uk/" --position=1
Success: Menu item added.

# wp menu item list test-menu
+-------+--------+------------+------------------------------+----------+
| db_id | type   | title      | link                         | position |
+-------+--------+------------+------------------------------+----------+
| 1952  | custom | one        | http://www.one.co.uk/        | 1        |
| 1955  | custom | before-one | http://www.before-one.co.uk/ | 2        |
| 1953  | custom | two        | http://www.two.co.uk/        | 3        |
| 1954  | custom | three      | http://www.three.co.uk/      | 4        |
+-------+--------+------------+------------------------------+----------+
```
A possible solution would be to allow a flag of `--position=0` to insert an item at the beginning of the list. (Currently, that would result in the item being inserted at the end of the list, not the beginning.)

**Comment by danielbachhuber** [comment]
> If an existing menu item already holds the position you specify, your new menu item will be placed after it.

I _think_ the behavior is that it's supposed to replace the item at the position, and bump the item currently at the position down one. Do you know if this is the behavior with other positions (I haven't tested)?

**Comment by discopatrick** [comment]
Actually, you are right. Normal behaviour is that your item is inserted at the position you specify, and everything else bumps down.

So this is only an issue when you try to use `--position=1` - the item will be inserted at position 2.

**Comment by danielbachhuber** [comment]
Here's the actual problem: https://core.trac.wordpress.org/ticket/28140

When a menu item is originally created without a specified menu position, it's inserted with `menu_order=>0` (the bug). It should be inserted with `menu_order=>1`. Because it's inserted with `0` though, `position=>1` will always insert a subsequent menu item after this now magical item. And you can't pass `position=>0` because `wp_update_nav_menu_item()` treats `position=>0` as a magical argument which means "last item in the stack".

I spent a little bit of time seeing if we could somehow fix this behavior within WP-CLI, with little success. This is best fixed in core itself, as it will eventually be needed for WP-API and #1784

**Comment by discopatrick** [comment]
Agreed, this needs to be fixed in WP Core.
