### ISSUE TITLE
Migrate new single site from multisite

### ISSUE THREAD

**Issue by mantismamita** [wp-cli/wp-cli#2696]
I'm not sure if this is something that is possible already or if this is a feature request.
Can I migrate a single site from a multisite (on a staging server) into the same multisite on a production server using wp-cli without recreating all the content using individual commands? Something along the lines of `wp db export —url=singledev.multisite.com` on the dev site followed by `wp db import singledev.multisite.sql` on the live site. 

Right now I am exporting the tables from staging to the production site but that doesn't take into account the site information in the `wp_blogs` table and others. I am using `wp db export --tables=$(wp db tables --url=singledev.multisite.com --format=csv)` I am working with a team that is quite familiar with Drush and we are trying to have a similar workflow with a WordPress multisite where a subsite can be built and launched without disturbing the others in the Network.

**Comment by danielbachhuber** [comment]
Interesting use case.

It is possible to create an export with the blog's tables, like you've mentioned, but it's not easily possible to conditionally include data out of `wp_blogs` and other tables. Most of the challenge is knowing exactly what data _should_ be included. You could probably create a definition for core but, because plugins and themes can add data in arbitrary locations, it's impossible to ensure you're getting all of the data.

> Right now I am exporting the tables from staging to the production site but that doesn't take into account the site information in the wp_blogs table and others.

Do you have a good sense of what this data actually needs to be? Or, another way to look at it, what problems have you run into with missing data?

**Comment by mantismamita** [comment]
We've tried to identify exactly which tables are affected and what data needs to be included and came up with a script that was pretty close. (I can include the whole thing if you're interested) but missed something somewhere in the serialisation. The result was that one of the sites in a multisite of 45 sites became unresponsive. The environments: pre-prod and prod are exactly the same with the exception of the url. 

Here is a list of the tables identified:

- wp_site
- wp_sitemeta
- wp_blogs
- wp_blog_versions
- wp_signups
- wp_registration_log
- wp_42_commentmeta
- wp_42_comments
- wp_42_links
- wp_42_options
- wp_42_postmeta
- wp_42_posts
- wp_42_term_relationships
- wp_42_term_taxonomy
- wp_42_terms

I did a search for the url in order to determine which ones were affected as that should be the only difference between the environments.

the export script was `wp db export --tables=wp_site,wp_sitemeta,wp_blogs,wp_blog_versions,wp_signups,wp_registration_log,wp_42_commentmeta,wp_42_comments,wp_42_links,wp_42_options,wp_42_postmeta,wp_42_posts,wp_42_term_relationships,wp_42_term_taxonomy,wp_42_terms`

**Comment by danielbachhuber** [comment]
> We've tried to identify exactly which tables are affected and what data needs to be included and came up with a script that was pretty close. (I can include the whole thing if you're interested) but missed something somewhere in the serialisation. The result was that one of the sites in a multisite of 45 sites became unresponsive.

Yeah — it makes sense to me that it would be imperfect. 

I don't think this is a problem WP-CLI itself can solve at this point. Ultimately, the solution is to create a PHP-representation of the application data, such that it's much easier to select just the data you need, and move that data between environments. This is part of the impetuous for the [wp-rest-cli](https://github.com/danielbachhuber/wp-rest-cli) project.

However, it's still a fair distance from here to there. If I were in your shoes and needed to make the data sync on a repeated basis, I would potentially write a PHP script to dump and import just the data I needed, instead of all of the tables. This way, you whitelist what you need, and avoid inheriting assumptions of data you don't need.

**Comment by mantismamita** [comment]
Yeah fair enough, I think we are going to just do bash scripting and wp-cli to add the bulk of it and then just do all we can to avoid having to change things manually (PHP script sounds like a good idea). Keeping an eye on wp-rest-cli and appreciate your hard work :) Thanks for all your help.
