### ISSUE TITLE
Installing fails when a package has uncommitted changes

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2718]
```
salty-wordpress ➜  ~  wp package install runcommand/media-sideload
Installing runcommand/media-sideload (dev-master)
Updating /home/vagrant/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...

---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Dependency resolution completed in 0.036 seconds
Analyzed 2399 packages to resolve dependencies
Analyzed 45716 rules to resolve dependencies
Warning: Source directory /home/vagrant/.wp-cli/packages/vendor/danielbachhuber/wp-rest-cli has uncommitted changes.
```

Although I'm not quite sure how this would be possible with Composer, it would be nice if the package still installed when already-installed packages had uncommitted changes.

**Comment by danielbachhuber** [comment]
@aaemnnosttv @schlessera Have either of you run into this before on a standard Composer project? Suggestions as to how we could solve?

**Comment by aaemnnosttv** [comment]
This should be expected behavior because the packages are installed as `dev-master` each installed package is a cloned git repository. When Composer attempts to update a package installed as a git repository, it will try to checkout the new reference.  Since the installed package in this case had modified files, git can't checkout the new reference because the working directory is dirty.  I believe when running a `composer update` normally, Composer will ask you if you want to keep or discard the modifications with a prompt in a situation like this, but I'm guessing WP-CLI is running this non-interactively and so the safter default to not discard them is used.

I would think we would want to preserve this behavior as well to prevent accidental loss of changes.  Perhaps we could add a `--force` flag which would do a `git reset --hard` or simply just delete the installed repo first to force a clean install?

**Comment by schlessera** [comment]
Yes, that behavior is to be expected.

Also, if you are using `"path"` repositories, keep in mind that if the source is an active local git repository, it will be linked to as such, and any changes you make to the source (in whatever location that is stored) are also reflected in the symlinked `vendor` folder then.

You would first need to find out whether the changes in that git repository are something you did manually (in which case this error should stay as is), or whether the changes were somehow introduced by WP-CLI intself during an install/update process.

**Comment by danielbachhuber** [comment]
> You would first need to find out whether the changes in that git repository are something you did manually (in which case this error should stay as is), or whether the changes were somehow introduced by WP-CLI intself during an install/update process.

Huh. We could potentially run `git stash` and git stash pop` in the affected directory.

**Comment by schlessera** [comment]
That might cause merge conflicts on `git stash pop`.

**Comment by danielbachhuber** [comment]
Calling this wontfix. I don't think there's a reasonable automatic solution we can employ.

**Comment by ThatGuySam** [comment]
I ended up having to manually adding `"discard-changes" : true` to the wp-cli composer.json 
```
// Users/{ account name }/.wp-cli/packages/composer.json
...
  "config": {
    "process-timeout": 1800,
    "discard-changes" : true
  },
...
```

`.wp-cli/packages/composer.json` and then it installed successfully

I found the solution here: https://stackoverflow.com/a/38634333/1397641
