### ISSUE TITLE
Is it possible to answer yes to all prompts?

### ISSUE THREAD

**Issue by chmac** [wp-cli/wp-cli#2735]
Firstly, thanks for the awesome work on wp-cli. Makes updating a dozen sites a breeze while wrapped in a little bash magic. 👍

I get this message during our update process:

    Warning: Running WP-CLI while the APC object cache is activated can result in cache corruption.

I've seen the message before, and I realise there is some risk, but I choose to proceed. (I think I solve the problem by restarting apache afterwards which I believe flushes the APC cache, but I could be wrong!)

Is there any way I can disable this prompt? Something like `--answer=yes`.

**Comment by danielbachhuber** [comment]
> Is there any way I can disable this prompt? Something like --answer=yes.

It's not, no.

Instead, you could move your `object-cache.php` drop-in to something like `apc-cache.php`, and then conditionally load the file in `object-cache.php`:

```
<?php

if ( ! ( defined( 'WP_CLI' ) && WP_CLI ) ) {
	require_once dirname( __FILE__ ) . '/apc-cache.php';
}
```

However, I can't recommend using WP-CLI with APC cache enabled because you're likely to run into cache corruption bugs, like the error message suggests.

**Comment by chmac** [comment]
Interesting, thanks for the feedback.

Agreed, the cache corruption is a risk. I figure flushing the cache is fine, it's a low traffic site anyway. I had written some bash magic to remove the file, but this approach would be cooler. :-)
