### ISSUE TITLE
`--json` parameter in `transient get` command

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#2802]
When I run `wp transient get sample_key --json` it gives following error.
`
Error: Parameter errors:
 unknown --format parameter
`

Is that parameter name correct? I also tried `--format=json` but same error.

**Comment by danielbachhuber** [comment]
> Is that parameter name correct? I also tried --format=json but same error.

The docs for the command need to be updated to `[--format=<format>]` instead of `[--json]`

**Comment by ernilambar** [comment]
`wp transient get sample_key --format=json` also gives same error.

**Comment by danielbachhuber** [comment]
As I said, the docs for the command will need to be changed from `[--json]` to `[--format=<format>]`

WP-CLI [parses accepted arguments](http://wp-cli.org/docs/commands-cookbook/#optional-registration-arguments) from the command's PHPDoc. Because `[--format=<format>]` isn't specified in the PHPDoc, WP-CLI errors about the invalid parameter before the command is called.
