### ISSUE TITLE
Add more config options for custom setups

### ISSUE THREAD

**Issue by jpSimkins** [wp-cli/wp-cli#2854]
I have a unique setup that I use for my servers. I am trying to get unit testing setup for WordPress plugin development but the only way seems to require wp-cli. The issue with this, is that it will not work for my setup and I cannot change my setup to allow for this package. I propose more options to allow for custom setups like mine as there are many different ways that users have implemented WordPress.

To give some insight into my setup to show why it won't work...

I have a global WordPress directory on my server. I install each flavor of WordPress there and I use shell scripts to easily switch between version for a site. The file structure is similar to:

`/var/wordpress` (global wordpress directoy)
`/var/www/_SITE_` (sites directory)

I have a wp-config file that sits in the `/var/wordpress` that basically uses $_SERVER to load the proper site's wp-config file. This also allows me to have a global config to limit WordPress on PRODuction. (garbage collection and disable poor-mans cron as I use a real cron). This config loads properly and works as expected with no issues asides from with wp-cli.

Since I use $_SERVER I am not able to specify these for wp-cli so I am getting many errors as it cannot use $_SERVER.

I tried to do 

```
core config:
  extra-php: |
     $_SERVER['DOCUMENT_ROOT'] = '/var/www/wordpress.dev/public_html/';
     $_SERVER['SERVER_NAME'] = 'www.wordpress.dev';
require:
  - /var/www/wordpress.dev/public_html/wp-content/plugins/olymp-membership/_unitTests/bootstrap.php
  - /var/wordpress/wp-config.php
```
 
Trying to set the $_SERVER values in the bootstrap and even the yml file but this still fails... and for some reason tries to load the config in the wrong folder which is puzzling because no variable is being defined for the _unitTests directory.

I assumed the extra-php would be loaded before the require files but that does not seem to be the case. 

I also tried this: https://gist.github.com/samstoller/efc38eb309e62df392ea but this wasn't really my issue as I already had if pointing to the correct wp-config.

So I am puzzled as how to get this to work with my setup and I have too many sites running this way to change the system as there is nothing wrong with the setup. Just limited config for wp-cli. The documentation is lacking and trying to find all the values for the yml file requires being a Google master... which I thought I was until I was researching this.

Hopefully I am just missing something but if not, it would be nice to allow for more customized setups to function properly. Better yet, if WordPress runs as expected with a setup, why couldn't wp-cli?

Thanks

**Comment by danielbachhuber** [comment]
> I assumed the extra-php would be loaded before the require files but that does not seem to be the case.

This is not the case. `--extra-php` is used when `wp core config` ([doc](http://wp-cli.org/commands/core/config/)) is run. It's not used every time `wp-config.php` is laoded.

> So I am puzzled as how to get this to work with my setup and I have too many sites running this way to change the system as there is nothing wrong with the setup. Just limited config for wp-cli.

Generally, it's better to use `dirname( __FILE__ )` and similar in your config files, instead of depending on `$_SERVER`, because `$_SERVER` isn't fully populated on the command line.

If you wanted to define `$_SERVER` at runtime just for WP-CLI, you could create a `cli-config.php` file:

```
<?php
$_SERVER['DOCUMENT_ROOT'] = '/var/www/wordpress.dev/public_html/';
$_SERVER['SERVER_NAME'] = 'www.wordpress.dev';
```

Then, in your `wp-cli.yml` or `~/.wp-cli/config.yml`, you'd require the `cli-config.php` file:

```
require:
  - cli-config.php
```

**Comment by jpSimkins** [comment]
I tried something similar to that too with no luck. 

It seems that the real problem here is that I cannot specify the wp-config.php file's location and it's trying to find it on it's own. I am going to test with using wordpress in a sub-directory and just let me devs use this setup only for unit testing.. Seems a bit redundant but it's important to get this to work for now. Hopefully a future update will allow for config specifications of:

wp-config.php
wordpress location
custom wp-content directory.

I cannot get past the wp-config issue so I am not aware if custom wp-content directories will cause issues yet.

**Comment by danielbachhuber** [comment]
> I tried something similar to that too with no luck.

Ok. It's hard to say what the problem might be then without access to greater detail on what you tried, how you tried it, and the result you saw. If you can provide more specific reproduction steps, I might be able to help further.

> It seems that the real problem here is that I cannot specify the wp-config.php file's location and it's trying to find it on it's own.

This is correct. WP-CLI, just like WordPress, supports a wp-config.php file in `ABSPATH` or one directory above `ABSPATH` (e.g. up one directory from WordPress core files).

If you want to include your configuration details elsewhere, you can have the wp-config.php file use `require()` to any other arbitrary file.

> My issue is that I have a wp-config.php file that is no the acutal wp-config as it's a global to set defaults and it includes the project specific wp-config using the `$_SERVER['DOCUMENT_ROOT']` and `$_SERVER['SERVER_NAME']` variables. 

Again, PHP CLI doesn't populate `DOCUMENT_ROOT` because the value is based on the web request. You'll need to find an alternative to `$_SERVER['DOCUMENT_ROOT']` in the WP-CLI context. See #785
