### ISSUE TITLE
DB Export - find and replace site URL in serialized data

### ISSUE THREAD

**Issue by designforhumans** [wp-cli/wp-cli#3006]
The db export feature is quite useful, but when moving wordpress from one domain to another, one needs to search the db for instances of the site url and replace it with the new site URL. This is a complex and time consuming task. Furthermore, many plugins and themes, store the site URL within serialized data. Thus, doing a simple find and replace breaks the serialized string, as serialized data stores both the representation of the text and metadata about the size of the string in bytes. 

A popular tool has been created to deal with this problem here: https://interconnectit.com/products/search-and-replace-for-wordpress-databases/

An awesome feature for WP-CLI would be to extend the **wp db export** command to export a version of the database with a find and replace (including within serialized data) this would save many people many headaches. 

WP-CLI is a great tool. Many thanks to all who contribute.

**Comment by danielbachhuber** [comment]
> An awesome feature for WP-CLI would be to extend the wp db export command to export a version of the database with a find and replace (including within serialized data) this would save many people many headaches.

Use `wp search-replace --export=<filename>`, [introduced in v0.22.0](http://wp-cli.org/blog/version-0.22.0.html#search-replace-for-love-and-profit), to create a SQL export with replaced strings.

**Comment by ilearnio** [comment]
This `search-replace` is useless. For me it replaced 4 site URLs only, all were in `wp_options` and `wp_2_options` tables. It skipped the serialized strings alltogether (please introduce JSON already instead of serialize for god's sake!)

I used this command:

```
wp search-replace 'olddomain.com' 'newdomain.com' --all-tables-with-prefix='wp_2_' --precise --verbose --report-changed-only --export=replaced.sql
```

![image](https://user-images.githubusercontent.com/14331216/152520477-7dec3444-fea6-4ac1-86a8-d64024702b05.png)

**Comment by jessuppi** [comment]
@ilearnio 

I was having similar problems with WP-CLI but I discovered it was because:

1. the strings in the database were different than I thought
2. the strings in the database were in different tables than I thought

For example, I had a client using WP Bakery page builder plugin and when editing pages, I saw absolute URLs in the code such as `https://staging.example.com` and tried to search/replaced with WP-CLI with no luck...

After I dropped the `https://` from my strings, WP-CLI found more instances to replace in other MySQL tables, and that's what ended up fixing the broken links on the site.

I don't understand all the reasons behind it (each theme/plugin might be different) but you can follow here:

Ref: https://wordpress.stackexchange.com/questions/408756/best-way-to-search-and-replace-within-serialized-database-strings
