### ISSUE TITLE
wp-cli should obey http_proxy & https_proxy env variables

### ISSUE THREAD

**Issue by c33s** [wp-cli/wp-cli#3019]
tools like wget read the proxy settings from the environment variables `http_proxy` & `https_proxy`

it is possible to set it via:
```
$stream_default_opts = array(
  'http'=>array(
    'proxy'=>"tcp://proxy.example.com:1080",
    'request_fulluri' => true,
  )
);

stream_context_set_default($stream_default_opts);
```
http://john.cuppi.net/proxy-outgoing-connections-via-php/

or via the curl
```
curl_setopt($ch, CURLOPT_PROXY, $proxy);
```

maybe have a look at composer, it supports proxies: https://github.com/composer/composer/search?utf8=%E2%9C%93&q=proxy

**Comment by danielbachhuber** [comment]
Sorry, what's this in reference to?

**Comment by c33s** [comment]
if i try to run ` wp core download` it connects directly not using the exported proxy. so it runs in a timeout because of the lan setting only allowing to connect to the net trough the proxy. 
so reading the proxy settings from the env variables and connection through that proxy would be awesome, because then it could be used in proxied & firewalled environments.

**Comment by danielbachhuber** [comment]
> if i try to run wp core download it connects directly not using the exported proxy.

`wp core download` uses the [Requests](https://github.com/rmccue/Requests) library to make remote requests. I'd suggest opening a ticket with that project to discuss supporting the environment variables.

**Comment by rkok** [comment]
Can you please support http proxying, at least as a command-line argument? It's quite common for corporate build servers to require a proxy for outgoing traffic; this is the situation I'm in currently, and I reckon a lot of other developers, too.

I think the Requests library is not a good place to put this functionality; it would give the library side-effects.

**Comment by c33s** [comment]
@rkok i think the prefect place for supporting this functinality would be the requests libary but often people act in the "i don't use/need it, so you don't need it too" matter. often this people haven't been confronted with such environments where proxies are used.

i hoped that @danielbachhuber will help me in the issue i opened at the requests lib, but he also don't need it. https://github.com/rmccue/Requests/issues/218#issuecomment-234360678

with wordpress and its surrounding tools you leave the enterprise compatible world, where LTS, SemVer and standards like `HTTP_PROXY` are followed. one of the reasons i stay with symfony and tools build with this framework.

you can try the following workaround (not tested with this tool):

php.ini
```
auto_prepend_file = "proxy.php"
```

proxy.php
```
<?php

$stream_default_opts = array(
  'http'=>array(
    'proxy'=>"tcp://proxy.example.com:1080",
    'request_fulluri' => true,
  )
);

stream_context_set_default($stream_default_opts);
```

with the `auto_prepend_file` the file listed there is automatically prepended to all your php files (don't know if this also works for phars). in the file you can set the stream defaults, so all for example  `file_get_contents` calls will be called with this default options. not sure if you need to provide the `$context` manually (which will break this workaround).

**Comment by rmccue** [comment]
My policy for Requests was (and remains) that it's the responsibility of the library user to connect the library to the system, whether that's environment variables or anything else. Having the library change behaviour underneath you makes your code unpredictable, which is why Requests has almost no global configuration. (The transport is global configuration, but this should be invisible to the library user.)

That said, I think it makes sense for wp-cli to use the environment variable if it's available.

**Comment by schlessera** [comment]
I also don't like just blindly trusting the `HTTP_PROXY` environment variable with WP-CLI, especially now that everyone just assumes it doesn't based on the prior lack of support.

However, I think something like the following would solve the problem, and not cause a surprising change in behavior on existing installations:

1. Provide support for a way to set a proxy through `wp-cli.yml` configuration files.
2. Accept the value `HTTP_PROXY` as such a config-based proxy, which would tell WP-CLI to fall back to the environment variable.

This way, you can set WP-CLI up to honor the `HTTP_PROXY` environment variable if you so want, but you need to explicitly enable this because it opens up a new attack vector on your server.

@c33s I assume this would solve your specific use case?

**Comment by brandonpittman** [comment]
I need some kind of way to set this globally. I'm tired of setting the proxy every time after setup.

**Comment by devnewton** [comment]
Could you please post your config.yml ? I cannot get wp-cli working behind corporate proxy.

**Comment by brandonpittman** [comment]
@devnewton I will when I get back on Monday.

**Comment by rkok** [comment]
It turns out that this error message on `wp core download`:

    Failed to get url 'https://api.wordpress.org/core/version-check/1.6/?locale=en_US':
    stream_socket_client(): unable to connect to ssl://api.wordpress.org:443 (Operation timed out).

can be circumvented easily by installing the PHP curl extension, which appears to honour `http_proxy`/`https_proxy`.

That solved the problem I was having.

**Comment by swissspidy** [comment]
For enabling the HTTP proxy configuration support in WP-CLI, @ekamran has kindly built and shared https://github.com/ekamran/wp-cli-http-proxy-command today. If you're interested, I recommend giving it a try and providing feedback.
