### ISSUE TITLE
Incorrect XML file generated from export command

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#3045]
Command:
`wp export --category=sample-category`
Expected output is XML file containing posts under that category. But all posts and taxonomies are there in the generated XML file.

WP: 4.6-alpha-37753

PHP binary: /usr/bin/php5
PHP version:    5.5.9-1ubuntu4.17
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:    /home/nilambar/personal/gitarea/wp-cli
WP-CLI packages dir:    /home/nilambar/.wp-cli/packages/
WP-CLI global config:   
WP-CLI project config:  
WP-CLI version: 0.24.0-alpha

**Comment by ernilambar** [comment]
Above command worked when used like this.
`wp export --category=sample-category --post_type=post`
Does `--post_type` always need to be there?

**Comment by danielbachhuber** [comment]
> Does --post_type always need to be there?

Appears to be:

https://github.com/wp-cli/wp-cli/blob/master/php/export/class-wp-export-query.php#L75-L104

I'm not sure what the expected behavior is meant to be. Given we're using an already slightly-forked version of https://core.trac.wordpress.org/ticket/22435, this isn't something I want to fix in the exporter.
