### ISSUE TITLE
Permission denied error when CLI update

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#3126]
I installed following steps given in the [Installing](https://wp-cli.org/#installing) section. When there is update available for CLI and I run `wp cli update`, I get `Permisson denied` error in `/usr/local/bin/wp`. Unfortunately, I am still not able to fix that, and I update CLI following steps for Installing. Anybody facing issue similar to this? May be this could be one configuration problem.

**Comment by nyordanov** [comment]
Check the write permissions of `/usr/local/bin/wp`. If you've moved the file there with `sudo mv wp-cli.phar /usr/local/bin/wp` you may need to update it with `sudo` as well:

`sudo wp cli update --allow-root`

Personally, I keep the `wp` Phar in `~/bin/wp`, which I've previously added to my PATH.

**Comment by ernilambar** [comment]
I guess it is not good practice to use `sudo` with `wp` command. That is explained in the command output also.

**Comment by danielbachhuber** [comment]
> Is anyone else also facing this issue?

It's a permissions issue. Your current system user doesn't have permission to modify the file, because you used `sudo` to move it in place. You'll need to fix the permissions on the file such that your current system user can modify the file, or run `sudo wp cli update --allow-root` to perform the update operation as sudo.
