### ISSUE TITLE
Echo specific @alias when using @all alias for commands 

### ISSUE THREAD

**Issue by arijuki** [wp-cli/wp-cli#3192]
When using @all alias, command will executed in the order as aliases are listed in config. Actual @alias name is not echoed, so in case of issue (or otherwise) it is not immediatey visible which @alias is in question.
Possible solution: add new flag to echo @alias name.

**Comment by danielbachhuber** [comment]
Just so it's written somewhere, I didn't print the alias being executed as a part of the initial implementation because it would potentially break `--format=csv` et al.

> Possible solution: add new flag to echo @alias name.

While I'm not sure what the solution is, I don't think adding a new flag is the way to go here, because I don't think it merits adding an option / making the user think.

**Comment by danielbachhuber** [comment]
> Just so it's written somewhere, I didn't print the alias being executed as a part of the initial implementation because it would potentially break `--format=csv` et al.

After thinking on this, I realized any of the `--format=<format>` arguments would need to potentially be parsed in a custom manner because the format is no longer valid if it's multiple instances rendered on top of one another.

I've decided to `WP_CLI::log()` the current alias when executing an alias group (including `@all`). This behavior can be disabled with `--quiet`.
