### ISSUE TITLE
@alias unknown parameter --url error

### ISSUE THREAD

**Issue by lkraav** [wp-cli/wp-cli#3444]
Today's `master` is 30e46f9

```
$ [-] wp cli info
PHP binary:     /usr/lib64/php7.0/bin/php
PHP version:    7.0.10-pl0-gentoo
php.ini used:   /etc/php/cli-php7.0/php.ini
WP-CLI root dir:        /home/leho/wp-cli
WP-CLI packages dir:
WP-CLI global config:   /home/leho/.wp-cli/config.yml
WP-CLI project config:  /home/wordpress/wp-cli.yml
WP-CLI version: 0.25.0-alpha
```
(PS version info could append commit hash marker)

Multi-site.

wp-cli.yml
```
color: auto
core config:
    dbhost: database
path: /home/wordpress
url: mysite.com

@subsite:
    url: subsite.mysite.com
```

then we get an error

```
$ wp @subsite option get siteurl
Error: Parameter errors:
 unknown --url parameter
```

Is this a bug, or a configuration error? I think my configuration makes sense from a human perspective. If no `--url` explicitly provided, it needs to default to something, or I get `PHP Notice:  Undefined index: SERVER_NAME in /home/leho/wp-cli/php/WP_CLI/Runner.php(953) : eval()'d code on line 13`

**Comment by danielbachhuber** [comment]
> Is this a bug, or a configuration error? I think my configuration makes sense from a human perspective.

I think it's a configuration error. You're missing a trailing colon on the alias:

```
@subsite
    url: subsite.mysite.com
```

**Comment by lkraav** [comment]
Unfortunately that was just a github-retyping error. I checked and `wp-cli.yml` was correctly formatted.

**Comment by danielbachhuber** [comment]
Ok. I was able to reproduce this with #3450

What's happening is that the top-level `url` value is still being passed through to the command as a local argument to the command.

If we were to change the current behavior, I'd have WP-CLI ignore any use of url, user, path, http, or ssh in a general config when an alias is being used. However, this isn't easily possible at this point because the config parsing happens at a different point than alias registration.

**Comment by danielbachhuber** [comment]
> However, this isn't easily possible at this point because the config parsing happens at a different point than alias registration.

Actually, it turned out to be easier than I expected.
