### ISSUE TITLE
Intermittent build failures on Travis

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3652]
Houston, we have a problem.

Travis has a build time limit of 50 minutes. WP-CLI, because of its comprehensive test coverage, is now occasionally exceeding the time limit, which causes the build to fail. This is annoying. If we keep things the way they are, the problem is only going to get worse.

Some ideas:

1. Speed up the test suite... but how?!?!?!
2. Split components into logical subpackages (e.g. `wp-cli/search-replace-command`), and require them via Composer.
3. ???

Obviously, 2 seems to be our only way out of this mess. I _think_ this can be done without backwards compatibility concerns. It's a not-insignificant amount of work though. We also lose out on the test suite running against all commands, although they should be atomic enough that it's not a problem.

Happy to consider other suggestions!

**Comment by danielbachhuber** [comment]
An idea from @Rarst: Run the test suite in different groups. This would decrease the execution time for each job, but lead to a greater total build time.

Previously https://github.com/wp-cli/wp-cli/issues/1992

**Comment by szepeviktor** [comment]
Do we have information (runcommand/profiler) on what is actually taking so long?

- network
- disk, file copying
- php execution
- database

**Comment by danielbachhuber** [comment]
> Do we have information (runcommand/profiler) on what is actually taking so long?

Not detailed, but the cost is WordPress loading each time. Loading WordPress takes some amount of time. Every time we add a new test, we incur the cost of loading WordPress.

**Comment by szepeviktor** [comment]
Could we try
```
opcache.enable=1
opcache.enable_cli=1
opcache.file_cache="/ramdisk/php-file-cache"
opcache.file_cache_only=1
opcache.file_cache_consistency_checks=1
```
providing there is a ramdisk (tmpfs) on Travis?

**Comment by danielbachhuber** [comment]
What sort of performance increase do you think this will yield?

**Comment by szepeviktor** [comment]
~7×

**Comment by danielbachhuber** [comment]
Travis CI increased our limit to 70 min, so we should be good to go for the near to medium term.

Longer term, I'm still excited by the idea of breaking commands into separate repos for easier maintainability.

**Comment by szepeviktor** [comment]
>  1 hr 9 min 58 sec

See https://travis-ci.org/wp-cli/wp-cli/builds/184062283
and the new lightspeed thing https://travis-ci.org/wp-cli/wp-cli/builds/184099215

**Comment by chriscct7** [comment]
If you haven't already I would reach out to Travis's dev team. I remember when TravisCI didn't have so many boxes a couple years ago and EDD's constant pushing would literally hold up every other travis job from all other organizations for **a lot** of time [1], and when talking with them they actually were happy we were at their limits because it and worked with us to reduce the time to execute [2]. 

Might be different now they're larger, but @joshk from TravisCI was always really approachable and helped us quite a lot. Not sure who is his equivalent (or maybe he's still the go-to guy for this) there atm.

[1] "you have 2k jobs in the queue, with each build taking about 2+ hours to completed due to the 72 job matrix" :stuck_out_tongue:
[2] "but tbh we love you putting Travis through its paces. So please don't worry about trying out fun and crazy things with it."

**Comment by joshk** [comment]
Hello

What's the goss? How can I help?

**Comment by danielbachhuber** [comment]
@joshk No worries — increasing the build timeout solved our more immediate problem.

**Comment by joshk** [comment]
Huzzah!

**Comment by danielbachhuber** [comment]
> increasing the build timeout solved our more immediate problem.

This is solution enough for now. Splitting commands out isn't actionable right now — [added to the wish list](http://wp-cli.org/docs/wish-list/).
