### ISSUE TITLE
`wp media import` should return a non-zero exit code upon error when run in conjunction with the `--porcelain` flag

### ISSUE THREAD

**Issue by balbuf** [wp-cli/wp-cli#3721]
Ran into some trouble because I was expecting this command would return a non-zero exit code if the image could not be successfully uploaded, but it doesn't (only with the `--porcelain` flag). I'd be happy to open a PR but I wanted to ask first what would be the preferred way to handle it:

1. When an error is first hit (https://github.com/wp-cli/wp-cli/blob/master/php/commands/media.php#L240), if the `--porcelain` flag is set, we could exit immediately. `--porcelain` sort of implies you are only importing one image, because you'd only ever get the ID of the last image processed (right?), but you could still theoretically be importing multiple images. So, it could also check `count( $args ) === 1` to exit there.
2. Otherwise, instead of blindly logging the value of `$success` on [#L266](https://github.com/wp-cli/wp-cli/blob/master/php/commands/media.php#L266), we could check the count of `$errors` or check whether `$sucess` is a WP error object (though if there are multiple images, this doesn't indicate if any images before the last one had an error).

In either case, I'm not sure whether you'd want to exit with a message via `WP_CLI::error()` or just send a non-zero code along with whatever is already being sent. So anyway if you want to give me a bit of direction I can submit a PR. Thanks!

**Comment by danielbachhuber** [comment]
Thanks for the report, @balbuf !

Here's some prior art you can study when working on your pull request: #3577

At a high level:

* All specified images should be processed, even if one errors.
* If any image processing errors, then exit code should be `1`.
* If `--porcelain` is provided, then you should use `WP_CLI::halt( 1 );` instead of `WP_CLI::error()`.

Please make sure to include Behat test coverage for your changes :)

**Comment by danielbachhuber** [comment]
🚢
