### ISSUE TITLE
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found

### ISSUE THREAD

**Issue by miya0001** [wp-cli/wp-cli#3802]
[PHPUnit 6](https://github.com/sebastianbergmann/phpunit/blob/6.0/ChangeLog-6.0.md#600---2017-02-03) doesn't support `PHPUnit_Framework_TestCase` as the base class.
And Homebrew version is 6.

So, I got an error like following.

```
$ /usr/local/bin/phpunit 
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /private/tmp/wordpress-tests-lib/includes/testcase.php on line 15
```

Should we add `composer.json` when running `wp scaffold plugin`, etc?

**Comment by danielbachhuber** [comment]
> Should we add `composer.json` when running `wp scaffold plugin`, etc?

I've refrained from generating a `composer.json` when running `wp scaffold plugin-tests` because:

1. `wp scaffold plugin-tests` is always run against an existing plugin.
2. An existing plugin can already have a `composer.json` file.
3. For `wp scaffold plugin-tests` to add a `require: phpunit/phpunit` statement, it would need to either create a new `composer.json` or modify an existing `composer.json`

I solved this dependency problem in #3472 by requiring `phpcs` globally in `.travis.yml`, instead of adding to a `composer.json`

For this particular issue, I think the problem to solve would be adding PHPUnit 6 support to WordPress core. Want to create a Trac ticket for it?

**Comment by miya0001** [comment]
> For this particular issue, I think the problem to solve would be adding PHPUnit 6 support to WordPress core. Want to create a Trac ticket for it?

OK, I try it. Thanks. :)

**Comment by miya0001** [comment]
Done, but I am not sure that my solution is ok ... 😓 
https://core.trac.wordpress.org/ticket/39822

**Comment by Failcookie** [comment]
Any tips on how to deal with this issue in the short term?

**Comment by holisticnetworking** [comment]
+1 for this. Dead in the water trying to unit test my favourite framework.

**Comment by bobbravo2** [comment]
@holisticnetworking @Failcookie  In composer.json, specify the PHPUnit 5.7.x branch

**Comment by cyberscribe** [comment]
+1

**Comment by GaryJones** [comment]
39822 is now fixed in WP core.
