### ISSUE TITLE
Add PHP 7.1 to the .travis.yml testing matrix

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#3810]
PHP 7.1 is now stable and should probably be added as well, as the jump from 7.0 to 7.1 contains some breaking changes.

Here's a list of the backward-incompatible changes from 7.0 to 7.1: http://php.net/manual/en/migration71.incompatible.php

**Comment by danielbachhuber** [comment]
👍 

Couple of things worth noting:

* We need to somehow, sustainably keep the Travis matrix in sync between the main project and all of the individual repositories to ensure every command is tested against the same standards. Not necessarily something we need to immediately solve though, just keep it in mind.
* I think I'm going to start on #3728 very soon, because the total build time is very annoying to me.

**Comment by danielbachhuber** [comment]
@schlessera Looks like 7.1 was added in 4e285d7a758a1745da5b43af5e2f55de8a2c4087. Can you clarify your original issue?

**Comment by schlessera** [comment]
Ah, the issue was not very clear, sorry. I was referring to #3784 which originally only included PHP 7.0, but not PHP 7.1
