### ISSUE TITLE
Abstract Behat test suite to a dedicated repo

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3826]
To make it easier to reuse our test suite across packages, we should abstract it to a dedicated repo, and then require it using Composer.

Previously https://github.com/wp-cli/scaffold-package-command/issues/13#issuecomment-201272695

**Comment by danielbachhuber** [comment]
As an artifact of https://github.com/wp-cli/scaffold-package-command/pull/89, this issue is no longer necessary.

We should evaluate whether this is still a pragmatic change.

**Comment by schlessera** [comment]
Whether it is "pragmatic" is difficult to say, it mostly depends on what the effort would be.

Having a separate Composer package for the test suite would keep the other repos cleaner. Otherwise, every change to the test suite will need commits across all other repositories.

I'd suggest focussing on #3850 first, and then use an hour or two to discover the exact amount of work this would need.

I still think it would be worthwhile to do in terms of code quality and maintenance, but I'm not yet sure how easy it is to pull off.

**Comment by danielbachhuber** [comment]
Closing as `maybelater` for now:

1. `wp scaffold package-tests` seems to be working just fine for our needs.
2. While this abstraction _could_ solve the problem of duplicated files, it could also introduce other issues/complexity we have to manage.
