### ISSUE TITLE
Scaffold more default .yml Config Files

### ISSUE THREAD

**Issue by bhubbard** [wp-cli/wp-cli#3866]
So also when using Scaffold, I would like to see the option to add default `.yml` files for common services being used:

* https://docs.codeclimate.com/docs/getting-started-configuration
* https://houndci.com/configuration
* https://scrutinizer-ci.com/docs/configuration
* https://documentation.codeship.com/pro/getting-started/services/
* etc

Each of these may be separate for plugin vs theme.

**Comment by szepeviktor** [comment]
Hello @balbuf !

WP-CLI is pluggable! You may hook here https://github.com/wp-cli/wp-cli/blob/84e55468fc5ed0de5b827f60639c358fd59b990c/php/WP_CLI/Dispatcher/Subcommand.php#L395
and create any file you need.
At this point we have only https://github.com/wp-cli/wp-cli/blob/master/templates/plugin-travis.mustache

**Comment by danielbachhuber** [comment]
> I would like to see the option to add default .yml files for common services being used:

I'm amenable to including services that run the PHPUnit test suite, because that's the genesis of our scaffolding command.

I don't think it makes sense to support _every_ continuous integration service, because it's a huge amount of effort to maintain over the long term, and departs from the original reason for `wp scaffold plugin-tests`.

**Comment by danielbachhuber** [comment]
I'm open to adding these as users have pull requests for them.
