### ISSUE TITLE
WP-CLI 2.0.0

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3909]
WP-CLI 2.0.0 is currently scheduled for late 2017. After release, WP-CLI 1.x will be maintained for critical bug fixes through 2018.

A working list of the breaking changes in 2.0.0 include:

* [ ] Bump minimum PHP version to 5.5.9
* [ ] Update to Symfony 3.x or later
* [ ] Update to Behat 3.x or later

Feedback welcome! Specifically, what other breaking changes should we consider and why?

**Comment by aaemnnosttv** [comment]
Any reason not to bump PHP to 5.6? 5.5 has been end of life for 8 months already and 5.6 is at least supported until 2019. http://php.net/supported-versions.php

**Comment by danielbachhuber** [comment]
> Any reason not to bump PHP to 5.6?

Not opposed. I think we need https://github.com/wp-cli/wp-cli/issues/3886 before making a final decision.

**Comment by rklrkl** [comment]
When people quote PHP versions, they often only refer to the php.net versions and their support periods, but long term Linux distros engage in backporting and typically have much longer support periods for a particular PHP version they've baselined on. And it's long term distros that hosters often run, so it's worth noting what their baseline PHP versions are (they backport fixes from later versions, but don't add new features from them).

RHEL/CentOS 6 ends support in Nov 2020 and ships PHP 5.3.3, whereas RHEL/CentOS 7 ends support in June 2024 and ships PHP 5.4.16. Now you can upgrade PHP fairly easily using the IUS repo at https://ius.io/ and I've done that successfully with CentOS 7 (now running the latest 5.6.X release and, yes, you can even pick a PHP 7.X version), but if you've already got a lot of sites running on, say, 5.3.3, this can cause breakage due to language changes between 5.3.X and 5.6.X.

It would be great if the WP-CLI 1.X series could be kept alive for as along as possible with no new features at all and just fixes for security issues and, of course, making sure it still works with the latest WordPress release. If that's the case, then I'm all for WP-CLI 2.X baselining its minimum PHP above even what CentOS 7 ships. I always manually update WP-CLI anyway and would just stay on the 1.X versions for "older" PHP installs.

**Comment by szepeviktor** [comment]
I remain an 1.x use till you brave guys report and fix all off the errors. Maybe I try 2.1.

@rklrkl Please consider modern PHP. As of modern: even 5.6 is hardly modern. I think refactoring a 5.4 project is a relatively small task.

**Comment by danielbachhuber** [comment]
At this point, we're only planning to increase minimum supported PHP to 5.4. Handling in #4554
