### ISSUE TITLE
Create stub files for autocompletion

### ISSUE THREAD

**Issue by rmccue** [wp-cli/wp-cli#4023]
Hello beautiful CLI folks.

Right now, wp-cli essentially has two parts: the system binary, and the internal PHP API. These two are obviously part of the same codebase, but are used in drastically different contexts. The binary is used on servers (including local development servers), whereas the internal PHP API is used by developers in their editors. This leads to a bit of a disconnect, as if you're writing PHP locally for wp-cli, you might not actually have a copy of it (it might be hidden inside a VM, e.g.).

The main problem here is with editors and IDEs that have autocompletion, as they may have no ability to find wp-cli's internal PHP API. This can lead to warnings about missing classes, or just a lack of information about what parameters to pass in. For people writing wp-cli commands, wp-cli essentially functions the same way as a PHP extension, and it would be great to use the same system of documentation as extensions have.

To fix this, I'd like to propose creating stub PHP files. These would include the [public internal API](https://make.wordpress.org/cli/handbook/internal-api/) classes and functions with all their inline documentation, but without the actual code.

As an example of what PHP stubs look like, the [phpstorm-stubs repo](https://github.com/JetBrains/phpstorm-stubs/blob/master/Core/Core.php) contains all the stubs for PHP and its extensions.

This should be automatable using the existing automated PHP docs system used by the handbook.

**Comment by schlessera** [comment]
I understand the problem, but I'm not sure the solution would be a fitting one.

These stubs are provided in the way they are because the functions they reference are not actual PHP code, but rather C code in an extension. That's why you can't just load the corresponding PHP file as an alternative.

Why not just add `wp-cli/wp-cli` as a development dependency through Composer? An IDE like PHPStorm will be able to properly load that in and autocompletion just works. This does not need any additional stub files we would need to maintain separately from the regular code base, and it is the default mechanism with which PHP -> PHP relations are now handled.

Do you have a use case where pulling in the actual PHP code through Composer (as a dev dependency) would not work?

**Comment by rmccue** [comment]
From the user's perspective, wp-cli is more like part of the system, not part of the project. We don't need the source for wp-cli included in the project. There's no specific use case where we couldn't just use the source (via Composer or otherwise), apart from most of the source being unnecessary.

(In our specific case, we're also not using Composer, so we can't just add it in to an existing system.)

I do recognise this is a weird request though, so feel free to close it out.

**Comment by danielbachhuber** [comment]
@rmccue Out of curiosity, which internal functions do you find yourself using most often?

**Comment by danielbachhuber** [comment]
At this point, we're going to invest our energy into improving https://make.wordpress.org/cli/handbook/internal-api/

Thanks for the idea though!
