### ISSUE TITLE
Behat hangs on clean-up

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4038]
(Issue brought over from https://github.com/wp-cli/wp-cli/pull/3872#issuecomment-298610113)

`Composer stack with override requirement before WP-CLI` test in `feature/bootstrap.feature` is currently marked as `@broken`.

Expected behavior is that the override command should be active instead of the original command.

The test shows that this is the case, but then the clean-up mysteriously fails and blocks Behat. I suspect this is due to the way the branch is pulled in. This will need further examination, but does not directly have anything to do with the behavior that is being tested.

**Comment by schlessera** [comment]
Maybe related: https://github.com/wp-cli/package-command/commit/47fedd9c04e6b8ee73fa49b86655fa574cb1b018

**Comment by schlessera** [comment]
The problem seems to simply be that the `rm -r` command asks for confirmation for each single folder and file, probably because of a slight difference in permissions.

Adding an `-f` argument solves the issue, but I feel nervous about this. I'll add a small check to make sure we're only ever deleting stuff from the temp dir.

**Comment by gitlost** [comment]
It seems to be in eg "features/bootstrap.feature:23" on a composer install, the ".git/objects/pack/*" files are readonly so causing `rm` to ask "remove write-protected regular empty file?"

It would be cleaner and nicer I think to do the remove in PHP rather than shelling out, eg Symfony\Filesystem (which just so happens to be available!) has a recursive `remove`. I tried this out in https://github.com/gitlost/wp-cli/pull/7 and it works well.
