### ISSUE TITLE
Wordwrapping breaks formatting of command list

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4127]
![image](https://cloud.githubusercontent.com/assets/36432/26735060/376bf896-4775-11e7-9c0d-fb5159bef318.png)

Related https://github.com/wp-cli/scaffold-package-command/issues/112

**Comment by danielbachhuber** [comment]
@gitlost Any good ideas for this?

**Comment by gitlost** [comment]
Well for 1.2.1 an idea obviously would be to default `WP_CLI_HELP_WORDWRAP_WIDTH` to 90 which was (sort of) what it was before. As for good ideas...those if any may have to be awaited...

**Comment by danielbachhuber** [comment]
> Well for 1.2.1 an idea obviously would be to default `WP_CLI_HELP_WORDWRAP_WIDTH` to 90 which was (sort of) what it was before.

Hm. I suppose this would be fine, as long as it fixed all of the current problem descriptions we currently have.

**Comment by gitlost** [comment]
Hm indeed. I found a number of issues with my previous "fix" https://github.com/wp-cli/wp-cli/pull/4105. One was not understanding `wordwrap()` - can't use the `break` parameter with anything but `\n` really without doing gymnastics. Also need to de-tab before using it. Also need to wordwrap the command list separately in order to preserve its columns.

See https://github.com/gitlost/wp-cli/pull/8 for fixes for these, which also dispenses with the arbitrary `WP_CLI_HELP_WORDWRAP_WIDTH` - which never made sense really - to use the very nice existing function `\cli\Shell::columns()` to wrap to the actual terminal width.

A small issue with `\cli\Shell::columns()` is that it's not test friendly - the `tput` command it uses will throw a error if not run interactively, so https://github.com/gitlost/wp-cli/pull/8 needs also the one-line change https://github.com/gitlost/php-cli-tools/pull/1 to suppress it - I had to temporarily point composer to this in order to get the tests to pass.

Extra, more precise tests have been added, and one test changed to wrap to 40 instead of 30 in order to avoid the unwrappable `--ssh=[<user>@]<host>[:<port>][<path>]` pushing out the max line length.

**Comment by gitlost** [comment]
Tested on a Windows 10 virtual box and ended up changing `cli\Shell::columns()` a fair bit to get good results on the various bash-like shells available. Also ran into the `/usr/bin/env` issue https://github.com/wp-cli/wp-cli/issues/4120.
