### ISSUE TITLE
Failed to import yst_prominent_words

### ISSUE THREAD

**Issue by hzektser** [wp-cli/wp-cli#4239]
Ran an export from a site, and now running an import to a new site. Its failing on all posts with the error `Failed to import yst_prominent_words`. Presumably this is tied to the Yoast SEO plugin, but even with that installed, it is failing.

**Comment by schlessera** [comment]
Hi @hzektser,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support

**Comment by hzektser** [comment]
@schlessera I'm not clear why this isn't a bug? It seems pretty clear-cut that it is.. Take a default install, run `wp export` and add this to the xml before re-importing;
```
<wp:term>
<wp:term_id>3981</wp:term_id>
<wp:term_taxonomy>yst_prominent_words</wp:term_taxonomy>
<wp:term_slug>steve</wp:term_slug>
<wp:term_parent/>
<wp:term_name>
<![CDATA[ ? by @steve ]]>
</wp:term_name>
</wp:term>
```

Even if this is an unsupported element for import, at the very least it should be ignorable. Just failing seems like incorrect behavior.

**Comment by schlessera** [comment]
@hzektser The import fails because the taxonomy you want to add data to does not exist, as it is only registered for premium installs of Yoast SEO. The solution would be to make sure the required plugin is installed. Otherwise, if WP-CLI would add this data without the taxonomy being registered, it would create orphaned elements in the database that take up space without being referenced.

How would you expect WP-CLI to handle this? Do you think there should be an option to force importing "faulty" data?

Right now, the above result is the currently expected behavior, which is why I don't consider it a bug. I'm open to investigating a different approach and maybe changing the expected behavior if it makes sense, though, so feel free to open an enhancement proposal in https://github.com/wp-cli/ideas/issues .

**Comment by hzektser** [comment]
@schlessera my miss -- didn't realize I had to activate Yoast! My bad, you are absolutely right!

**Comment by iamkingsleyf** [comment]
I am having the same problem, i have installed YOAST but seems not to work
