### ISSUE TITLE
Sort (or allowing sorting of) meta and option lists

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#4242]
Commands such as `wp option list` and `wp user meta list` (among others) return their data in the order in which they are stored in the database, which typically means by their primary key in ascending order.

It would be more user-friendly if this data were ordered according to their key fields (`option_name`, `meta_key`), either by default or via a flag to control sorting.

**Comment by schlessera** [comment]
@johnbillion You can already sort some lists by an arbitrary field. For example, the optional `--<field>=<value>` parameter for `wp post list` allows you to add arbitrary `WP_Query` arguments to the query. As an example, to sort the list of posts by title in ascending order, you'd do:
```
wp post list --orderby=post_title --order=ASC
```

This is not implemented for all lists, and I think the two examples you've provided are amongst the ones that don't support that yet. I'd suggest adding this generalized `--<field>=<value>` to these as well, so that people can add arbitrary `WP_Query` filters to them.

Does that make sense?

**Comment by danielbachhuber** [comment]
> I'd suggest adding this generalized `--<field>=<value>` to these as well, so that people can add arbitrary `WP_Query` filters to them.

Related: https://github.com/wp-cli/entity-command/issues/19 and https://github.com/wp-cli/entity-command/issues/16

For purposes of having more complete documentation, I think it'd be worthwhile to explicitly identify known query parameters, and then include `--<field>=<value>` as a fallback as necessary.

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/wp-cli/entity-command/issues/45
