### ISSUE TITLE
Clarify policy around merging "code churn" PRs.

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4427]
In #4401, @gitlost said:

> In general it can be taken as read that I'm opposed to all this sort of code fiddling, for what it's worth.

It'd be worthwhile for @wp-cli/committers to discuss this at depth, and update documentation once a decision has been made.

**Comment by danielbachhuber** [comment]
My thinking is:

1. If it's a small change (logically equivalent, easy to understand, and is covered by existing tests), then I think it's fine to merge.
2. If it's a small change to a code path with any sort of risk, then I'm generally against merging unless: 1) there's a proven need, and 2) it's covered by tests.
3. If it's a large set of changes (diff of ~100 lines or greater) in one pull request, then it needs to be broken into smaller, more understandable PRs.

I'm generally supportive of coding standard changes because, while each individual standard may be debatable, they bring consistency to the codebase. Greater consistency subtly makes the entire codebase easier to understand.

Furthermore, if we're afraid of making changes to the codebase, we should take that as a sign we should focus our efforts on increasing confidence about making changes (e.g. by adding more tests or otherwise). Every part of the codebase should be mutable, provided it still confirms to its explicitly defined APIs (e.g. no backwards compatibility breaks).

Of what I've said:

1. What do you agree with?
2. Where do you differ, and how would you change it?
3. How would you clarify further?

**Comment by gitlost** [comment]
The issue for me isn't churn as such, but fiddling, ie. making changes to code for no reason apart from "best practices" or "readability" or "consistency" or "insert subjective rationale here".

> 1. If it's a small change (logically equivalent, easy to understand, and is covered by existing tests), then I think it's fine to merge.

The problem with that is that there are an infinite amount of such improvements that could be made. I or anyone could rattle off about 10 PRs per minute that would match that criteria. The core mantra "Code refactoring should not be done just because we can" has a lot going for it.

Re 2.1, if a change has a proven need then that's not what I'm opposed to.

> I'm generally supportive of coding standard changes

My position is that if it's explicitly in [WordPress PHP Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/), then fine. If not, such as https://github.com/wp-cli/wp-cli/pull/4389, then not fine. The beauty of the WP document is that it's short, has few rules and is easy to follow, You just accept it and get on with your coding.

> Greater consistency subtly makes the entire codebase easier to understand.

Consistency of coding style is nice to look at. I'm not that sure it makes a codebase easier to understand, unless the existing style is particularly bad and all over the place.

> we should focus our efforts on increasing confidence about making changes (e.g. by adding more tests or otherwise)

Yes we should!

> How would you clarify further?

I'd go with a soft variant of [Code Refactoring - Make WordPress Core](https://make.wordpress.org/core/handbook/contribute/code-refactoring/) but that's just me.

**Comment by danielbachhuber** [comment]
Great articulation, @gitlost. Thanks for taking the time.

One other opinion I forgot to mention: if a new(er) contributor submits a coding standards/fiddling/whatever we call it type of change, I'd much rather accept the pull request and educate them about our policy than close the pull request. The soft aspect of contributor experience is as important as "correctness".

**Comment by GaryJones** [comment]
I'm not sure if this thread was also inviting others to contribute - probably not, but since my flurry of PRs seemed to trigger the discussion, I'll add my 2 pennies anyway:

As a new(er) contributor who doesn't know the internals of WP-CLI off by heart, but does know about code standards and documentation, and can run the (Php Inspections) inspector in PhpStorm to get a list of small improvements, then my ability to contribute is somewhat limited to that domain. 

Does a project like WP-CLI need contributions like that or not? Well, #4058 suggested it did, and the number of smaller code fixes that were possible to find and easily make PRs on (some would have been more in-depth changes, for only the same small benefit) in one sitting also indicates that there was room for improvement within the code.

> My position is that if it's explicitly in WordPress PHP Coding Standards, then fine.

That should also cover the [Inline PHP Docs](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/) in the Handbook as well, of which `WordPress-Docs` is a starting point. It's far less complete in terms of checks, compared to `WordPress-Core`, but it catches 660+ items on the current WP-CLI code base, so I'll be pushing for that here.

It's worth noting that the PHP Code Standards page in the handbook is not complete - it's full of holes, and doesn't even touch on how things like namespaces and `use` statements should be formatted.

One of the things we (the WPCS team) are trying to do, is get more of the `WordPress-Extra` checks moved over into `WordPress-Core`, so it wouldn't hurt any project related to WordPress, to start trying to adhere to that standard as well (it's what I'll also be encouraging here).

From my perspective, the WP-CLI core committers and main contributors can focus on the big features and bug fixes for end users, and let the likes of me help bring the quality of the project code up to speed to make your future lives easier. One doesn't have to pick one or the other.

**Comment by danielbachhuber** [comment]
> Does a project like WP-CLI need contributions like that or not? Well, #4058 suggested it did, and the number of smaller code fixes that were possible to find and easily make PRs on (some would have been more in-depth changes, for only the same small benefit) in one sitting also indicates that there was room for improvement within the code.

To offer a bit of perspective, it can be overwhelming for someone reviewing pull requests on a project to receive dozens of pull requests in a short period of time. For me personally, it took a better part of an hour for me to work through the pull requests I did.

Typically, we ask contributors to open an issue with their proposed change before submitting a pull request. This gives us the opportunity for some level of discussion before the contributor commits significant time to writing code. What's implied is always better explicitly stated.

> That should also cover the Inline PHP Docs in the Handbook as well, of which WordPress-Docs is a starting point. It's far less complete in terms of checks, compared to WordPress-Core, but it catches 660+ items on the current WP-CLI code base, so I'll be pushing for that here.

I don't think we'll be adopting these sniffs quite yet. This seems like a significant amount of work for debatable return. If you want to invest time in documentation, long-form would be a much higher value: https://github.com/wp-cli/handbook/issues

> From my perspective, the WP-CLI core committers and main contributors can focus on the big features and bug fixes for end users, and let the likes of me help bring the quality of the project code up to speed to make your future lives easier. One doesn't have to pick one or the other.

Ultimately, one has to pick a focus and choose how they spend their time. Our major focus right now is the [checksums project](https://make.wordpress.org/cli/2017/09/26/wordpress-plugin-and-theme-checksums-project-announcement/); time and attention we spend on other things takes away from this project.

Granted, there's a certain amount of ongoing work we can't ignore. Time is the currency we have to spend though, so it's important for us to spend it wisely.

**Comment by schlessera** [comment]
My personal opinion is that code standards and consistency in applying are very debatable in terms of how they improve readability or code comprehension or any other metric in that same vein.

However, where I find they provide huge productivity gains is when your code adheres to exactly 100% to them, and you can just switch on the systems in your IDE that take care of formatting and stuff automatically. One key stroke - done!

Whenever code is not 100% there, you not only need to do manual adjustments that take time, but you have to consciously think about the standards in place and the places they're not being followed, creating an additional mental hurdle.

With 100% standards adherence and automated application/enforcement, the entire topic just disappears, from your time tracker as well as from your mind. And in the end, it does not even matter much, what specific standard is being followed then - that's the point: you shouldn't need to care!

**Comment by schlessera** [comment]
I still like to add, though, that I also personally dislike the "avoid variable assignment in statements", because it changes the scoping of the variables involved. But I don't have any strong opinions about it. I just want us to get to the point where I can let my IDE deal with all these inconsequential details and concentrate on the actual problem at hand.
