### ISSUE TITLE
Increase minimum supported PHP version to 5.4

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4554]
Once v1.5.0 is released, we'll want to increase the minimum supported PHP version to 5.4 in:

* [x] Travis builds on main project.
* [x] Travis builds on packages.
* [x] Composer require.
* [x] Documentation.

[See announcement](https://make.wordpress.org/cli/2017/12/06/timing-for-v1-5-0-and-v2-0-0/).

**Comment by swissspidy** [comment]
The version requirement has come up today in https://github.com/wp-cli/makepot-command/pull/16. I agree with @schlessera that we might need to reinvestigate how to deal with this. Not only for the bump to 5.4, but also for future requirement changes.

For example, the i18n command might consist of multiple sub commands in the future, only one of which has a hard requirement for PHP 5.4 so far. This is being checked using the `before_invoke` argument. However, that one sub command also relies on a composer package which requires PHP 5.4 or higher.

Now, if you're on PHP 5.3 and still want to use all other i18n commands, you can't do that because of the composer dependency. Alain mentioned that installing WP-CLI over Composer would also break on PHP 5.3 in this case because of the version mismatch (assuming the i18n command is bundled with WP-CLI).

The only solution I can think of right now would be to use `--ignore-platform-reqs` for the build. This way, you can still use all of the PHP 5.3 commands while the 5.4 command does not work because of `before_invoke`. If it's a non-bundled package, users will need to use `--ignore-platform-reqs` as well when trying to manually install it (given that their also using PHP 5.3). I'm not familiar with the build / distribution process, so bear with me 🙂

In addition to that, the packages could also explicitly specify their minimum required PHP version (or even the WP-CLI version if needed. Using `*` is always tricky). in `composer.json` to make things more clear during installation.
