### ISSUE TITLE
--post_category="not working"

### ISSUE THREAD

**Issue by killown** [wp-cli/wp-cli#4605]
I am trying to set a post category in post creation with the following
 wp post create --post_type=post --post_title="asdf" --post_status=future --post_category="Teste" --post_content="asdf" --porcelain --allow-root --path=/var/www/html   everything works fine except for --post_category. 

Does wp-cli have this functionality to assign posts?

**Comment by schlessera** [comment]
@killown Can you try using the ID of the category to assign it? That should work.
According to the documentation, using name or slug should work as well, but it didn't for me with some quick tests.

**Comment by gitlost** [comment]
Yes for hierarchical taxonomies such as categories need to give ids due to this [wp-includes/post.php#L4131](https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L4131) check casting the array to ints.

So need to update the docblock, and check and give warnings (errors?) if given non-int category ids., for both `post create` and `post update`.

Thanks for raising the issue @killown !

**Comment by killown** [comment]
this worked after you tip: wp post term set 1000 category test --allow-root --path='/var/www/html' thanks a lot
