### ISSUE TITLE
Add dummy no-op WP_Object_Cache and use in long-running batch commands.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/wp-cli#4617]
From @schlessera https://github.com/wp-cli/media-command/pull/62#issuecomment-357873763

> I'd like to first investigate whether we cannot just replace the global variable $wp_object_cache that contains the current WP_Object_Cache instance with a sort of dummy cache object that just not stores anything for these commands.

`Utils\wp_clear_object_cache()` currently used in `wp import` and `wp export`.

`wp media regenerate` and `wp media import` are other candidates for dummy `WP_Object_Cache` use.

**Comment by gitlost** [comment]
@schlessera I forgot to discuss this in office hours. It's something I'd really like to happen for 1.5.0 but that seems unlikely now, so should be removed from the milestone?

**Comment by schlessera** [comment]
Implementation should be rather trivial, but testing is more problematic here, so I agree. Let's remove it from the milestone. We'll include it with either 1.5.1 or 2.0.0.

**Comment by danielbachhuber** [comment]
`Utils\wp_clear_object_cache()` is a tried and true solution to the problem. Creating a no-op `WP_Object_Cache` seems like it could cause further issues down the road.

For instance, the `alloptions` cache handles options lookups. If you disabled object cache for options, then pretty much every procedure would incur hundreds of database requests (because yes, options are referenced that often).

**Comment by danielbachhuber** [comment]
This will be addressed sufficiently with https://github.com/wp-cli/media-command/pull/62
