### ISSUE TITLE
A shortcut to combine wp core download and wp config create

### ISSUE THREAD

**Issue by benqzq** [wp-cli/wp-cli#4663]
I use the same arguments when using `wp core download` and `wp config create`:

```
wp core download --path=${drt}/${domain}/ --allow-root
wp config create --path=${drt}/${domain}/ --dbname=${domain} --dbuser=${domain} --dbpass=${dbuserp} --dbhost="localhost" --allow-root
```

I think it's worth creating some command shortcut that combines them, if there is no such simple way already.

An example could be:

    wp core download + config create --path=${drt}/${domain}/ --dbname=${domain} --dbuser=${domain} --dbpass=${dbuserp} --dbhost="localhost" --allow-root

**Comment by schlessera** [comment]
WP-CLI are meant to solve one single problem and then be composable, so that you can script solutions to whatever complex needs you have (see [Philosophy in the Handbook](https://make.wordpress.org/cli/handbook/philosophy/)).

You can easily use variables for the above use case. If you do this time and time again, create your own script that combines these (and other) commands behind a shortcut.
