### ISSUE TITLE
wp core download --locale=en_GB : Error: The requested locale (en_GB) was not found.

### ISSUE THREAD

**Issue by chriscroome** [wp-cli/wp-cli#4669]
I stopped using `wp --allow-root core download` because [it was failing](https://github.com/wp-cli/wp-cli/issues/4370#issuecomment-332012902) and switched to using `wp --allow-root core download --locale=en_GB` because it worked.

However now that doesn't work and I'm switching back

```bash
wp --allow-root core download --locale=en_GB
Error: The requested locale (en_GB) was not found.

wp --allow-root core download 
Downloading WordPress 4.9.3 (en_US)...
md5 hash verified: be602a64e3e406ba7fecdade6cc9d9cf
Success: WordPress downloaded.
```

If there is anything to can do to help debug this issue I'm happy to help, I'm not the only one with [issues of this nature](https://github.com/wp-cli/wp-cli/issues/4436).

**Comment by schlessera** [comment]
The 4.9.3 Core is not yet released for that locale, that's why it can't be found. At the time of writing, this is what the official en-GB page shows as the latest release:

<img width="723" alt="image 2018-02-06 at 3 32 06 pm" src="https://user-images.githubusercontent.com/83631/35864749-e81dc376-0b52-11e8-9cfc-9f0d0ea3aad6.png">

I suppose that when you originally switched, you were facing this issue instead, which has since been resolved: https://github.com/wp-cli/wp-cli/issues/4370

**Comment by chriscroome** [comment]
Do'h, thanks 🙂 .
