### ISSUE TITLE
Quotes in arguments get stripped when using WP-CLI::runcommand with 'launch'=>false

### ISSUE THREAD

**Issue by rosswintle** [wp-cli/wp-cli#4741]
Quotes in arguments get stripped when using WP-CLI::runcommand with `'launch'=>false` set

### Steps to reproduce:

1. Create a file, `test.php`, containing the following:

```
<?php
WP_CLI::runcommand( 'post create --post_title="Hello world!"', ['launch' => false]);
```

2. Run `wp eval-file test.php`

### Expected result:

A post is created with the title 'Hello world!"

### Actual result

```
$ wp eval-file test.php
Error: Unable to read content from 'world!"'.
```

### Other info

This doesn't seem to happen if `'launch'=>true`

**Comment by jmichaelward** [comment]
Hmm, this is perplexing. When running this example, it appears that the string that gets passed in to `WP_CLI::runcommand` looks like:

```
"post create --post_title="Hello world!""
```

Which means the single quotes are getting replaced with double quotes before the query gets to the method. This is therefore causing the `world!` string to be treated as a separate argument instead of a part of the string.

There is a `$launch` condition inside `runcommand` that parses those arguments differently - when `$launch` is `true`, the value of `$GLOBALS['argv']` is used, but when it's false, the string gets passed to a helper function `Utils\parse_str_to_array` that clearly isn't processing the command the same way. It seems like looking into that method is a great first place to start, but I'd also investigate whether there's a way to handle quote formation issue.

**Comment by jmichaelward** [comment]
These two lines in `php/utils.php`'s `parse_str_to_argv` method are responsible for the error:

```
preg_match_all( '/(?<=^|\s)([\'"]?)(.+?)(?<!\\\\)\1(?=$|\s)/', $arguments, $matches );
$argv = isset( $matches[0] ) ? $matches[0] : array();
```

The method accepts a string parameter named `$arguments`, which in the example is `"post create --post_title="Hello world!""`. `preg_match_all` finds this array of `$matches`:

```
array(3) {
  [0] =>
  array(4) {
    [0] =>
    string(4) "post"
    [1] =>
    string(6) "create"
    [2] =>
    string(19) "--post_title="Hello"
    [3] =>
    string(7) "world!""
  }
  [1] =>
  array(4) {
    [0] =>
    string(0) ""
    [1] =>
    string(0) ""
    [2] =>
    string(0) ""
    [3] =>
    string(0) ""
  }
  [2] =>
  array(4) {
    [0] =>
    string(4) "post"
    [1] =>
    string(6) "create"
    [2] =>
    string(19) "--post_title="Hello"
    [3] =>
    string(7) "world!""
  }
}
```

It's not clear to me whether this regex can be updated to look for double quotes and ignore them, but it seems that this method will need additional consideration if this problem is to be resolved.

**Comment by Mekton** [comment]
I encountered the same problem, the solution was to escape the space character like this :
`post create --post_type=page --post_title="Hello\ world!"`

**Comment by schlessera** [comment]
Related: https://wordpress.slack.com/archives/C02RP4T41/p1540995345199900
