### ISSUE TITLE
PHP Parse error:  syntax error, unexpected 's' (T_STRING) in php_error.log

### ISSUE THREAD

**Issue by ecobux** [wp-cli/wp-cli#4786]
When I run `wp scaffold plugin-tests`, the command fails silently. With adding "--debug" I see

```
Debug (bootstrap): Using default global config: /Users/xyz/.wp-cli/config.yml (0.177s)
Debug (bootstrap): No project config found (0.181s)
Debug (bootstrap): argv: /Applications/MAMP/bin/php/php7.1.12/bin/wp-cli.phar scaffold plugin-tests my-plugin-name --debug (0.181s)
Debug (bootstrap): ABSPATH defined: /Users/ ... /htdocs/wordpress/ (0.181s)
Debug (bootstrap): Begin WordPress load (0.184s)
Debug (bootstrap): wp-config.php path: /Users/ ... /htdocs/wordpress/wp-config.php (0.184s)
```
config.yml is empty. All paths seem to be correct. Tried with various plugins.

The php_error.log shows:
`PHP Parse error:  syntax error, unexpected 's' (T_STRING), expecting ',' or ')' in phar:///Applications/MAMP/bin/php/php7.1.12/bin/wp-cli.phar/php/WP_CLI/Runner.php(1138) : eval()'d code on line 91`

I tried other commands, like `wp plugin get` - same error.

`wp --info` returns:
```
OS:	Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
Shell:	/bin/bash
PHP binary:	/Applications/MAMP/bin/php/php7.1.12/bin/php
PHP version:	7.1.12
php.ini used:	/Applications/MAMP/bin/php/php7.1.12/conf/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/ ... /htdocs/wordpress
WP-CLI packages dir:	
WP-CLI global config:	/Users/xyz/.wp-cli/config.yml
WP-CLI project config:	
WP-CLI version:	1.5.1
```
The installation is on localhost with MAMP 4.4.1, free version. That WordPress site runs without any errors/warnings/notices in php_error.log or error.log. The beginning of config.php seems to be OK, as verified with `hexdump -C wp-config.php | head -1`.

In the admin, all plugins are deactivated and the theme is Twenty Seventeen.

**Comment by schlessera** [comment]
This is probably some plugin that is currently active on your site that breaks in CLI context.

You can try to run your commands by adding the flag `--ski-plugins`.

If you need further support, please review support options at http://wp-cli.org/#support

**Comment by ecobux** [comment]
@schlessera All plugins were deactivated. Please read my initial post.

I know http://wp-cli.org/#support - that's how I came here.

It would really be useful if WP-CLI could offer a bit more debugging information. Also, it's difficult for users to understand what is considered a valid bug and if reporting errors here is actually welcome.

**Comment by schlessera** [comment]
> It would really be useful if WP-CLI could offer a bit more debugging information.

WP-CLI uses WordPress for pretty much all of the actual logic, it is just the interface wrapper. While WP-CLI does produce quite a bit of debugging information or other feedback, WordPress generally doesn't. It just fails silently.

> Also, it's difficult for users to understand what is considered a valid bug and if reporting errors here is actually welcome.

Bug are in general an error that is reproducible. So, given a same command run in a same context, the error should be the same for everyone. If an error happens to only occur in an individual environment, we first assume that there's a problem with the environment, not WP-CLI, as the error would be common for all users otherwise.

Your bug reports are of course always welcome.

However, in this case, reading through your output, I see that you are using MAMP, which is known to cause all sorts of weird issues with PHP, as it deviates from a standard setup.

The line your error message refers to is this one: https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Runner.php#L1138

This lets me assume that you don't have a valid config file in the installation you're using (or it can't be properly detected/parsed), and your environment is broken in such a way that the error message cannot be printed.

Please feel free to continue discussing a possible diagnostic of the above issue in Slack. But until further evidence, I have to assume that this is not a reproducible bug.

**Comment by ecobux** [comment]
After a long time, I gave it another try and now I figured out what was the problem - just in case somebody else has the same issue:

The path on my local machine to the WordPress folder contains a `'s`, like:
`/something/X's folder/htdocs`

That doesn't seem to get escaped properly. I solved it by renaming `X's folder` to `Xs folder`. Fortunately it has nothing to do with the configuration or MAMP.  🍾
