### ISSUE TITLE
wp-cli-ssh Issue

### ISSUE THREAD

**Issue by JayHoltslander** [wp-cli/wp-cli#4831]
Trying to connect to a remote server from my local machine and having this problem.

````bash
$ wp ssh user list --host=staging
The authenticity of host ' (127.0.0.1)' can't be established.
ECDSA key fingerprint is SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxx.
Are you sure you want to continue connecting (yes/no)? yes
Password: *******

Warning: preg_match() expects parameter 2 to be string, array given in phar:///Users/me/.wp-cli/wp/php/utils.php on line 824

Warning: preg_match() expects parameter 2 to be string, array given in phar:///Users/me/.wp-cli/wp/php/utils.php on line 839
The authenticity of host ' (127.0.0.1)' can't be established.
ECDSA key fingerprint is SHA256: xxxxxxxxxxxxxxxxxxxxxxxxxx.
Are you sure you want to continue connecting (yes/no)? no
Error: Cannot connect over SSH using provided configuration.
Error: Cannot connect over SSH using provided configuration.
````

~/.wp-cli/config.yml contains:

````
require:
  - commands/wp-cli-ssh/wp-cli-ssh.php

ssh:

  staging:
    cmd: ssh %pseudotty% root@XXX.XXX.XX.XX %cmd%
    url: http://mysite.com
    path: /
````

I'm unclear why it's trying to connect to 127.0.0.1 and can't verify the authenticity of... myself.
(My known_hosts file doesn't contain any entries for 127.0.0.1)

I followed the instructions at <https://kinsta.com/blog/wp-cli/>

**Comment by schlessera** [comment]
@JayHoltslander The blog post you're linking to is out of date and has you use a deprecated command: `wp-cli-ssh` has been integrated into WP-CLI since v0.24.

Here's the documentation on how to use WP-CLI remotely: https://make.wordpress.org/cli/handbook/running-commands-remotely/

Also, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
