### ISSUE TITLE
WP CLI search-replace is not replacing all matches there in DB

### ISSUE THREAD

**Issue by ds250568** [wp-cli/wp-cli#4871]
WP CLI search-replace is not replacing all matches there is DB

I am using wordpress-seo plugin which stores the site pages URL in to wp_options table with some dymamic key transient "_transient_yst_sm_post_1:2FGA4_3oum9".

I am running wp search-replace 'wph/dev' 'wph/live' which replace this everywhere but not is key stored by wordpress-seo plugin..

Can you guys look into this and suggest me.

**Comment by Reiner030** [comment]
Hi, 
I had some equal problem - only 6 out of 18 tables where registered in $WPDB handler.
For this the documentation offers several parameters for every needs, in your case the `--all-tables-with-prefix` should match or the `--all-tables` if the temporary tables haven't same prefix:

https://developer.wordpress.org/cli/commands/search-replace/
>
> `[<table> …]`
> List of database tables to restrict the replacement to. Wildcards are supported, e.g. `'wp_*options'` or `'wp_post*'`.
> `[--all-tables-with-prefix]`
> Enable replacement on any tables that match the table prefix even if not registered on $wpdb.
> `[--all-tables]`
> Enable replacement on ALL tables in the database, regardless of the prefix, and even if not registered on $wpdb. Overrides `–-network` and `-–all-tables-with-prefix`.
> `[--skip-tables=<tables>]`
> Do not perform the replacement on specific tables. Use commas to specify multiple tables.
> `[--skip-columns=<columns>]`
> Do not perform the replacement on specific columns. Use commas to specify multiple columns.
> `[--include-columns=<columns>]`
> Perform the replacement on specific columns. Use commas to specify multiple columns.
> 

(and every command has it's own repository here I found out 2 days ago :smile: so right choice would be: https://github.com/wp-cli/search-replace-command/issues )

**Comment by schlessera** [comment]
Note: your issue might also be that the value you want to replace could be serialized in such a way that `wp search-replace` cannot reliably change it yet.

Anyway, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by ds250568** [comment]
yes you are right. This is a bug for which I need a fix or a suggestion how to fix in search-replace command. what ever the value is not replace is in wp_options table in option_value which a default wp table. 

Your this statement "Note: your issue might also be that the value you want to replace could be serialized in such a way that wp search-replace cannot reliably change it yet.", I think fits to the situation but it is creating a huge blocker for me. 

Can you provide a fix for this.

**Comment by wojsmol** [comment]
@ds250568 Please see last sentence  in @schlessera reply.

**Comment by StephenGravitt** [comment]
I've come across a third party plugin (not to be named) which entertains tables without the prefix AND have no primary key. So even running a search-replace with the --all-tables or even --precise flags won't do the trick. Some times your solution is to define a primary key or roll up your sleeves and look at the data via db tool such as phpmyadmin, adminer, or mysql workbench.

**Comment by elliottpost** [comment]
While @schlessera's response that WP may not be able to do this safely yet is a good concern, I think a developer running WP CLI should be able to make that decision themself without having to resort to installing a plugin or a 3rd party tool. Adding support to use other tables not registered with WPDB could be enabled with a flag like `--allow-risky-business` or something a bit more professional.

For now, this safety limitation is in itself just that: a limitation. I argue that WP CLI should allow developers to make the decision whether or not they want to risk it, rather than having WP flat out disallow it.

A temporary work around can be using a tool like https://interconnectit.com/products/search-and-replace-for-wordpress-databases/ but this introduces security risks as if a user doesn't delete it, then their entire WP database is compromised.

**Comment by schlessera** [comment]
I stated that WP-CLI cannot do it _reliably_, it is already unsafe to do something like this anyways, we're directly manipulating the database. WP-CLI easily lets you destroy the entire installation with a single command.

The problem I'm referring to is that, to unserialize objects, the classes need to be declared (known to PHP) that these objects represent. Otherwise, there is just no knowledge about the internal structure of what this data is supposed to be.

Classes should usually be declared, because we're loading the entire WordPress site. However, there are edge cases where this is not true and unserializing the objects will fail:
* data stored by a plugin or theme that has been deactivated/uninstalled
* running search-replace with --skip-plugins/--skip-themes
* running search-replace across tables that are not linked to the current WP install, so the list of active plugins/themes is incorrect
* ...maybe others?

In the above cases, WP-CLI might encounter data that states: "if you want to unserialize me, I am of type 'SomeClass'...", but PHP does not know what 'SomeClass' is.

**Comment by elliottpost** [comment]
Hey @schlessera, I agree that it's already unsafe and I recognize your distinction between reliable and unsafe. I also appreciate you identifying the edge cases--it's a great sign to see careful planning go into the development of these tools. 

The argument I'm making; however, is that because it's already unsafe to do these operations, that to enable a flag which extends that functionality slightly improves the capability of WP-CLI without risk to default behavior. Developers already take their WP install's "life in their hands" every time they perform database updates without doing these as reversible and trackable migrations, as well as any number of risky behavior by "just copy pasta this functions.php gist." 

More to the point, there is a need for this functionality. Users will simply download 3rd party plugins to meet their needs. I argue that the WP development team would be more pro-active about safety  (as shown in your own response of identifying the potential concerns) than a 3rd party developer. Allowing an advanced user, who understands the risks and implications involved, to pass a flag (like is already allowed in some of the base DB commands like `--all-tables`) removes the requirement for a 3rd party migration tool that does exactly what WP CLI does when they already have WP CLI installed. 

I don't know how I could collect evidence to support or disprove this hypothesis, but it seems to me that a developer who has tables not registered under WPDB probably has an advanced use case and probably isn't storing serialized data in a relational database to begin with, as they would have tables that are built for specific entities rather than the general purpose tables WP uses which require serialization regularly. Even if they do, by using the `--allow-risky-business` flag they're sort of acknowledging that they have RTFM and understand the consequences if they have bad serialization practices in effect.
