### ISSUE TITLE
Use WP-CLI as local Composer dependency

### ISSUE THREAD

**Issue by leymannx** [wp-cli/wp-cli#4935]
Let's assume I started a Composer-based WordPress project. For example by using https://github.com/roots/bedrock or https://github.com/wodby/wordpress-composer, or something similar.

I set up everything. WordPress up and running, fine. Now I'd like to add and use WP-CLI to this project by including it **locally**. Without the need to install it globally anywhere.

So I just `composer require wp-cli/wp-cli` then change directory into the WordPress web root and fire the command:

```shell
$ cd web
$ ../vendor/bin/wp --info
OS:	Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php
PHP version:	7.1.16
php.ini used:	/etc/php.ini
WP-CLI root dir:	/Users/leymannx/Sites/some-dir/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	/Users/leymannx/Sites/some-dir/vendor
WP_CLI phar path:
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.0.1
$ ../vendor/bin/wp plugin activate cfm
Error: 'plugin' is not a registered wp command. See 'wp help' for available commands.
```

So far so good. But how can I include more useful commands now in that local setup? What environment variables or other steps need to be accomplished to make WP-CLI work that way?

**Comment by schlessera** [comment]
Since v2, the `wp-cli/wp-cli` package is only the framework itself, without any of the actual commands (except for `cli` and `help`). Pulling in the framework for your project does not make sense, it should only be indirectly used as a dependency of commands.

You can either:

a) Pull in the specific command packages you need. For `plugin ...` for example, this would be the `wp-cli/extension-command` package.

b) Pull in the entire bundle, which gives you all the commands that are part of the default PHAR-based distribution. Just require `wp-cli/wp-cli-bundle` to make this happen.

Also, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
