### ISSUE TITLE
Outdated css file after wp theme activate

### ISSUE THREAD

**Issue by steefaan** [wp-cli/wp-cli#5006]
After running `wp theme activate uncode` for [Uncode theme](https://undsgn.com/uncode/) the theme is active but the css file is outdated. If I activate the theme manually through the admin area everything works as expected.

wordpress: 4.9.8
wp-cli: 2.0.1

**Comment by schlessera** [comment]
WP-CLI just reuses the WordPress Core functionality to switch the active theme (as you can see [here](https://github.com/wp-cli/extension-command/blob/master/src/Theme_Command.php#L226)).

This is probably because the theme makes some assumption that is not true in the context of WP-CLI. You should contact the support of the theme about this.
