### ISSUE TITLE
WP_CLI_CONFIG_PATH environment ignored

### ISSUE THREAD

**Issue by majick777** [wp-cli/wp-cli#5136]
While using global config at `/root/.wp-cli/config.yml` works fine,
I was trying to set the `WP_CLI_CONFIG_PATH` in a bash shell script, eg:

```
export WP_CLI_CONFIG_PATH="/root/.wp-cli/sitename.yml"
printenv WP_CLI_CONFIG_PATH
sudo -u root wp --info --debug
```
The printenv line prints `/root/.wp-cli/sitename.yml` fine.
but the WP CLI debug line gives:
`Debug (bootstrap): no readable global config found.`
(is_readable("/root/.wp-cli/sitename.yml") returns true in PHP)

Not sure why this is being so difficult? I can see the WP CLI PHP just
checks using `getenv`, so feel rather stumped the value is just being ignored.
Am I missing something simple or is this just not working as expected..? 
(Maybe there could be an example added somewhere in the handbook?)

While on the topic, is there a reason why the the project config names
are limited to `wp-cli.yml` and `wp-cli.local.yml`..? as this is really what I was
wanting to specify rather than changing the global config anyway.
Ideally I would like to have a directory `/wp-configs/` with all the YAML files 
in one place, eg. `sitename1.yml`, `sitename2.yml`, but the lack of a
corresponding `--wp-cli-config-path=` switch prevents this, so I am 
attempting to use the global config instead (as I understand I can 
load the actual global config via eg. `_: inherit: /root/.wp-cli/global.yml`)

**Comment by schlessera** [comment]
@majick777 You are setting the environment variable for the user that you are currently running under, but then change the user to `root` to execute WP-CLI, which means the environment variables are different ones.

To make this work, you'll have to adapt the environment variables for the `root` user, not your currently active one.

There are several ways you can try to do this (all of these untested, just what I think could possibly work):

* The easiest solution would be to use the option to "preserve the environment" when switching users. This is usually the `-E` switch to `sudo`, but it might be blocked by security policies.
* Forward the environment variable to the call. This could be done through something like this: `sudo -u root WP_CLI_CONFIG_PATH=$WP_CLI_CONFIG_PATH wp --info --debug`.
* Alternatively, what you are trying to do is actually load in the local config file from some place else. You might want to look into using something like this in your project folder's `wp-cli(.local).yml` file instead:
```
_:
    # Merge subcommand defaults from the upstream config.yml, instead of overriding
    merge: true
    # Inherit configuration from your a site-specific one upstream
    inherit: /root/.wp-cli/<sitename>.yml
```

The last one will obviously just work if you only run WP-CLI as root, so that it can have access to this folder. You might rethink the placement and put your configuration files under `/etc/wp-cli` instead, to make them independent of the specific user.

On another note, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/). Just head over there, and we can continue this discussion if you need further help.

**Comment by majick777** [comment]
@schlessera Gotcha! I appreciate the help and pointers, sorry if it was a bit out of place.
I was partly hoping to suggest that `--wp-cli-config-path=` be added as a feature.
Since the environment variable can be used to set the global config path as you've shown, the switch could be used to specify an alternative project configuration location instead (which would be easier than overriding this via inherit.)

**Comment by schlessera** [comment]
The main issue I see here is that you are effectively turning project-specific configuration (located with the project) into global configuration (located in one central place, irregardless of the project). The fact that you're naming the config files after the different sites does not really change that.

**Comment by majick777** [comment]
Yes that is what I was hoping to avoid - using the project configurations as global configs.
Which is exactly why it would be nice to be able to set a specific project configuration path from the command line instead, so it automatically respects the global config still.
The inherit method can do it, but really adds a level of complexity to my particular use case.
All this made me realize there *is* a actually simple way!
`cd /site-configs/<sitename>/wp-cli.yml && sudo -u user wp`
Which will read the site project config file and use it so long as path/ssh is set, lol.
Sure I was hoping to have `/site-configs/<sitename>.yml` but that'll do. :-)
