### ISSUE TITLE
wp-cli searching for every plugin in every subcommand

### ISSUE THREAD

**Issue by MacGyer** [wp-cli/wp-cli#5139]
Hey guys,

I am using a [Bedrock ](https://roots.io/bedrock/) based Wordpress with wp-cli-bundle installed.

On the live system a strange behaviour occurred as the IT is reporting numerous requests made by wp-cli when accessing frontend.

I am trying to explain:

When accessing a frontend page, more than 3000 calls are made to all plugin files in all CLI subcommands, which are leading to a "No such file or directory" result.

Find following an strace output:

```
15459 lstat("/var/www/vhosts/mydomain.com/web/releases/2019-04-11-13-43-38/app/web/app/plugins/ajax-load-more/ajax-load-more.php", {st_mode=S_IFREG|0644, st_size=23247, ...}) = 0
15459 lstat("/var/www/vhosts/mydomain.com/web/releases/2019-04-11-13-43-38/app/web/app/plugins/ajax-load-more", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
15459 stat("/var/www/vhosts/mydomain.com/web/releases/2019-04-11-13-43-38/app/web/app/plugins/ajax-load-more/ajax-load-more.php", {st_mode=S_IFREG|0644, st_size=23247, ...}) = 0
15459 access("/var/www/vhosts/mydomain.com/web/releases/2019-04-11-13-43-38/app/vendor/composer/../wp-cli/widget-command/src/AjaxLoadMore.php", F_OK) = -1 ENOENT (No such file or directory)
15459 access("/var/www/vhosts/mydomain.com/web/releases/2019-04-11-13-43-38/app/vendor/composer/../wp-cli/super-admin-command/src/AjaxLoadMore.php", F_OK) = -1 ENOENT (No such file or directory)
15459 access("/var/www/vhosts/mydomain.com/web/releases/2019-04-11-13-43-38/app/vendor/composer/../wp-cli/shell-command/src/AjaxLoadMore.php", F_OK) = -1 ENOENT (No such file or directory)
15459 access("/var/www/vhosts/mydomain.com/web/releases/2019-04-11-13-43-38/app/vendor/composer/../wp-cli/server-command/src/AjaxLoadMore.php", F_OK) = -1 ENOENT (No such file or directory)
15459 access("/var/www/vhosts/mydomain.com/web/releases/2019-04-11-13-43-38/app/vendor/composer/../wp-cli/search-replace-command/src/AjaxLoadMore.php", F_OK) = -1 ENOENT (No such file or directory)
```

This is from Ajax Load More plugin only. Tries for other plugins, too.

Why is it trying to load `app/vendor/composer/../wp-cli/widget-command/src/AjaxLoadMore.php` or `app/vendor/composer/../wp-cli/super-admin-command/src/AjaxLoadMore.php` and so on?

After some more research, I have got the feeling every plugin is being autoloaded and is looked for in every subcommand's `src` folder.
Sounds bit like a composer autoload misconfiguration?!

I have skipped all plugins in wp-cli.yml (except wp-migrate-db as it is needed).

I don't even know whether this is a Bedrock issue or wp-cli issue. Maybe you can shed some light on this?

Thanks in advance for getting back.

**Comment by schlessera** [comment]
@MacGyer This is the PHP autoloader going through all registered namespace roots to see whether it finds a match for the `AjaxLoadMore` class.

As it starts in the folder of that plugin, it either has a bad autoloader configuration (because after that, the PHP autoloader should have found the class), or there's permission issues on your filesystem.

Also, this means you're using unoptimized autoloaders on your production site. The autoloader is always trying to find the files on the filesystem at runtime, instead of having a hardcoded list of mappings. You should use the Composer `-o` flag on production sites to generate optimized autoloader classmaps, and the `-a` flag to make these authoritative. This way, there's only 1 hardcoded possibility for the class file location, and there's no filesystem lookups.
Look here for more details: https://getcomposer.org/doc/articles/autoloader-optimization.md

Either way, this is not an issue specific to WP-CLI (apart from the fact that it is one of the many packages that register an autoloader on the root namespace for legacy reasons), so I'm closing this issue in here.

**Comment by MacGyer** [comment]
Thanks for your reply.

I did some more research. I removed the wp-cli-bundle from composer.json, added only wp-cli/wp-cli.

The behaviour does not occur.

As I need the plugin command bundle I added the wp-cli/extension-command package and after that, the problem existed.
A test with wp-cli/i18n-command instead of extension-command did not produce the behaviour.

So maybe it is more related to wp-cli/extension-command package than wp-cli?

I will check the optimized autoload thingy, thanks for that.

**Comment by schlessera** [comment]
First of all, with WP-CLI v2, you don't need to require either the `wp-cli/wp-cli-bundle` or the `wp-cli/wp-cli` package explicitly, if all you want is to have 1 command available. Just require the package of that command, and you're fine.

If you need to command only during development, you should add it to `"require-dev"` instead of `"require"`. This way, if you optimize for production, it will be completely gone.

Finally, what you see is the autoloader going through all commands that are registering an autoloader against the root namespace. For commands that use a proper namespace themselves, this does not happen. So the `wp-cli/extension-command` has been around for a long time, and for legacy reasons, it doesn't come with a proper namespace, it just registers the autoloader against the namespace `""`.
<img width="296" alt="Image 2019-04-12 at 7 10 20 PM" src="https://user-images.githubusercontent.com/83631/56054382-f45fcb00-5d56-11e9-8c76-2ac1e3269978.png">
For this reason, Composer cannot do an early exit and needs to check the actual file to see if there is a match, when a class without namespace (like `\AjaxLoadMore` here)  is being requested.

The `wp-cli/i18n-command`, however, is more recent, and does actually use a proper namespace for its autoloader.
<img width="291" alt="Image 2019-04-12 at 7 13 03 PM" src="https://user-images.githubusercontent.com/83631/56054408-03df1400-5d57-11e9-9d3e-c6eed5ef74be.png">
Therefore, Composer can exit early without checking the filesystem, as namespaces that start with `\WP_CLI\i18n\` cannot possibly match the FQCN `\AjaxLoadMore`.

That being said, it still seems to be an error that the `\AjaxLoadMore` class is not found while going through the `ajax-load-more` files (which would stop autoloader checking at that point then and not bother with WP-CLI at all).

**Comment by MacGyer** [comment]
@schlessera 

Thanks again for thoroughly going through this.

The `AjaxLoadMore` was just an extract of the strace output. Actually Composer was trying to find nearly all plugin files inside the wp-cli/src namespace.

Anyway, optimizing the autoloaders with the `-o` flag did really good. It's not perfect, but it is a step in the right direction.
