### ISSUE TITLE
Add PHP 7.3 to the Travis CI build matrix

### ISSUE THREAD

**Issue by localheinz** [wp-cli/wp-cli#5160]
PHP 7.3 was released on December 6, 2018, so I believe it's about time to add it to the Travis CI build matrix, so we can make sure everything works as expected on PHP 7.3 as well.

**Comment by schlessera** [comment]
You said you're interested in managing the pull requests across the repositories, so I'll try t go through how I normally do this. There is no fully automated tooling for that yet, but I intend to add that to the `wp-cli/wp-cli-dev` repository at some point, so this will serve as an initial "spec" I guess...

Scripting pull requests is pretty easy for Github if you have the `hub` tool installed: https://github.com/github/hub

I'm currently using a very simplistic script to run a command across all "bundled" repositories. I usually deal with the non-bundled repositories separately, because most of them do not share the same standardized setup.

Here's the basic script I'm currently using:
```bash
#!/usr/bin/env bash

BUNDLE_DEPENDENCIES=$(curl --silent https://raw.githubusercontent.com/wp-cli/wp-cli-bundle/master/composer.json -q | jq '.["require"] | keys[]' )
BUNDLE_DEPENDENCIES=$(echo "wp-cli/wp-cli-bundle $BUNDLE_DEPENDENCIES")

for NAME in $BUNDLE_DEPENDENCIES; do

	REPO=$(echo $NAME | tr -d '"')
	case $REPO in wp-cli/*)
	    export REPO=$(echo "$REPO" | sed -e "s|^wp-cli/||")
	    if [ -d "$REPO" ]; then
			OLDPWD="$(pwd)"
			cd "$REPO"
			echo "--- $REPO : ---"
			"$@"
			cd "$OLDPWD"
		fi
	esac
done
```

Of course, feel free to use any other script/tool you feel comfortable with. Just remember that there are repositories in the `wp-cli` organization that don't share the same setup as the bundled commands. Only the bundled commands are guaranteed to adhere to all of the conventions.

If you clone the `wp-cli/wp-cli-dev` repository and run `composer install`, it should set you up with all the individual repositories, and you can run commands against them all from there.

My first action is usually run a `git status` first and then resetting the repositories and switching to `master` branch, as there might be previous work in there (make sure you don't delete changes you still want to keep).
```bash
# Check what state we are in first, to make sure we're not erasing changes that are still needed.
./foreach-bundle git status

# If needed, checkout the `master` branch and pull latest changes.
./foreach-bundle git checkout master && git pull

# Create a new branch for the pull-request.
./foreach-bundle git checkout -b add-php-7-3-tests
```

Now your repositories should be in the correct state to accept the code changes for the PR.
There are multiple ways you can do these changes: copy over a file, apply a git patch, run a sed, ...

After the changes are done, you can verify you didn't mess anything up and then commit and create the PR:
```bash
# Make sure the changes are as expected and that only the correct files are affected.
./foreach-bundle git status && git diff

# Stage the changes and commit them.
./foreach-bundle git add . && git commit -m 'Add PHP 7.3 to the Travis test matrix'

# Fork the repository.
./foreach-bundle hub fork

# Create the pull-request. I usually create a small text file with the pull-request message first, containing all info and links to the related issue(s).
./foreach-bundle hub pull-request --file prtext.txt --labels scope:distribution
```

All of the above is just done from memory now without testing, so proceed with caution and verify the results after each step. Let me know if you hit any issues.

**Comment by localheinz** [comment]
@schlessera 

I think this worked quite well, thank you for the tips.

Now I better unterstand why it's preferred to create an issue first, I was a bit puzzled at first.

**Comment by schlessera** [comment]
Thanks for the PRs, @localheinz!

I will not merge these immediately, as we're currently in the middle of doing a big push to get a custom PHPCS standard implemented and enforced, and our main bottleneck is Travis. So expect 1 or 2 days of delay before I'll go through them and merge them.

**Comment by schlessera** [comment]
Note: an added side benefit of this approach (issue + systematic PRs with link to issue) is that we have a full overview of the current status above, the list of PRs referencing the issue.

**Comment by danielbachhuber** [comment]
I'll go through and merge a number of these closer to the end of the day Pacific.

**Comment by danielbachhuber** [comment]
@schlessera Thanks for taking the time to explain with such detail, by the way. You're a better person than I 😄

**Comment by schlessera** [comment]
All done, awesome work, @localheinz ! Thanks for the big effort!
