### ISSUE TITLE
wp cli alias doesn't respect --path flag

### ISSUE THREAD

**Issue by peterjohnhunt** [wp-cli/wp-cli#5205]
## Bug Report

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

`wp cli alias` command using `--path="/my/wp/install"` flag returns results based off the current working directory instead of the `--path` flag

I tested on both stable and the nightly release, as i noticed some additions / changes to the alias command that have been made (but not yet released), but the same result occurred on that as well.

**Describe how other contributors can replicate this bug**

- add custom alias to wp-cli.yml in a WordPress install folder
- cd into a random folder that is NOT the WordPress install folder the alias was just added to
- run `wp cli alias --path=/path/to/wordpress/install`

**Describe what you expect as the correct outcome**

Expected to return the aliases defined in the site as notated by the `--path` flag

**Let us know what environment you are running this on**

```
OS:	Darwin 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
Shell:	/bin/bash
PHP binary:	/Applications/MAMP/bin/php/php7.3.1/bin/php
PHP version:	7.3.1
php.ini used:	/Applications/MAMP/bin/php/php7.3.1/conf/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/peterjohnhunt
WP-CLI packages dir:	/Users/peterjohnhunt/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.1.0
```

**Provide a possible solution**

It's possible this isn't intended to work, in which case documentation could be adjusted for the alias command to not mention the global flags, or specifically say they are excluded for that command.

**Comment by peterjohnhunt** [comment]
Since 2.2.0 was released like 4 hours after this, i have re-tested with `wp cli alias list --path="my/wp/install"` but have encountered the same results!

**Comment by thrijith** [comment]
Hi @peterjohnhunt thanks for reporting the issue.

`wp cli *`  commands are hooked to run before wp load, I don't think `--path` was supposed to work in this case, @schlessera thoughts?

As of now to list aliases from an individual installation, you would have to run `wp cli alias list` inside the installation path.

To avoid confusion, I think this doc block should also be updated.
>WP-CLI has a series of global parameters (e.g. --path=<path> and --user=<user>) which work with all commands. They are called global parameters because they affect how WP-CLI interacts with WordPress, and have the same behavior across all commands.

Ref: https://make.wordpress.org/cli/handbook/config/

**Comment by schlessera** [comment]
I don't think this is a bug per se and just the expected behavior as I currently understand it.

The local config is the `wp-cli.yml` file in the current folder. This can be in any folder, it doesn't have to be a WordPress installation at all.

The documentation for `--path` states that it is the:
> Path to the WordPress files.

Often, you have the web root contain a `wp-cli.yml`, and that file contains a `path` instruction to a subfolder when WordPress is installed in that subfolder instead of the web root.

So there is a difference between "location of the local config file" and "location of the WordPress files". Your current folder dictates the first, the `--path` parameter dictates the second.

I don't see how we could easily change this behavior, as for example, what happens when you have `--path` inside of your local config? Would the local config itself be disregarded then?

The only way to fully solve this would be to follow locations recursively, check for a local config in each location and merge them. That might lead to unexpected consequences, though...

**Comment by peterjohnhunt** [comment]
Thanks @thrijith & @schlessera! It primarily came up because i use the node wrapper in some VSCode packages for WP-CLI which technically uses WP-CLI by running all commands with the --path flag instead of actually changing the directory it's using. I figured in this case it may not be an intended feature but wanted to check since the global flags were listed on the docs page for it! Thanks to both of you for the help!
