### ISSUE TITLE
Tagged release missing updated VERSION file

### ISSUE THREAD

**Issue by 0x6d617474** [wp-cli/wp-cli#5359]
The most recent tagged release (`2.4.1`) is missing an updated VERSION file, and so still reports as `2.4.0`. The VERSION file should be updated and the release should be re-tagged such that `wp --version` reports an accurate version number.

**Comment by schlessera** [comment]
Please look at the Slack chat [starting here](https://wordpress.slack.com/archives/C02RP4T41/p1582042168265300) for an explanation of why I decided to decouple "WP-CLI - the binary" version from "WP-CLI - the framework" version (these were kept in sync before since split up for v2.0.0.

The framework received a patch version v2.4.1 to fix an issue that is only present for people using WP-CLI via Composer, there's no benefit of releasing a new binary.

**Comment by 0x6d617474** [comment]
I think you may have confused this bug report with the one I opened in wp-cli-bundle. This is the behavior I see when I install wp-cli via composer. Shouldn't the version number reported match what composer installed?.

```
$ cat composer.json 
{
    "require": {
        "wp-cli/wp-cli": "^2.4.1"
    }
}

$ ./vendor/bin/wp --version
WP-CLI 2.4.0
```

**Comment by schlessera** [comment]
Ah, right. This actually introduces a different problem. The version that is being reported is not meant to show the framework version, but rather the bundle version. However, when using Composer, there usually is no bundle... 🤔
