### ISSUE TITLE
Parse error on PHP 7.4 class property with type declaration

### ISSUE THREAD

**Issue by Spartelfant** [wp-cli/wp-cli#5404]
## Bug Report
- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When running any command, WP-CLI reports a parse error if it encounters any mu-plugin or any active plugin with a type declaration for a class property. Inactive plugins do not trigger this error.

**Describe how other contributors can replicate this bug**

Using `WP-CLI 2.5.0-alpha-c4c9f7e` with a clean [WordPress 5.4.1](https://github.com/WordPress/WordPress/tree/5.4.1) installation on a server running PHP 7.4.6, try commands such as `wp user list`, `wp plugin list`, `wp create user`, etc. They should complete normally.

Now introduce an mu-plugin or an active plugin that makes use of the following [PHP 7.4 new feature](https://www.php.net/manual/en/migration74.new-features.php):

>Class properties now support type declarations.

The following example code is enough to trigger the parse error:

```php
class My_Class {
    public static ?string $class_property = null;
}
```

Now try any WP-CLI command again and it won't succeed, instead reporting a parse error:

    Parse error: syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in /srv/www/wordpress/public_html/wp-content/mu-plugins/test.php on line 3

WP-CLI will experience a parse error regardless of the presence of the `?` prefix, signifying a nullable type. This [feature was introduced with PHP 7.1](https://www.php.net/manual/en/migration71.new-features.php). Removing the `?` prefix from the above example code results in the following error message:

    Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /srv/www/wordpress/public_html/wp-content/mu-plugins/test.php on line 3

**Describe what you expect as the correct outcome**

I expected the command to complete normally.

**Let us know what environment you are running this on**

```
OS:     Linux 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.2
PHP version:    7.2.31-1+ubuntu18.04.1+deb.sury.org+1
php.ini used:   /etc/php/7.2/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.3.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:      STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /srv/www/wordpress/public_html/wp-content
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:  /srv/www/wordpress/wp-cli.yml
WP-CLI version: 2.5.0-alpha-c4c9f7e
```

Edit: I'm not sure why `wp cli info` reports PHP version 7.2, WordPress and `phpinfo()` both report PHP version 7.4.6

**Comment by schlessera** [comment]
Although PHP 7.1 introduced nullable types for function/method arguments and return values, what you're using here is a nullable typed property. Typed properties were only introduced with PHP 7.4.

The issue is that your PHP `cli` SAPI is PHP 7.2, so the above syntax is indeed not supported. This has nothing to do with WP-CLI, you're just executing PHP 7.4+ code in PHP 7.2.

When you're running PHP via a web server, it is run via `php-fpm` or a similar web SAPI. The command-line SAPI of PHP is a different one and can indeed be configured to use a different version. This is a matter of server configuration, and you should check with your hosting provider to make sure you're also running PHP 7.4 from a CLI context.

Note that this is a support request, and GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by Spartelfant** [comment]
Dear @schlessera,

My apologies for my erroneous bug report and my thanks for your concise explanation!

Kind regards,
Bart Kuijper
