### ISSUE TITLE
Change only security keys  with `wp core config`

### ISSUE THREAD

**Issue by wojsmol** [wp-cli/wp-cli#543]
Welcome
Whether at recent version of WP-CLI is possible to add to an existing wp-config only new value for salt, leaving other values unchanged by using the `wp core config`?
Regards

**Comment by bluepresley** [comment]
A couple of things have happened where we have needed this functionality, and indeed we turned to "wp help config" since it's description was "Manage the wp-config file."

The first scenario was a mishap on our part where a templated install of wordpress got shipped with the same wp-config.php file, and thus the same security keys. This was a security concern so we went back in and created new config files with WP-CLI. The second was when working on a but related to the WP NONCE system, and we kept getting the error "Are you sure you want to do this?"

The only way to remedy that during the debugging process was to change out the keys and delete the SESSION_TOKENS key from the wp_usermeta database.

So, if the option is still on the table to have something like ''wp config --regenerate-salts" is still an option, I'd lke to put in a +1 for the functionality. They may have been edge cases, but that would have been a real time saver.

In any case though, I wanted to post here and share this link. If a person does need regenerate keys quickly, this link will do that for you automatically, and you can simply copy and paste. Refresh the page to get a new set of keys.  Hope that helps someone.

https://api.wordpress.org/secret-key/1.1/salt/

**Comment by danielbachhuber** [comment]
> So, if the option is still on the table to have something like ''wp config --regenerate-salts" is still an option, I'd lke to put in a +1 for the functionality. They may have been edge cases, but that would have been a real time saver.

See https://github.com/wp-cli/ideas/issues/50
