### ISSUE TITLE
How can i update the parameter in wp-cli.phar

### ISSUE THREAD

**Issue by pjain287074** [wp-cli/wp-cli#5435]
wordpress version :5.2.0 
i am getting error 
Error: WP-CLI needs WordPress 3.7 or later to work properly. The version currently installed is 1.x.x.
For sake of security i have updated version of word press with some dummy value.
with that changes everything is working fine but somehow i need to update the PHAR as well to make it work properly
so i have updated    $minimum_version = '3.7'; with  $minimum_version = '1.x';
but after update its giving below error.

PHP Fatal error:  Uncaught PharException: phar "wp-cli.phar" has a broken signature in wp-cli.phar:3
Stack trace:
#0 /wp-cli.phar(3): Phar::mapPhar()
#1 {main}
  thrown in /wp-cli.phar on line 3

can you please help here how can use wp cli here

**Comment by wojsmol** [comment]
Smily restore proper WordPress version then use WP-CLI and restore fake vesion.

**Comment by schlessera** [comment]
The Phar is signed so that it cannot be manipulated, for security reasons.

I'd recommend against changing the WordPress version like that, as it will lead to all sorts of problems. For example, with such a WordPress versions, all plugins and themes that conditionally use advanced WordPress features for better security and/or performance will probably fall back to their less safe and less performant fallback, as they assume your WP version is not high enough.

This problem is the same for WP-CLI. Without a valid WordPress version number, WP-CLI will not know what functionality is available for use, and thus will probably disable a lot of features.

**Comment by schlessera** [comment]
The only way you can use WP-CLI like this will be to build it from source.

There's no plan for supporting a use case like the above in a published release, so I'm closing this as a `wontfix`.
