### ISSUE TITLE
Roadmap - new release

### ISSUE THREAD

**Issue by tobias992** [wp-cli/wp-cli#5478]
Hello,

there is any plan or any roadmap for new release? Official roadmap says all 3-4 Month updates.
But the last update was in 11/2019.

**Comment by wixaw** [comment]
I need this info too, 
I dare not use nightly in production, wp-cli is used to manage 60 website
Thanks

**Comment by tobias992** [comment]
Bye bye outdated project. Its a shame!

**Comment by Basilakis** [comment]
Would love to know how you guys also sponsor the project, so the roadmap can keep growing <3

**Comment by schlessera** [comment]
Nonsense, the project is not outdated.

The nightly version can currently be used just fine and should be as stable or more than the 2.4.0 release.

The reason why there was no release as of yet is because the project hit major compatibility issues with recent PHP versions, the DB support in WordPress and the many breaking changes within the internal WordPress APIs due to the bump in PHP minimum version at the same time.

Codewise, it is pretty much ready to be released now, but just when we were ready to start work on the release process, Travis CI pulled the plug on free support for open source projects.

Right now, I'm migrating tests and deployments over to GitHub Actions so we don't have to do the release "in the dark" (which I don't intend to do).

Consider that a lot of the contributions that used to help support this project have died down over the last year due to the current global situation. So any help in testing, debugging, fixing is greatly appreciated!

Also, I am aware the roadmap is not up-to-date. I was planning a more detailed roadmap with strategic version milestones when the above avalanche of compact problems just broke loose. Hopefully, when we've got over that bump, we can pick this more strategic approach back up.
