### ISSUE TITLE
WP CLI Requests dependency conflicts with WordPress Requests class.

### ISSUE THREAD

**Issue by ericp-mrel** [wp-cli/wp-cli#5484]
I am trying to manually run my plugin's cron job event using the wp cli using the following command: `wp cron event run event_name`

My cron job needs to download some external files from Amazon S3 for one, and whenever it tries to download the file fails with a 403 forbidden response using https://developer.wordpress.org/reference/functions/media_sideload_image/, after I investigated this issue for a few hours I finally narrowed the root cause. I kept trying to print debug statements from WordPress' Requests class, but they would never get output to the debug log and it looks like because this tool's requests dependency class and WordPress' are both not namespaced that the class from `rmccue/requests` is overriding and being used instead.

I really wish WordPress would start namespacing things more to avoid issues like this, but is there any way to address this issue other than writing my own functionality using my own curl request? This is just an unfortunate side-effect of not using namespaces in both places.

**Comment by ericp-mrel** [comment]
Is there anyway to resolve this issue?

**Comment by ronilaukkarinen** [comment]
Hello. We have noticed this as well. This causes "Response could not be parsed" in WordPress updates and is kinda serious security-wise since wp-core updates in this matter gets ignored. We'd like to use WP Core `parse_response` function instead but right now this wp-cli dependency overrides/conflicts with the core one.

For now we just have to remove wp-cli from our repositories and use it as stand alone instead.

**Comment by danielbachhuber** [comment]
Is this still an issue? If so, can someone provide steps to reproduce?

**Comment by schlessera** [comment]
@ericp-mrel Can you please test whether you're still seeing this issue with the latest version?
