### ISSUE TITLE
Allow "WP" in addition to "wp"

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/wp-cli#5589]
Would be great if all commands worked as uppercase WP too.

e.g.
`WP config set ...`
in addition to the existing
`wp config set ...`

**Comment by schlessera** [comment]
`wp` is the name of the file that you are executing when you are calling the WP-CLI binary. This is not under WP-CLI's control, it is completely up to the shell environment you're running it in and how you installed it. You can rename the file to whatever you want, like `wp-cli` instead of `wp`.

To make the command work across both uppercase and lowercase in your shell, you can try an alias like:
```shell
alias WP=wp
```

Here's a (random) article on how to use aliases: https://shapeshed.com/unix-alias/
