### ISSUE TITLE
--user=<user> argument unexpectedly looks up by ID when username is numeric

### ISSUE THREAD

**Issue by vihai** [wp-cli/wp-cli#5706]
Hello,

Many commands match username, ID and email automatically for the "user" parameters.

Sometimes users have numeric-only username and wp-cli commands match either the username or the ID incorrectly.

There should be a way to identify the user unequivocally.

Bye,

**Comment by danielbachhuber** [comment]
Thanks for the report, @vihai !

For reference, here's the lookup logic WP-CLI uses for the `--user=<user>` argument:

https://github.com/wp-cli/wp-cli/blob/ff3a4e0215172be8de5645ca58cb775715804919/php/WP_CLI/Fetchers/User.php#L27-L37

I think we could add a `WP_CLI_USE_USERNAME=1` environment variable (or similar) to force a username lookup instead of user ID.

Here's a previous report: https://github.com/wp-cli/wp-cli/issues/4780

**Comment by danielbachhuber** [comment]
We should show a warning when the situation is ambiguous (when value is numeric, check if `user_login` also exists for D and warn if so).
