### ISSUE TITLE
`--no-color` does not remove all color

### ISSUE THREAD

**Issue by quinncomendant** [wp-cli/wp-cli#5744]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

When using `--no-color`, ANSI color codes are still printed for error messages.

As an example, here's the output from running `wp plugin update --all` with normal output (e.g., implied `--color`) that shows color for `Warning:` and `Error:`:

<img width="898" alt="Screenshot 2023-03-02 at 11 17 38" src="https://user-images.githubusercontent.com/6884276/222504074-633ee9fd-566b-4fea-898a-6d860c980773.png">

After adding the `--no-color` option, the color for `Warning:` is gone, but `Error:` is still colorized:

<img width="893" alt="Screenshot 2023-03-02 at 11 17 48" src="https://user-images.githubusercontent.com/6884276/222504371-4834265b-4bf0-4237-a9dd-70e866bac19d.png">

**Describe what you expect as the correct outcome**

When using `--no-color`, wp-cli should never output ANSI color escape codes.

**Let us know what environment you are running this on**

```
OS:     Linux 5.14.0-162.12.1.el9_1.0.2.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jan 30 22:14:42 UTC 2023 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php
PHP version:    8.0.20
php.ini used:   /etc/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.5.16-MariaDB, for Linux (x86_64) using  EditLine wrapper
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/mhs/www.milehighsports.com
WP-CLI packages dir:
WP-CLI cache dir:       /home/mhs/.wp-cli/cache
WP-CLI global config:   
WP-CLI project config:  
WP-CLI version: 2.7.1
```

**Comment by danielbachhuber** [comment]
Thanks for the report, @quinncomendant.

I think this problem is specific to `wp plugin update`. The color state is somehow being reset in the multi update process:

<img width="901" alt="image" src="https://user-images.githubusercontent.com/36432/225361690-62cc724f-75e9-43fb-961b-26057d3ae80e.png">

**Comment by danielbachhuber** [comment]
This debugging is kinda interesting too:

```diff
diff --git a/php/WP_CLI/Loggers/Base.php b/php/WP_CLI/Loggers/Base.php
index 419ca373..9ff5d173 100644
--- a/php/WP_CLI/Loggers/Base.php
+++ b/php/WP_CLI/Loggers/Base.php
@@ -75,11 +75,14 @@ abstract class Base {
 	 * @param resource $handle Resource to write to. Defaults to STDOUT.
 	 */
 	protected function _line( $message, $label, $color, $handle = STDOUT ) { // phpcs:ignore PSR2.Methods.MethodDeclaration.Underscore -- Used in third party extensions.
+		var_dump( $this->in_color );
+		var_dump( $color );
 		if ( class_exists( 'cli\Colors' ) ) {
 			$label = Colors::colorize( "$color$label:%n", $this->in_color );
 		} else {
 			$label = "$label:";
 		}
+		var_dump( $label );
 		$this->write( $handle, "$label $message\n" );
 	}

```

`$this->in_color` is false in both places, but ends up as colorized in one of them:

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/36432/225364119-b28afc51-29a4-44f0-a357-6efb68814401.png">

**Comment by Dan-Q** [comment]
It looks like the problem is [in the table formatter](https://github.com/wp-cli/wp-cli/blob/main/php/WP_CLI/Formatter.php#L321-L323). When rendering a table (of plugins), the function first checks whether colorisation is enabled. If it is, it first disables it (so it can't scramble the table output), then after drawing the table it re-enables it.

It looks like it _always_ ends up re-enabling colorisation, in this case, even if it wasn't enabled in the first place. I'll investigate a little further at WCEU23 in case I can work out _why_...
