### ISSUE TITLE
Bug Report: wpcli Hangs When Attempting to Update Hacked WordPress Sites

### ISSUE THREAD

**Issue by unclesamwk** [wp-cli/wp-cli#5914]
Hello everyone,

We utilize wpcli to update several WordPress installations. Recently, we encountered an issue where wpcli becomes unresponsive when attempting to update a WordPress site that has been hacked, resulting in malicious code being injected into files. Upon investigation using strace, it was observed that wpcli attempts to read these compromised files, after which it ceases to proceed further.

It appears that wpcli is encountering a deadlock or similar issue when handling these compromised files, causing it to hang indefinitely. We believe there needs to be a solution implemented to address this issue, perhaps by implementing a mechanism to handle such situations gracefully without causing wpcli to hang.

We appreciate your attention to this matter and look forward to a resolution.

Thank you.

**Comment by schlessera** [comment]
First of all, be careful with whatever you are trying to do here. It seems obvious that whatever malicious code you have on your site is being processed by WP-CLI as well, so this can have malicious side effects depending on what the code is doing. Malicious code should never be executed at all, as the risk is too high for it to do something irreversible.

You should first use `wp core verify-checksums` to see if the malicious code is part of the core files. If it is, DON'T EXECUTE REGULAR WP-CLI COMMANDS!

WP-CLI can be used with flags like `--skip-plugins` or `--skip-themes` if the malicious code is found in plugins/themes.

To help you further, as @Luc45 pointed out, we need more detailed information and context. However, this sounds more like a support request rather than a bug report or feature request. So I'll close this issue here, as GitHub is only for the development of WP-CLI, not for supporting end users. Feel free to open a discussion on Slack in the `#cli` with more info to get help.
