### ISSUE TITLE
wp import can't find activated wordpress-importer plugin

### ISSUE THREAD

**Issue by madhippie** [wp-cli/wp-cli#625]
Hi there,

first of all - thanks to all of you who contribute to this awesome tool! 
I'm really falling in love with wp-cli.

Unfortunately I encountered a strange error: I'm about to migrate a lot of single wp blogs into one multisite installation. Batch export was fine, batch creation of empty sites was fine, batch activation of plugins was fine, but when I try to import my wxr files I encounter a strange error.

It's always dying with the error message: 

> WordPress Importer needs to be activated. Try 'wp plugin activate wordpress-importer'.

This is very strange, because I activated the plugin for the whole network. Both, via wp-cli and via the backend. If I login to the specific wp-backend, the importer is available.  I tried to debug it by myself, but I'm stuck. :) I have no idea why he isn't loading the needed classes (WP_Import and/or WP_Importer).

Thanks for any feedback!

**Comment by dangtrinhnt** [comment]
I just encountered this error and finally find out the reason:

I was using the **"--skip-plugins"** parameter when importing. That of-course ignored any plugins and did not load the WP_LOAD_IMPORTERS constant.

**Comment by commadelimited** [comment]
I'm using WP CLI for the first time, trying to import content from another site into mine. My command:
`wp import import-file.2021-02-06.001.xml --authors=mapping.csv --skip-plugins --skip-themes --skip-packages --debug`

Not having used this import functionality before, my understanding of the `--no-plugins` flag would that it doesn't import plugins from the remote site. It might be worth updating the documentation to be very clear about what that flag means so that other people don't run into this.

Thanks for the great software!

**Comment by mwittmann** [comment]
I've just run into the same scenario described by https://github.com/wp-cli/wp-cli/issues/625#issuecomment-44431941. I'm trying to create a custom WP-CLI command that imports a WXR file. It does not work because https://github.com/wp-cli/wp-cli/blob/v0.11.0/php/WP_CLI/Runner.php#L473 defining `WP_LOAD_IMPORTERS` for WP-CLI only runs for commands belonging to the `import` module.

As a hack workaround, I could run `wp config set WP_LOAD_IMPORTERS true --raw`, then run my WP-CLI custom command, and finally run `wp config delete WP_LOAD_IMPORTERS`. Is there a more elegant solution?
