### ISSUE TITLE
Add search-replace to db export

### ISSUE THREAD

**Issue by westonruter** [wp-cli/wp-cli#709]
As I [tweeted](https://twitter.com/westonruter/status/369698335218991104) yesterday, it would be great if WP-CLI added support for doing search-replace during the db export process, so that replacements would not have to be done in-place. In order to migrate a database from staging to production, for example, the process with WP-CLI is currently a bit convoluted. I gisted a [bash script](https://gist.github.com/westonruter/6277456) which incorporates the necessary steps with WP-CLI (here to also export only the specific tables for a site in a multisite network), but in general they would be:

1. `wp db export backup-snapshot.sql` (snapshot restore point)
2. `wp db search-replace staging.example.com www.example.com`
3. `wp db export production.sql`
4. `wp db import backup-snapshot.sql` (rollback to restore point)

So then as I later [tweeted](https://twitter.com/westonruter/status/369841513221480448), what if the `wp db export` subcommand accepted `--search` and `--replace` arguments to do the translations during the export process? For example, the above 4 commands could all be done with just one:

```bash
wp db export \
    --search=staging.example.com \
    --replace=www.example.com \
     > production.sql
```

This then would go along very nicely with the [proposed](https://github.com/wp-cli/wp-cli/issues/708#issuecomment-22952062) `wp db list-tables` to export a single site from a multisite network for promotion from staging to production. See #708.

As @scribu [points out](https://github.com/wp-cli/wp-cli/issues/708#issuecomment-22954832), this means we can't use `mysqldump` which is really fast. True, but we would avoid having to accompany each `wp search-replace` with two calls to `wp db export` and once to `wp db import`.

**Comment by lkraav** [comment]
Hmm, so a few years later, as far as I can tell only https://deliciousbrains.com/wp-migrate-db-pro/doc/multisite-tools-addon/ has CLI interface available for one direction "subsite -> single site" implementation.

Is anybody here still interested in getting WP-CLI modules for all migration combinations going:
* subsite -> single-site
* single-site -> subsite
* subsite -> subsite

I guess https://gist.github.com/westonruter/6277456 does subsite -> subsite right?

BackupBuddy probably has the most complete implementation of all these migration options, but they gave up developing it further long ago because of GUI and networking issues complexity. There's some intricacies involved in the process, such as managing the relevant user records on exports/imports. I believe that CLI could get this to the finish line, since it would eliminate a lot of complex timeout problems etc that hinder the GUI.

Thoughts?

**Comment by danielbachhuber** [comment]
> Thoughts?

If you want to work on subsite -> single-site, etc. database migrations, pull requests are welcome. This issue is for a separate enhancement: exporting a database with replaced values.
